-- RocketMount | Sources.lua
-- The data layer: one normalised record per mount the character is missing.
--
-- (!) NOTHING HERE IS READ FROM ANOTHER ADDON (28/09). The user's rule: *"Quando o addon estiver
-- em produção, quando outros usuários baixarem ele, não pode depender de nenhum outro addon"*.
-- Every fact comes from the game (the journal, the item's tooltip, the open vendor, the
-- Adventure Guide, reputation and currency) or from a table of OURS in `Data/`, generated by
-- the tools in `tools/`. What neither of them knows is not said.
local _, ns = ...
local L = ns.L

--------------------------------------------------------------------------------
-- Nome das fontes. O jogo já traduz essas strings; a tabela abaixo é só o plano B
-- para o caso de uma delas não existir neste cliente.
--------------------------------------------------------------------------------
local SOURCE_FALLBACK = {
    [0] = L["Unknown"],
    [1] = L["Drop"],
    [2] = L["Quest"],
    [3] = L["Vendor"],
    [4] = L["Profession"],
    [5] = L["Pet Battle"],
    [6] = L["Achievement"],
    [7] = L["World Event"],
    [8] = L["Promotion"],
    [9] = L["Trading Card Game"],
    [10] = L["Shop"],
    [11] = L["Discovery"],
    [12] = L["Trading Post"],
}

ns.SOURCE_NAMES = setmetatable({}, {
    __index = function(t, k)
        local s = _G["BATTLE_PET_SOURCE_" .. tostring(k)] or SOURCE_FALLBACK[k] or SOURCE_FALLBACK[0]
        rawset(t, k, s)
        return s
    end,
})

--------------------------------------------------------------------------------
-- Reputação
--------------------------------------------------------------------------------

-- Nível de reputação como o MCL escreve (em inglês, é o dado dele) → índice da API.
local STANDING_INDEX = {
    Hated = 1, Hostile = 2, Unfriendly = 3, Neutral = 4,
    Friendly = 5, Honored = 6, Revered = 7, Exalted = 8,
}

-- Reputação acumulada, a partir do Neutro, para chegar a cada nível. São os valores
-- padrão do jogo desde sempre; valem para facção clássica (amizade e renome não usam).
local STANDING_TOTAL = {
    [5] = 3000,    -- Amigável
    [6] = 9000,    -- Honrado
    [7] = 21000,   -- Reverenciado
    [8] = 42000,   -- Exaltado
}

---De QUEM é a reputação que estamos lendo.
---
---⛑ Relato do usuário, 21/09: *"eu não sei qual char meu tem a reputação e se tem, por que tá
---escrito que posso pegar, mas qual char tem essa reputação?"*. Ele está certo e a pergunta não
---tinha resposta na tela: o addon lê a reputação do personagem **conectado**, e nunca dizia isso.
---Desde o War Within parte das facções virou reputação de **Brigada** (vale para a conta inteira)
---e parte continua por personagem — e a diferença muda completamente o que o jogador tem que
---fazer. `C_Reputation.IsAccountWideReputation` (11.0+) responde qual é qual.
local function ReputationScope(factionId)
    if C_Reputation and C_Reputation.IsAccountWideReputation then
        local ok, conta = pcall(C_Reputation.IsAccountWideReputation, factionId)
        if ok and conta then return "conta" end
        if ok then return "personagem" end
    end
    return nil    -- cliente sem a função: não afirmamos nada
end

---A frase que diz de quem é aquele progresso. Sem ela "Exaltado" não informa nada: o jogador
---não sabe se é dele, deste personagem, ou de um alt que ele nem lembra.
local function ScopeLabel(factionId)
    local escopo = ReputationScope(factionId)
    if escopo == "conta" then
        return L["account-wide reputation"]
    elseif escopo == "personagem" then
        return string.format(L["this character only (%s)"], UnitName("player") or "?")
    end
    return nil
end

---(!) A REQUIREMENT WE CANNOT READ IS AN UNMET REQUIREMENT, NOT AN ABSENT ONE.
---
---This function used to return `nil` on six different paths -- faction unknown to the API,
---standing name we do not map, renown info missing. And the caller read `nil` as "this mount has
---no reputation gate", which is the opposite of the truth: the catalogue had just told us there
---IS one.
---
---The player caught it: *"os outros e reputacao que nenhum personagem meu tem e ta ali como se
---desse para comprar"*. Exactly right, and the mechanism is precise -- `GetFactionDataByID`
---returns nothing for a faction this character has never encountered, which is the very case
---where the mount is furthest away. The less we knew, the closer to the top it went.
---
---So it never returns nil once the catalogue says there is a requirement. Unreadable becomes
---`pct = 0` plus `unreadable`, and the label says why.
local function ReputationProgressHere(rep)
    if not rep or not rep.factionId then return nil end

    local nome = rep.factionName or "?"
    local alvo = STANDING_INDEX[rep.levelName or ""]

    -- (!) ANTES DE DIZER "ninguém tem", PERGUNTA AO LIVRO-CAIXA. A API só fala do personagem
    -- conectado, mas o `Roster` anotou o que cada um tinha ao entrar — e a pergunta do usuário
    -- era exatamente essa: *"consegue mostrar qual personagem tem a reputação, caso seja
    -- legada?"*. Reputação de Brigada não precisa disto; a legada, sim.
    local outro, quem
    if ns.Roster then outro, quem = ns.Roster.Line(rep.factionId, alvo) end
    local desconhecida = {
        kind = "rep", factionName = nome, pct = 0, unreadable = true,
        outroChar = outro,
        -- Who the line names, for the card's "no longer exists" button.
        named = quem and { key = quem.key, name = quem.name, seen = quem.seen } or nil,
        label = outro
            and string.format(L["%s: %s — this character does not have it"], nome, outro)
            or string.format(L["%s: no reputation with this faction on this character"], nome),
    }

    -- (!) A COVENANT OF THE SHADOWLANDS (28/09). Its renown is not a faction's: it belongs to
    -- the covenant the character is IN, and the game answers for that one only
    -- (`C_Covenants.GetActiveCovenantID`, `C_CovenantSanctumUI.GetRenownLevel`). A character
    -- of another covenant, or of none, has not walked any of this road.
    if rep.renown and rep.covenant then
        local ativo, tenho
        if C_Covenants and C_Covenants.GetCovenantData then
            local ok, dado = pcall(C_Covenants.GetCovenantData, rep.covenant)
            if ok and type(dado) == "table" and type(dado.name) == "string" and dado.name ~= ""
                and not (issecretvalue and issecretvalue(dado.name)) then
                nome = dado.name
            end
        end
        if C_Covenants and C_Covenants.GetActiveCovenantID then
            local ok, id = pcall(C_Covenants.GetActiveCovenantID)
            if ok and type(id) == "number" then ativo = id end
        end
        if C_CovenantSanctumUI and C_CovenantSanctumUI.GetRenownLevel then
            local ok, n = pcall(C_CovenantSanctumUI.GetRenownLevel)
            if ok and type(n) == "number" then tenho = n end
        end
        if ativo == nil or (ativo == rep.covenant and tenho == nil) then return desconhecida end
        local need = rep.level or 1
        if ativo ~= rep.covenant then
            return {
                kind = "rep", factionName = nome, have = 0, need = need, pct = 0,
                label = string.format(L["%s: renown %d, and this character is not in this covenant"], nome, need),
            }
        end
        return {
            kind = "rep", factionName = nome, have = tenho, need = need,
            pct = math.min(1, tenho / math.max(1, need)),
            label = tenho >= need
                and string.format(L["%s: renown %d reached (you are at %d)"], nome, need, tenho)
                or string.format(L["%s: renown %d of %d"], nome, tenho, need),
        }
    end

    -- (!) FRIENDSHIP IS MEASURED IN POINTS (05/10). Reported by players: reputation mounts
    -- stuck at 0%. Every friendship was: the table knew the NAME of the rank asked for ("Best
    -- Friend", "Rank 6"), which is no standing of `C_Reputation`, and the mount fell into "asks
    -- for X, which I cannot measure" whatever the character had. The game answers in points
    -- (`C_GossipInfo.GetFriendshipReputation(...).standing`, what its own reputation panel
    -- reads), and the table has how many points reach the rank (`need`, from the game's
    -- FriendshipRepReaction). The rank's name on the line is the game's, in the player's
    -- language.
    if rep.friendship and type(rep.need) == "number" and rep.need > 0 then
        if not (C_GossipInfo and C_GossipInfo.GetFriendshipReputation) then return desconhecida end
        local ok, f = pcall(C_GossipInfo.GetFriendshipReputation, rep.factionId)
        if not ok or type(f) ~= "table" or (issecretvalue and issecretvalue(f.standing))
            or type(f.friendshipFactionID) ~= "number" or f.friendshipFactionID <= 0
            or type(f.standing) ~= "number" then
            return desconhecida
        end
        if type(f.name) == "string" and f.name ~= "" and not (issecretvalue and issecretvalue(f.name)) then
            nome = f.name
        end
        local grau = type(f.reaction) == "string" and not (issecretvalue and issecretvalue(f.reaction))
            and f.reaction or "?"
        local tenho = math.max(0, f.standing)
        if tenho >= rep.need then
            return {
                kind = "rep", factionName = nome, pct = 1, have = tenho, need = rep.need,
                scope = ReputationScope(rep.factionId),
                label = string.format(L["%s: rank reached (%s)"], nome, grau),
            }
        end
        return {
            kind = "rep", factionName = nome, pct = tenho / rep.need, have = tenho, need = rep.need,
            scope = ReputationScope(rep.factionId),
            label = string.format(L["%s: %s of %s (%s)"], nome,
                BreakUpLargeNumbers(tenho), BreakUpLargeNumbers(rep.need), grau),
        }
    end

    -- Renome (facção moderna): o progresso é o nível, e a API responde direto.
    if rep.renown and C_MajorFactions and C_MajorFactions.GetMajorFactionRenownInfo then
        -- The faction's name in the player's language: the table's is English.
        if C_MajorFactions.GetMajorFactionData then
            local okN, dado = pcall(C_MajorFactions.GetMajorFactionData, rep.factionId)
            if okN and type(dado) == "table" and type(dado.name) == "string" and dado.name ~= ""
                and not (issecretvalue and issecretvalue(dado.name)) then
                nome = dado.name
            end
        end
        local ok, info = pcall(C_MajorFactions.GetMajorFactionRenownInfo, rep.factionId)
        if ok and info and info.renownLevel then
            local need = rep.level or 1
            local have = info.renownLevel
            -- (!) "renome 25 de 5" NÃO É FRASE. O usuário leu e perguntou: *"eu tenho 25 e precisa
            -- de 5? isso que entendi?"*. A forma "X de Y" só faz sentido enquanto X caminha para
            -- Y; passado o Y, ela vira charada. Cumprido se diz cumprido.
            local texto
            if have >= need then
                texto = string.format(L["%s: renown %d reached (you are at %d)"], nome, need, have)
            else
                texto = string.format(L["%s: renown %d of %d"], nome, have, need)
            end
            local escopo = ScopeLabel(rep.factionId)
            return {
                kind = "rep", factionName = nome,
                have = have, need = need,
                pct = math.min(1, have / math.max(1, need)),
                scope = ReputationScope(rep.factionId),
                label = texto .. (escopo and ("  —  " .. escopo) or ""),
            }
        end
        return desconhecida
    end

    if not (C_Reputation and C_Reputation.GetFactionDataByID) then return desconhecida end
    local ok, data = pcall(C_Reputation.GetFactionDataByID, rep.factionId)
    if not ok or not data or not data.reaction then return desconhecida end

    local name = data.name or nome

    -- Paragon: a barra que continua depois do Exaltado, e que reinicia a cada baú.
    if rep.levelName == "Paragon" then
        if C_Reputation.GetFactionParagonInfo then
            local okP, value, threshold = pcall(C_Reputation.GetFactionParagonInfo, rep.factionId)
            if okP and value and threshold and threshold > 0 then
                local into = value % threshold
                return {
                    kind = "rep", factionName = name, pct = into / threshold,
                    scope = ReputationScope(rep.factionId),
                    label = string.format(L["%s: %s of %s to the next cache"],
                        name, BreakUpLargeNumbers(into), BreakUpLargeNumbers(threshold)),
                }
            end
        end
        return desconhecida
    end

    local targetIdx = STANDING_INDEX[rep.levelName or ""]
    if not targetIdx then
        -- Nível que não é patamar de reputação (ex.: "Professional", que é perícia de
        -- profissão). Não dá para medir, e por isso mesmo NÃO está cumprido.
        return {
            kind = "rep", factionName = name, pct = 0, unreadable = true,
            label = string.format(L["%s: asks for %s, which I cannot measure"], name, rep.levelName or "?"),
        }
    end

    if data.reaction >= targetIdx then
        return {
            kind = "rep", factionName = name, pct = 1,
            scope = ReputationScope(rep.factionId),
            label = string.format(L["%s: already %s%s"], name,
                _G["FACTION_STANDING_LABEL" .. targetIdx] or L["at the standing"],
                ScopeLabel(rep.factionId) and ("  —  " .. ScopeLabel(rep.factionId)) or ""),
        }
    end

    local total = STANDING_TOTAL[targetIdx]
    local standing = data.currentStanding or 0
    if total and standing >= 0 then
        local pct = math.min(1, standing / total)
        return {
            kind = "rep", factionName = name, pct = pct,
            have = standing, need = total,
            scope = ReputationScope(rep.factionId),
            label = string.format(L["%s: %s of %s to %s%s"],
                name, BreakUpLargeNumbers(standing), BreakUpLargeNumbers(total),
                _G["FACTION_STANDING_LABEL" .. targetIdx] or L["the standing"],
                ScopeLabel(rep.factionId) and ("  —  " .. ScopeLabel(rep.factionId)) or ""),
        }
    end

    local pct = (data.reaction - 1) / math.max(1, targetIdx - 1)
    return {
        kind = "rep", factionName = name, pct = math.max(0, math.min(1, pct)),
        scope = ReputationScope(rep.factionId),
        label = string.format("%s: %s", name,
            _G["FACTION_STANDING_LABEL" .. data.reaction] or ""),
    }
end

-- (!) THE CLOSEST OF YOUR CHARACTERS (25/09). The user: *"se um char x tiver a reputação que
-- precisa ou que falta pouco, só avisar e atualizar esta lista, e dai a lista pega tudo
-- independente de facção e dizer qual dos chars que está mais proximo de pegar"*. A mount is
-- collected for the whole account, so for a LEGACY reputation (one per character) the number is
-- the best character's, and the row names it. This reverses the rule of 22/09 ("whoever has it
-- is another character, so it is not met") -- the user's call.
--
-- Only legacy standings: a Warband reputation is the same on every character, and renown and
-- friendship are not in the ledger. The ledger is what each character had at its last login,
-- and the label says whose number it is.
local function BestAlt(factionId, alvo)
    if not (ns.Roster and ns.Roster.WhoHas) then return nil end
    local melhor
    for _, c in ipairs(ns.Roster.WhoHas(factionId)) do
        local pct
        if c.reaction >= alvo then
            pct = 1
        elseif c.standing and STANDING_TOTAL[alvo] and c.standing >= 0 then
            pct = math.min(1, c.standing / STANDING_TOTAL[alvo])
        else
            pct = math.max(0, math.min(1, (c.reaction - 1) / math.max(1, alvo - 1)))
        end
        if not melhor or pct > melhor.pct then
            melhor = { key = c.key, name = c.name, class = c.class, pct = pct,
                standing = c.standing, reaction = c.reaction, seen = c.seen }
        end
    end
    return melhor
end

-- (!) ONE FACTION PER SIDE OF THE WAR (05/10). The talbuks are sold by the Mag'har to the Horde
-- and by the Kurenai to the Alliance; the table had one of the two, and the other side read "no
-- reputation with this faction", 0%, whatever it had. The table now has the pair
-- (`altFactionId`), with the side of each, and the character is measured against its own.
-- A character of neither side yet is measured against the first.
local function ForMySide(rep)
    if type(rep) ~= "table" or not rep.altFactionId then return rep end
    local lado = UnitFactionGroup and UnitFactionGroup("player")
    lado = (lado == "Alliance" and "A") or (lado == "Horde" and "H") or nil
    if lado and rep.altSide == lado and rep.side ~= lado then
        local outra = {}
        for k, v in pairs(rep) do outra[k] = v end
        outra.factionId, outra.factionName = rep.altFactionId, rep.altFactionName or rep.factionName
        if rep.altNeed ~= nil then outra.need = rep.altNeed end
        outra.altFactionId, outra.altFactionName, outra.altNeed = nil, nil, nil
        return outra
    end
    return rep
end

local ReputationOfMySide

local function ReputationProgress(rep)
    local r = ReputationOfMySide(ForMySide(rep))
    -- One of a pair: the item at hand may be the other side's, and its line names a faction
    -- this character can never have (BuildList sets that line aside).
    if r and type(rep) == "table" and rep.altFactionId then r.paired = true end
    return r
end

ReputationOfMySide = function(rep)
    local aqui = ReputationProgressHere(rep)
    if aqui and rep and rep.factionId then aqui.factionId = aqui.factionId or rep.factionId end
    if not (rep and rep.factionId) or rep.renown or rep.friendship then return aqui end
    local alvo = STANDING_INDEX[rep.levelName or ""]
    if not alvo or ReputationScope(rep.factionId) == "conta" then return aqui end

    local melhor = BestAlt(rep.factionId, alvo)
    local meu = (aqui and not aqui.unreadable and aqui.pct) or 0
    if aqui then aqui.altPct = melhor and melhor.pct or nil end
    if not melhor or melhor.pct <= meu then return aqui end

    local nome = (aqui and aqui.factionName) or rep.factionName or "?"
    local nivel = _G["FACTION_STANDING_LABEL" .. alvo] or rep.levelName
    local texto
    if melhor.pct >= 1 then
        texto = string.format(L["%s: %s is already %s — buy it on that character"],
            nome, melhor.name, nivel)
    elseif melhor.standing and STANDING_TOTAL[alvo] then
        texto = string.format(L["%s: %s is at %s of %s to %s — the closest of your characters"],
            nome, melhor.name, BreakUpLargeNumbers(melhor.standing),
            BreakUpLargeNumbers(STANDING_TOTAL[alvo]), nivel)
    else
        texto = string.format(L["%s: %s is %s — the closest of your characters"], nome,
            melhor.name, _G["FACTION_STANDING_LABEL" .. melhor.reaction] or "?")
    end
    return {
        kind = "rep", factionId = rep.factionId, factionName = nome,
        pct = melhor.pct, char = melhor.name, charClass = melhor.class,
        outroChar = melhor.name, minePct = meu,
        named = { key = melhor.key, name = melhor.name, seen = melhor.seen },
        scope = "personagem", label = texto,
    }
end

--------------------------------------------------------------------------------
-- THE DROP CHANCE, FROM OUR OWN TABLE
--
-- (!) No addon of ours depends on another one (the user, 27/09). The list took the chance from
-- MCL and from nowhere else -- the window's footer said so in red -- while `Data/MobDrops.lua`
-- (Wowhead's "Dropped by", keyed by creature) sat in the addon feeding only the rare alert and
-- the map. It knows 158 mounts; MCL knows the chance of 192, and 102 are the same ones.
--
-- Which number, when several creatures drop the mount: THE BEST creature's, among those with at
-- least ten drops seen. The player goes where it drops most, and a pooled average is dragged
-- down by whoever is killed most (Amber Primordial Direhorn: 1 in 21 from the Warbringers, 1 in
-- 133 pooled with the scouts that almost never drop it). With no creature at ten drops, the
-- pool of all of them, marked rough.
--
-- (!) A CREATURE THAT DROPS IT NEARLY EVERY TIME IS NOT A FARM. Measured against MCL on 27/09:
-- Mail Muncher is "1 in 1" on Wowhead and 1 in 100 in MCL; Grey Riding Camel, Alunira, the
-- Void-Scarred Gryphon the same. The kill is certain -- finding, summoning or unlocking the
-- creature is the whole task, and no drop table measures that. Shown as a chance it would put
-- those mounts on top of the farms. So from half the kills up there is NO chance number: the
-- mount stays without an estimate, and the row says why.
--------------------------------------------------------------------------------
local SURE_DROP = 0.5     -- from here up the kill is not where the luck is
local ENOUGH_DROPS = 10   -- Wowhead's sample below this is a rough estimate
local porItem             -- item -> { n, rough, npc, name, sure, creatures }
local indexadoDe          -- the table `porItem` was built from

local function IndexarChance()
    porItem = {}
    if type(ns.MobDrops) ~= "table" then return end
    local soma = {}
    for npc, rec in pairs(ns.MobDrops) do
        if type(rec) == "table" then
            for _, d in ipairs(rec) do
                local c, o = tonumber(d.count), tonumber(d.outof)
                if d.item and c and o and c > 0 and o > 0 then
                    local s = soma[d.item] or { count = 0, outof = 0, creatures = 0 }
                    soma[d.item] = s
                    s.count, s.outof, s.creatures = s.count + c, s.outof + o, s.creatures + 1
                    local taxa = c / o
                    if c >= ENOUGH_DROPS and (not s.melhor or taxa > s.melhor) then
                        s.melhor, s.npc, s.name = taxa, npc, rec.name
                    end
                    if not s.qualquer or taxa > s.qualquer then
                        s.qualquer, s.npcQualquer, s.nomeQualquer = taxa, npc, rec.name
                    end
                end
            end
        end
    end
    for item, s in pairs(soma) do
        local taxa = s.melhor or (s.count / s.outof)
        porItem[item] = {
            n = 1 / taxa,
            rough = not s.melhor,
            npc = s.npc or s.npcQualquer,
            name = s.name or s.nomeQualquer,
            sure = taxa >= SURE_DROP,
            creatures = s.creatures,
        }
    end
end

---The chance of the mount this item teaches, from our own table.
---@return table|nil `{ n = 1-in-n, rough, npc, name, sure, creatures }`
function ns.OwnChance(itemID)
    if not itemID then return nil end
    -- The table is swapped in tests and never in game: indexed again when it is another one.
    if not porItem or indexadoDe ~= ns.MobDrops then
        IndexarChance()
        indexadoDe = ns.MobDrops
    end
    return porItem[itemID]
end

--------------------------------------------------------------------------------
-- WHERE IT IS GOT, FROM OUR OWN TABLE
--
-- (!) The user, 28/09: *"falta os pontos no mapa como mostrei em prints de vendedores, missão e
-- etc"*. The map took vendors, treasures and quest givers from MCL, read at run time; alone, it
-- had the rares and nothing else -- and no addon of ours depends on another one.
-- `Data/MountPlaces.lua` (tools/coletar_lugares.py) holds, for each mount, who sells it, the
-- chest it is in and the quest that rewards it, each with its place on the map.
--
-- What comes out has the shape the rest of the addon already reads (it was MCL's): `vendors`
-- and `coords`, in the map's own scale. A vendor or a quest of the OTHER faction is left out.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- IS THE EVENT ON? THE GAME'S CALENDAR ANSWERS
--
-- (!) The user's screenshot, 28/09: a "Vendor" marker in The Jade Forest with 39 raid mounts in
-- its tooltip, and nobody there -- *"não achei nenhum NPC, revise todos, precisa ter certeza"*.
-- The vendor was of WoW Remix: Mists of Pandaria, which ended. A vendor of an event
-- (`event` in Data/MountPlaces.lua) is in the world only while the event is on, and who knows
-- that is the calendar: `CalendarDayEvent.eventID` is the id of the game's holiday.
--
-- Whatever cannot be told is "not on": no calendar, no answer, a secret value, an event the
-- table has no id for. A marker that is missing costs a look at the journal; a marker with
-- nobody there costs the trip.
--------------------------------------------------------------------------------
local CALENDAR_TTL = 60
local hoje, hojeEm
-- (!) THE READING CANNOT START ITSELF AGAIN (02/10, "C stack overflow" recorded by the game).
-- `C_Calendar.SetAbsMonth` fires CALENDAR_UPDATE_EVENT_LIST before it returns; the handler of
-- that event reads the calendar; the reading sets the month again. The recorded stack is that
-- loop, until the stack ran out. While a reading is at work, the event it causes is not news.
local lendo = false

---A moment of the calendar ({ year, month, monthDay, hour, minute }) as one number to compare.
local function Instante(t)
    if type(t) ~= "table" then return nil end
    local y, m, d = tonumber(t.year), tonumber(t.month), tonumber(t.monthDay)
    if not (y and m and d) then return nil end
    return (((y * 12 + m) * 31 + d) * 24 + (tonumber(t.hour) or 0)) * 60 + (tonumber(t.minute) or 0)
end

---@return table|nil `{ [holiday id] = title }` of what is on right now; nil when the game does not say
local function LerCalendario()
    if not (C_Calendar and C_DateAndTime and C_Calendar.GetNumDayEvents and C_Calendar.GetDayEvent
        and C_Calendar.GetMonthInfo and C_DateAndTime.GetCurrentCalendarTime) then
        return nil
    end
    -- The calendar answers with secrets while chat messaging is locked down.
    -- (!) `C_ChatInfo.InChatMessagingLockdown` (ChatInfoDocumentation.lua, 12.1.0.69933). This
    -- asked a GLOBAL of that name, which the game does not have: the guard was never on, and
    -- the harness passed because it defined the global itself. Found by `tools/globais.py`.
    local trancado = C_ChatInfo and C_ChatInfo.InChatMessagingLockdown
    if trancado and trancado() then return nil end
    local okA, agora = pcall(C_DateAndTime.GetCurrentCalendarTime)
    local okM, mes = pcall(C_Calendar.GetMonthInfo)
    if not (okA and okM and type(agora) == "table" and type(mes) == "table") then return nil end
    local momento = Instante(agora)
    if not (momento and tonumber(mes.month) and tonumber(mes.year)) then return nil end
    -- The calendar counts the months from the one it has SELECTED, which is the current one
    -- until the player browses it. Browsed away, nothing is read: moving it back would move
    -- the window the player is looking at.
    if mes.month ~= agora.month or mes.year ~= agora.year then
        if (CalendarFrame and CalendarFrame.IsShown and CalendarFrame:IsShown()) or not C_Calendar.SetAbsMonth then
            return nil
        end
        lendo = true
        local moveu = pcall(C_Calendar.SetAbsMonth, agora.month, agora.year)
        lendo = false
        if not moveu then return nil end
    end
    local okN, n = pcall(C_Calendar.GetNumDayEvents, 0, agora.monthDay)
    if not okN or type(n) ~= "number" or (issecretvalue and issecretvalue(n)) then return nil end
    local out = {}
    for i = 1, n do
        local ok, ev = pcall(C_Calendar.GetDayEvent, 0, agora.monthDay, i)
        local id = ok and type(ev) == "table" and ev.eventID
        if id ~= nil and issecretvalue and issecretvalue(id) then return nil end
        if type(id) == "number" then
            -- The day an event starts or ends it is on for part of the day only.
            local de, ate = Instante(ev.startTime), Instante(ev.endTime)
            if not (de and momento < de) and not (ate and momento > ate) then
                local titulo = ev.title
                if type(titulo) ~= "string" or (issecretvalue and issecretvalue(titulo)) then titulo = true end
                out[id] = titulo
            end
        end
    end
    return out
end

---@return boolean on, string|nil title the event's name as the calendar gives it, in the player's language
function ns.EventOn(nome)
    local T = ns.MountPlaces
    local e = type(T) == "table" and type(T.event) == "table" and T.event[nome]
    if type(e) ~= "table" or type(e.ids) ~= "table" then return false end
    -- The event of a timerunner: a character of the ordinary world has no way to its vendors.
    if e.timerunning then
        if type(PlayerGetTimerunningSeasonID) ~= "function" then return false end
        local ok, temporada = pcall(PlayerGetTimerunningSeasonID)
        if not ok or type(temporada) ~= "number" then return false end
    end
    local agora = GetTime and GetTime() or 0
    if not hojeEm or agora - hojeEm > CALENDAR_TTL or agora < hojeEm then
        local ok, lido = pcall(LerCalendario)
        hoje, hojeEm = ok and lido or nil, agora
    end
    if type(hoje) ~= "table" then return false end
    for _, id in ipairs(e.ids) do
        if hoje[id] then return true, type(hoje[id]) == "string" and hoje[id] or nil end
    end
    return false
end

---The game says its list of events changed: the calendar is read again.
---@return boolean changed whether what is ON changed -- the list is built again only then, and
---the event comes every time the player turns a page of the calendar
function ns.CalendarChanged()
    if lendo then return false end
    local function Chave(t)
        if type(t) ~= "table" then return "?" end
        local ids = {}
        for id in pairs(t) do ids[#ids + 1] = id end
        table.sort(ids)
        return table.concat(ids, ",")
    end
    local antes = Chave(hoje)
    local ok, lido = pcall(LerCalendario)
    hoje, hojeEm = ok and lido or nil, GetTime and GetTime() or 0
    return Chave(hoje) ~= antes
end

--------------------------------------------------------------------------------
-- THE TRADING POST: WHAT IS ON OFFER THIS MONTH, AND WHETHER IT IS THERE
--
-- (!) The user's second screenshot, 28/09: the vendor of the Trading Post of Stormwind, "Sells:
-- Celestial Steed 61%, The Dreadwake 69%, Riding Turtle 1%", and nobody at the place. The list
-- of what a Trading Post vendor sells is every mount that ever went through it; the month's
-- offer is the game's to say (`C_PerksProgram`), and so is whether the Trading Post is there
-- for this character (the game's own landmark, `C_AreaPoiInfo`).
--
-- The game answers about the offer when it has the data -- for sure with the Trading Post
-- open -- so what it said is KEPT (account-wide: the offer is the account's), each mount until
-- its own offer ends, and the ones with no end until the month turns. Nothing kept and
-- nothing answered is "not on offer": the mount goes back to what its journal says it is.
--------------------------------------------------------------------------------
local function MesDe(t)
    return date and date("%Y-%m", t) or ""
end

---Read what the game says is on offer, and keep it.
---@return boolean changed whether the set of mounts on offer changed
function ns.ReadPerks()
    if not (ns.db and C_PerksProgram and C_PerksProgram.GetAvailableVendorItemIDs
        and C_PerksProgram.GetVendorItemInfo) then
        return false
    end
    local ok, ids = pcall(C_PerksProgram.GetAvailableVendorItemIDs)
    -- An empty list is the game not having the data yet, not a month with nothing on offer.
    if not ok or type(ids) ~= "table" or #ids == 0 then return false end
    local agora = time()
    local montarias, lidos = {}, 0
    for _, id in ipairs(ids) do
        local okI, info = pcall(C_PerksProgram.GetVendorItemInfo, id)
        if okI and type(info) == "table" then
            lidos = lidos + 1
            local m, resta = info.mountID, info.timeRemaining
            if issecretvalue and (issecretvalue(m) or issecretvalue(resta)) then return false end
            if type(m) == "number" and m > 0 then
                if info.doesNotExpire ~= true and type(resta) == "number" and resta > 0 then
                    montarias[m] = agora + resta
                else
                    montarias[m] = true
                end
            end
        end
    end
    if lidos == 0 then return false end
    local antes = ns.db.perks
    local function Chave(t)
        local ms = {}
        for m in pairs(type(t) == "table" and type(t.mounts) == "table" and t.mounts or {}) do ms[#ms + 1] = m end
        table.sort(ms)
        return table.concat(ms, ",")
    end
    local novo = { read = agora, mounts = montarias }
    ns.db.perks = novo
    if ns.Log and ns.Log.Add then
        pcall(ns.Log.Add, "perks", { items = lidos, mounts = Chave(novo) })
    end
    return Chave(antes) ~= Chave(novo)
end

---Is this mount on offer at the Trading Post now, by what the game said?
function ns.PerksOffer(mountID)
    local p = ns.db and ns.db.perks
    if type(p) ~= "table" or type(p.mounts) ~= "table" or type(p.read) ~= "number" then return false end
    local ate = p.mounts[mountID]
    local agora = time()
    if type(ate) == "number" then return ate > agora end
    -- An offer with no end of its own is the month's: read in another month, it is over.
    return ate == true and MesDe(p.read) == MesDe(agora)
end

---Does the game draw its own landmark of this Trading Post, for this character?
local function MarcoNoMapa(ficha)
    if type(ficha.poi) ~= "number" then return true end     -- no landmark known: nothing to ask
    if not (C_AreaPoiInfo and C_AreaPoiInfo.GetAreaPOIInfo) then return false end
    local ok, info = pcall(C_AreaPoiInfo.GetAreaPOIInfo, ficha.poiMap, ficha.poi)
    return ok and type(info) == "table"
end
ns.PerksLandmark = MarcoNoMapa

---The vendors of a map that are there only SOMETIMES, and what the game says of each now: for
---`/rmt pins`, which is how "there is no marker here" is told from "the addon does not know".
---@return table[] `{ { name, npcId, event, on, title, perks, landmark, offers }, ... }`
function ns.ConditionalVendors(mapID)
    local T = ns.MountPlaces
    local out = {}
    if type(T) ~= "table" or type(T.npc) ~= "table" then return out end
    local ofertas = 0
    for m in pairs(ns.db and type(ns.db.perks) == "table" and type(ns.db.perks.mounts) == "table"
        and ns.db.perks.mounts or {}) do
        if ns.PerksOffer(m) then ofertas = ofertas + 1 end
    end
    for id, v in pairs(T.npc) do
        if type(v) == "table" and (v.event ~= nil or v.perks) and type(v.where) == "table" and v.where[mapID] then
            local reg = { name = v.name, npcId = id }
            if v.event ~= nil then
                reg.event = v.event
                reg.on, reg.title = ns.EventOn(v.event)
            end
            if v.perks then
                reg.perks, reg.landmark, reg.offers = true, MarcoNoMapa(v), ofertas
            end
            out[#out + 1] = reg
        end
    end
    table.sort(out, function(a, b) return a.npcId < b.npcId end)
    return out
end

---A vendor or a quest that counts for THIS character, now, for THIS mount: of its faction;
---when it is of an event, with the event on; when it is of the Trading Post, with the mount on
---offer and the Trading Post there.
local function DoMeuLado(ficha, mountID)
    if type(ficha) ~= "table" then return false end
    if ficha.event ~= nil and not ns.EventOn(ficha.event) then return false end
    if ficha.perks and not (ns.PerksOffer(mountID) and MarcoNoMapa(ficha)) then return false end
    if not ficha.side then return true end
    local meu = UnitFactionGroup and UnitFactionGroup("player") or nil
    return not meu or ficha.side == meu
end

---A table's `where`, as a list in a fixed order (the map's id, then the order of the table).
local function Pontos(where)
    local mapas, out = {}, {}
    for mapa in pairs(type(where) == "table" and where or {}) do mapas[#mapas + 1] = mapa end
    table.sort(mapas)
    for _, mapa in ipairs(mapas) do
        local pts = where[mapa]
        for i = 1, #pts - 1, 2 do
            -- `i` is which place of the map it is, in the order of the table
            out[#out + 1] = { m = mapa, x = pts[i], y = pts[i + 1], i = (i + 1) / 2 }
        end
    end
    return out
end

---Is it the turn of a place that takes turns? The game has a world quest for each group of the
---broken mirrors of Revendreth, active while the group is (and done, once the player did it).
---
---A character the mirrors are not for -- another covenant, the network not yet built -- has
---none of the quests, and no marker: the game's answer is the requirement too. A client that
---cannot be asked at all leaves every place on the map: they are where the thing may be.
local function NaVez(quest)
    if type(quest) ~= "number" then return true end
    if not (C_TaskQuest and C_TaskQuest.IsActive) then return true end
    local ok, ativa = pcall(C_TaskQuest.IsActive, quest)
    if not ok then return true end
    if issecretvalue and issecretvalue(ativa) then return false end
    if ativa then return true end
    if C_QuestLog and C_QuestLog.IsQuestFlaggedCompleted then
        local okF, feita = pcall(C_QuestLog.IsQuestFlaggedCompleted, quest)
        if okF and feita and not (issecretvalue and issecretvalue(feita)) then return true end
    end
    return false
end
ns.PlaceTurn = NaVez

---Is a landmark that comes and goes (a ritual site, the way in to the visions) on now?
---(!) THE RITUAL SITE MOVES (30/09). The user: *"os rituais depende de onde está o ritual, ou
---seja, qual mapa"*. The game has one landmark per site, each behind a world state, and draws
---the one that is on: the marker follows the game's. As with the places that take turns, a
---client that cannot be asked leaves the place on the map; a client that answers "no such
---landmark here" takes it off.
local function MarcoAoVivo(mapa, poi)
    if not (C_AreaPoiInfo and C_AreaPoiInfo.GetAreaPOIInfo) then return true end
    local ok, info = pcall(C_AreaPoiInfo.GetAreaPOIInfo, mapa, poi)
    if not ok then return true end
    return type(info) == "table"
end
ns.LandmarkOn = MarcoAoVivo

---The name of an object in the player's language: the game has no way to ask it by id, so the
---translation is ours (`Locales/ptBR_Places.lua`) and English is what is left.
local function NomeDoObjeto(id, ingles)
    local t = ns.PlaceNamesLocal and ns.PlaceNamesLocal.object
    local nome = type(t) == "table" and t[id]
    return type(nome) == "string" and nome or ingles
end

---@param sourceType number|nil what the game's journal says the mount comes from (2 = quest)
---@return table|nil `{ vendors, coords, quests, box }`
function ns.OwnPlaces(mountID, sourceType)
    local T = ns.MountPlaces
    local m = type(T) == "table" and type(T.mount) == "table" and T.mount[mountID]
    if type(m) ~= "table" then return nil end
    local out = { vendors = {}, coords = {}, quests = {}, box = type(m.box) == "table" and m.box or nil }

    for _, id in ipairs(type(m.npc) == "table" and m.npc or {}) do
        local v = type(T.npc) == "table" and T.npc[id]
        if DoMeuLado(v, mountID) then
            local pts = Pontos(v.where)
            -- The event that is on, by the name the calendar gives it (the player's language).
            local evento = v.event ~= nil and select(2, ns.EventOn(v.event)) or nil
            for _, p in ipairs(pts) do
                out.vendors[#out.vendors + 1] = {
                    npc = v.name, npcId = id, m = p.m, x = p.x, y = p.y, guild = v.guild == true,
                    event = evento,
                }
            end
            -- A vendor nobody has placed is still a vendor: the card names it.
            if #pts == 0 then
                out.vendors[#out.vendors + 1] = { npc = v.name, npcId = id, guild = v.guild == true }
            end
        end
    end
    -- (!) BEHIND A WAY IN, THE CHEST IS NOT A PLACE (28/09). The twelve chests of the Battle
    -- Gargon Silessa have coordinates -- of rooms nobody walks into: the way in is a broken
    -- mirror. With a way in among the mount's objects, the chests are not put on the map.
    local entrada = false
    for _, id in ipairs(type(m.object) == "table" and m.object or {}) do
        local o = type(T.object) == "table" and T.object[id]
        if type(o) == "table" and o.kind == "portal" then entrada = true end
    end
    for _, id in ipairs(type(m.object) == "table" and m.object or {}) do
        local o = type(T.object) == "table" and T.object[id]
        if type(o) == "table" and not (entrada and o.kind == nil) then
            -- An object is a chest unless the table says what else: a PORTAL is the way in to
            -- where the mount is, and appears at one of its places (28/09).
            local kind = type(o.kind) == "string" and o.kind or "treasure"
            local quando = type(o.when) == "table" and o.when or nil
            local mapa
            for _, p in ipairs(Pontos(o.where)) do
                local vez = quando and type(quando[p.m]) == "table" and quando[p.m][p.i] or nil
                if NaVez(vez) then
                    out.coords[#out.coords + 1] = {
                        m = p.m, x = p.x, y = p.y, n = NomeDoObjeto(id, o.name), kind = kind, objectId = id,
                        -- the first of each map: on a continent, the only one drawn
                        first = p.m ~= mapa,
                    }
                    mapa = p.m
                end
            end
        end
    end
    -- (!) WHERE A MOUNT OF PUZZLE STARTS (28/09). The user: *"ainda tem algumas montarias que
    -- são tipo com puzzles em mapas"*. A creature that is fed, talked to or followed is not
    -- killed and sells nothing: it has its own table, and is never read as a vendor. What it
    -- is comes from the table (`kind`); a record that does not say is not drawn as a guess.
    for _, id in ipairs(type(m.creature) == "table" and m.creature or {}) do
        local c = type(T.creature) == "table" and T.creature[id]
        if type(c) == "table" and type(c.kind) == "string" then
            local mapa
            for _, p in ipairs(Pontos(c.where)) do
                out.coords[#out.coords + 1] = {
                    m = p.m, x = p.x, y = p.y, n = c.name, kind = c.kind, npcId = id,
                    first = p.m ~= mapa,
                }
                mapa = p.m
            end
        end
    end
    -- (!) A DELVE IS A PLACE TOO (28/09). The mount of a nemesis is an achievement's reward
    -- and the journal names no place: the place to go is the door of the nemesis' own delve,
    -- a landmark of the game's own map (`poi`).
    for _, id in ipairs(type(m.poi) == "table" and m.poi or {}) do
        local d = type(T.poi) == "table" and T.poi[id]
        if type(d) == "table" and type(d.kind) == "string" then
            for _, p in ipairs(Pontos(d.where)) do
                if not d.live or MarcoAoVivo(p.m, id) then
                    out.coords[#out.coords + 1] = {
                        m = p.m, x = p.x, y = p.y, n = d.name, kind = d.kind, poiId = id,
                    }
                end
            end
        end
    end
    -- (!) A QUEST LISTED IS NOT A QUEST ASKED (28/09). Wowhead lists every quest that ever
    -- rewarded the item: the old epic horses, sold for gold, come with the two quests that
    -- once exchanged them. 40 mounts of the table have a vendor AND a quest, and read as a
    -- requirement the quest put "quest pending" on a mount anyone can buy. With a vendor, the
    -- quest only counts when the GAME says the mount comes from a quest.
    local QUEST = 2
    local contaMissao = #out.vendors == 0 or sourceType == QUEST
    for _, id in ipairs(contaMissao and type(m.quest) == "table" and m.quest or {}) do
        local q = type(T.quest) == "table" and T.quest[id]
        if DoMeuLado(q) then
            local pts = Pontos(q.where)
            -- `m` is where the quest is taken, for the card to name the zone.
            out.quests[#out.quests + 1] = {
                id = id, name = q.name, m = pts[1] and pts[1].m or nil,
                chain = type(q.chain) == "table" and q.chain or nil,
            }
            for _, p in ipairs(pts) do
                -- `q` is what the map reads to know the point is spent: the quest done.
                out.coords[#out.coords + 1] = {
                    m = p.m, x = p.x, y = p.y, n = q.name, kind = "quest", questId = id, q = id,
                }
            end
        end
    end
    return out
end

--------------------------------------------------------------------------------
-- THE BOSS, FROM THE GAME'S OWN ADVENTURE GUIDE
--
-- (!) 28/09. The name of the boss, the difficulties, the size of the group and the entrance on
-- the map came from MCL, read at run time, and no addon of ours reads another one.
-- `Data/MountBosses.lua` (tools/coletar_chefes.py) has the game's own ids for each mount a boss
-- drops; the NAMES are asked of the game by id, so they come in the player's language, and the
-- English ones of the table are what is left when the game does not answer.
--------------------------------------------------------------------------------
---A name the game gave: a string, not empty, not secret.
local function NomeDoJogo(f, id)
    if type(f) ~= "function" then return nil end
    local ok, nome = pcall(f, id)
    if not ok or nome == nil then return nil end
    if issecretvalue and issecretvalue(nome) then return nil end
    if type(nome) ~= "string" or nome == "" then return nil end
    return nome
end

---@return table|nil `{ name, names, instance, zone, raid, world, difficulties }`
function ns.OwnBoss(mountID)
    local b = type(ns.MountBosses) == "table" and ns.MountBosses[mountID]
    if type(b) ~= "table" or type(b.bosses) ~= "table" then return nil end
    local nomes = {}
    for _, par in ipairs(b.bosses) do
        if type(par) == "table" and type(par[1]) == "number" then
            local nome = NomeDoJogo(_G.EJ_GetEncounterInfo, par[1])
                or (type(par[2]) == "string" and par[2] ~= "" and par[2]) or nil
            if nome then nomes[#nomes + 1] = nome end
        end
    end
    if #nomes == 0 then return nil end
    local instancia = type(b.instance) == "number" and b.instance or nil
    local difs
    if type(b.difficulties) == "table" then
        difs = {}
        for _, d in ipairs(b.difficulties) do
            if type(d) == "number" then difs[#difs + 1] = d end
        end
        if #difs == 0 then difs = nil end
    end
    return {
        name = nomes[1], names = nomes,
        instance = instancia,
        zone = (instancia and NomeDoJogo(_G.EJ_GetInstanceInfo, instancia))
            or (type(b.zone) == "string" and b.zone ~= "" and b.zone) or nil,
        raid = b.raid == true, world = b.world == true,
        difficulties = difs,
    }
end

--------------------------------------------------------------------------------
-- THE CHANCE ON EACH DIFFICULTY
--------------------------------------------------------------------------------
-- (!) 28/09. A raid's chest is one object for each difficulty, all of one name, and the chance
-- is not the same in all of them: the Astral Cloud Serpent came in 0.4% of the chests of 10
-- players and in 2.9% of those of 25. The number of the list is of all of them together; this
-- is what each difficulty gave, for the card (`Data/MountChances.lua`,
-- tools/coletar_dificuldades.py). The user: *"explica também a dificuldade da raid"*.
--
-- A row with no difficulty is a chest whose difficulty could not be told: it is kept, and the
-- card says so. One row alone has nothing to be compared with, and says nothing. And a mount
-- seen fewer than ten times on a difficulty has no rate there yet: two in three hundred is
-- not 0.7%.
local SEEN_ENOUGH = 10

---@return table|nil `{ { d = difficultyID|nil, rate, count, outof }, ... }`, the best first
function ns.OwnChances(mountID)
    local t = type(ns.MountChances) == "table" and ns.MountChances[mountID]
    if type(t) ~= "table" then return nil end
    local out = {}
    for i, r in ipairs(t) do
        if type(r) == "table" and type(r.count) == "number" and type(r.outof) == "number"
            and r.count >= SEEN_ENOUGH and r.outof >= r.count then
            out[#out + 1] = {
                d = type(r.d) == "number" and r.d or nil,
                rate = r.count / r.outof, count = r.count, outof = r.outof, i = i,
            }
        end
    end
    if #out < 2 then return nil end
    table.sort(out, function(a, b)
        if a.rate ~= b.rate then return a.rate > b.rate end
        return a.i < b.i
    end)
    return out
end

--------------------------------------------------------------------------------
-- WHERE THE PRICE COMES FROM
--
-- (!) Reported on 27/09 with a screenshot, standing at Elianna (Emerald Dream): *"Montaria
-- apontando 100% mas sem a moeda para comprar"*. Garrant costs 1 Dream Infusion, the character
-- held none, and the list said 100%, "the vendor sells it to you", "Requirements -- all met".
-- The footer of the same screenshot: "without MCL". The price used to come from MCL's table and
-- from nowhere else, so without the catalogue the addon knew NO price at all -- and the vendor's
-- verdict is about requirements, not about money (the game does not tint red what you cannot
-- afford, `MerchantFrame.lua`). No price known was read as nothing to pay: the same family of
-- defect, for the seventh time, and this one reaches everybody who installs the addon alone.
--
-- Three sources, the most certain first:
--   vendor      what the vendor CHARGES, read with the vendor open (`ns.ScanMerchant`). It is the
--               game charging, so it wins. Kept for the account: a price is not per character.
--   own         our table (`Data/MountPlaces.lua`, `cost`): what each vendor charges, as
--               players' clients reported it.
--   journal     the game's own source text, which carries the price as a link:
--               `Cost: |r1|Hcurrency:2777|h|T...|t`. Always there, in every language.
--
-- Measured on 27/09 against the client's table (515 mounts with a price somewhere): the journal
-- and MCL agree on 338, the journal alone has 16, and where they differ the journal is usually
-- SHORT -- it names the first part of a price made of several (Great Red Elekk: 500 gold, and
-- MCL adds 5 Champion's Seals). So the journal comes last, and it can only ever say "at least
-- this much": a requirement, never a permission. And it can be wrong (Blessed Amani Burrower:
-- 1,600 written, 6,400 charged), which is why the vendor, once seen, replaces it.
--------------------------------------------------------------------------------

---A number as the journal writes it: `1600`, `5,000,000`, `5.000.000`. Prices are whole numbers.
local function Inteiro(s)
    local n = tonumber((tostring(s or ""):gsub("[%.,]", "")))
    return n
end

---The price the journal's source text states, in MCL's shape.
---
---The text is one block per vendor, separated by an empty line, and a mount sold by two vendors
---(one per faction) states its price twice: the first block that has a price is the price.
---A price with an icon and no link (honour, a holiday's token) names nothing the game can count,
---and is left out rather than guessed.
---@return table[]|nil `{ { type = "currency"|"item"|"gold", id = number, amount = number }, ... }`
function ns.JournalCost(sourceText)
    if type(sourceText) ~= "string" or sourceText == "" then return nil end
    if issecretvalue and issecretvalue(sourceText) then return nil end
    local NL = string.char(10)
    local texto = sourceText:gsub("|n", NL)
    texto = texto .. NL .. NL
    for bloco in texto:gmatch("(.-)" .. NL .. "%s*" .. NL) do
        local out = {}
        -- `|r<number>` then a link, then the icon -- or the icon alone, for gold.
        for numero, resto in bloco:gmatch("|r%s*(%d[%d%.,]*)%s*(|[HT][^" .. NL .. "]*)") do
            local quanto = Inteiro(numero)
            local tipo, id = resto:match("^|H(%a+):(%d+)")
            if quanto and quanto > 0 then
                if tipo == "currency" or tipo == "item" then
                    out[#out + 1] = { type = tipo, id = tonumber(id), amount = quanto }
                elseif not tipo and resto:upper():find("^|T[^|]*UI%-GOLDICON") then
                    out[#out + 1] = { type = "gold", id = 0, amount = quanto * 10000 }
                end
            end
        end
        if #out > 0 then return out end
    end
    return nil
end

---(!) WHAT OUR OWN TABLE SAYS THE VENDORS CHARGE (28/09), as a list of prices in the shape the
---rest reads. One price when every vendor of the player's side charges the same; several when
---they charge different things (one takes a currency, another takes another).
---@return table[]|nil `{ { { type, id, amount }, ... }, ... }`
function ns.OwnCost(mountID)
    local T = ns.MountPlaces
    local m = type(T) == "table" and type(T.mount) == "table" and T.mount[mountID]
    if type(m) ~= "table" or type(m.cost) ~= "table" then return nil end
    local out = {}
    for _, p in ipairs(m.cost) do
        if type(p) == "table" then
            -- A price belongs to who charges it: the other faction's vendor does not count.
            local meu = false
            for _, id in ipairs(type(p.npc) == "table" and p.npc or {}) do
                if type(T.npc) == "table" and DoMeuLado(T.npc[id], mountID) then meu = true end
            end
            if meu then
                local lista = {}
                if type(p.gold) == "number" and p.gold > 0 then
                    lista[#lista + 1] = { type = "gold", id = 0, amount = p.gold }
                end
                for _, tipo in ipairs({ "currency", "item" }) do
                    local ids = {}
                    for id, n in pairs(type(p[tipo]) == "table" and p[tipo] or {}) do
                        if type(id) == "number" and type(n) == "number" and n > 0 then ids[#ids + 1] = id end
                    end
                    table.sort(ids)
                    for _, id in ipairs(ids) do
                        lista[#lista + 1] = { type = tipo, id = id, amount = p[tipo][id] }
                    end
                end
                if #lista > 0 then out[#out + 1] = lista end
            end
        end
    end
    if #out == 0 then return nil end
    return out
end

---What the vendor charged for this mount the last time one was open, in MCL's shape.
---
---(!) THE PRICE THIS CHARACTER SAW COMES FIRST (01/10). The price was kept once for the whole
---account, and a vendor does not charge everyone the same: gold drops up to 20% with the
---reputation. The last character to open the vendor decided the number every other one read.
---Now each character keeps what it was charged (`vendorSeen[character][mount].cost`), and the
---account's is what answers for a character that never stood at that vendor.
local function VendorCost(mountID)
    if not (mountID and ns.db) then return nil end
    local name = UnitName and UnitName("player")
    local chave = name and (name .. "-" .. (GetRealmName and GetRealmName() or ""))
    local meu = chave and type(ns.db.vendorSeen) == "table" and type(ns.db.vendorSeen[chave]) == "table"
        and ns.db.vendorSeen[chave][mountID]
    if type(meu) == "table" and type(meu.cost) == "table" and #meu.cost > 0 then return meu.cost end
    local v = type(ns.db.vendorCost) == "table" and ns.db.vendorCost[mountID]
    if type(v) == "table" and #v > 0 then return v end
    return nil
end

---What it costs, and whether you can pay -- as TWO separate facts.
---
---(!) They used to be one string, and the player called it out: *"a linha onde aparece valores
---mistura o valor que tenho em bag com o valor da montaria, muito confuso"*. He was right --
---`"1234g 56s 78c de 3000g"` asks the reader to parse two numbers and work out which is which,
---every row, when what he wants first is one of them: **the price**.
---
---So `price` is the number the row shows, and `gap` is a short clause that only exists when
---something is missing. What you already hold is not printed unless it matters.
local function CostOf(list)
    -- Gold apart from the rest (currencies, items): the percentage holds gold back until every
    -- other requirement is met (Score.lua, `Price`).
    local precos, faltas, worst = {}, {}, 1
    local goldPct, otherPct
    -- What each part of the price is, for the card's "where it comes from" (27/09): the name and
    -- what the GAME says about it. A currency carries its description; an item's is its flavour
    -- text, read from its tooltip when the card is drawn (it may not be in the cache yet).
    local partes = {}
    for _, c in ipairs(list) do
        local have, need, preco, falta = nil, c.amount, nil, nil
        local parte

        if c.type == "gold" then
            have = GetMoney and GetMoney() or 0
            -- `GetCoinTextureString` é compacto e já traz o ícone da moeda: "3000g". O
            -- `GetMoneyString` escreve por extenso e ocupa a linha inteira.
            -- From `C_CurrencyInfo` (28/09): the global of the same name only exists while the
            -- game loads its deprecated shims (`Blizzard_DeprecatedCurrencyScript`).
            local moedas = C_CurrencyInfo and C_CurrencyInfo.GetCoinTextureString
            preco = moedas and moedas(need) or tostring(need)
            if have < need then
                falta = moedas and moedas(need - have) or tostring(need - have)
            end
        elseif c.type == "currency" and C_CurrencyInfo and C_CurrencyInfo.GetCurrencyInfo then
            local ok, info = pcall(C_CurrencyInfo.GetCurrencyInfo, c.id)
            if ok and info then
                have = info.quantity or 0
                preco = string.format("%s %s", BreakUpLargeNumbers(need), info.name or "?")
                if have < need then
                    falta = string.format("%s %s", BreakUpLargeNumbers(need - have), info.name or "?")
                end
                parte = { type = "currency", id = c.id, name = info.name, icon = info.iconFileID,
                          about = info.description }
            end
        elseif c.type == "item" and C_Item and C_Item.GetItemCount then
            local ok, n = pcall(C_Item.GetItemCount, c.id, true)
            if ok then
                have = n or 0
                local iname = (C_Item.GetItemNameByID and C_Item.GetItemNameByID(c.id))
                    or string.format(L["item %d"], c.id)
                preco = string.format("%d x %s", need, iname)
                if have < need then
                    falta = string.format("%d x %s", need - have, iname)
                end
                parte = { type = "item", id = c.id, name = iname }
            end
        end
        if parte then
            parte.have, parte.need = have, need
            partes[#partes + 1] = parte
        end

        if have and need and need > 0 and preco then
            local pct = math.min(1, have / need)
            if pct < worst then worst = pct end
            if c.type == "gold" then
                goldPct = math.min(goldPct or 1, pct)
            else
                otherPct = math.min(otherPct or 1, pct)
            end
            precos[#precos + 1] = preco
            if falta then faltas[#faltas + 1] = falta end
        end
    end

    if #precos == 0 then return nil end

    local preco = table.concat(precos, " + ")
    local falta = #faltas > 0 and table.concat(faltas, " + ") or nil
    return {
        pct = worst,
        goldPct = goldPct,
        otherPct = otherPct,
        price = preco,
        gap = falta,
        parts = partes,
        -- A frase completa, para a ficha: o preço primeiro, a falta depois, e nunca os dois
        -- números grudados um no outro.
        label = falta and string.format(L["%s  ·  %s missing"], preco, falta)
            or string.format(L["%s  ·  you have it"], preco),
    }
end

---The price from the most certain source that has one (see "WHERE THE PRICE COMES FROM").
---A source whose entries cannot be counted gives way to the next.
local function CostProgress(mountID, sourceText)
    local fontes = {}
    local visto = VendorCost(mountID)
    if visto then fontes[#fontes + 1] = { "vendor", visto } end
    -- Ours: with several prices, the one the player is FARTHEST from (below). Which vendor he
    -- will go to nobody knows, and not knowing pushes down.
    local nossos = ns.OwnCost(mountID)
    if nossos then fontes[#fontes + 1] = { "own", nossos, several = true } end
    local ok, doDiario = pcall(ns.JournalCost, sourceText)
    if ok and doDiario then fontes[#fontes + 1] = { "journal", doDiario } end

    for _, f in ipairs(fontes) do
        local okC, custo
        if f.several then
            for _, lista in ipairs(f[2]) do
                local okL, c = pcall(CostOf, lista)
                if okL and c and (not custo or c.pct < custo.pct) then okC, custo = true, c end
            end
            if custo then custo.alternatives = #f[2] > 1 and #f[2] or nil end
        else
            okC, custo = pcall(CostOf, f[2])
        end
        if okC and custo then
            custo.from = f[1]
            -- The vendor charged something the addon could not read: what is here is part of it.
            custo.partial = f[1] == "vendor" and f[2].partial or nil
            return custo
        end
    end
    return nil
end

--------------------------------------------------------------------------------
-- Missão
--------------------------------------------------------------------------------
---A missão que entrega a montaria já foi feita?
---
---(!) O CATÁLOGO TINHA ISTO E EU NÃO LIA. `MCL_GUIDE_QUEST_DATA` guarda missão, id, quem entrega
---e onde, para 83 montarias — e o addon ignorava a tabela inteira. Pergunta do usuário:
---*"Grande Grifo, se falta missão, não dá para ir pegar, correto?"*. Correto, e até agora a tela
---não dizia nem que havia missão.
---
---⚠️ O QUE ESTA FUNÇÃO **NÃO** RESPONDE, e o usuário perguntou direto: se a missão está
---**disponível**. O jogo não expõe o grafo de pré-requisito de missão para addon — dá para saber
---se você CONCLUIU uma missão, nunca se você PODE pegá-la. (Conferência: dos addons instalados,
---67 usam `IsQuestFlaggedCompleted` e **nenhum** usa API de pré-requisito, porque não existe; os
---que mostram cadeia de missão, como o Zygor, embarcam base própria.)
---
---Então aqui se diz o que dá para provar: feita, ou não feita. "Não feita" já responde a pergunta
---que importa — tem coisa no caminho — sem fingir saber quantos passos faltam.
local function QuestProgress(nossas)
    -- The quests of `Data/MountPlaces.lua`. A mount with a quest for each faction has one left
    -- here (`ns.OwnPlaces` drops the other side's); with more than one, the one already done
    -- counts, and otherwise the first.
    if type(nossas) ~= "table" or #nossas == 0 then return nil end
    local q = { questId = nossas[1].id, quest = nossas[1].name, m = nossas[1].m, chain = nossas[1].chain }
    for _, n in ipairs(nossas) do
        local ok, feita = pcall(C_QuestLog.IsQuestFlaggedCompleted, n.id)
        if ok and feita then q = { questId = n.id, quest = n.name, m = n.m, chain = n.chain }; break end
    end

    local questID = q.questId
    -- O nome vem do jogo quando ele já carregou a missão; senão fica o da tabela, que é o
    -- nome em inglês. Pedir o carregamento aqui faz o próximo desenho já achar traduzido.
    local titulo = q.quest
    if questID and C_QuestLog then
        if C_QuestLog.RequestLoadQuestByID then pcall(C_QuestLog.RequestLoadQuestByID, questID) end
        if C_QuestLog.GetTitleForQuestID then
            local ok, t = pcall(C_QuestLog.GetTitleForQuestID, questID)
            if ok and type(t) == "string" and t ~= "" then titulo = t end
        end
    end

    local feita, naConta = false, false
    if questID and C_QuestLog then
        if C_QuestLog.IsQuestFlaggedCompleted then
            local ok, v = pcall(C_QuestLog.IsQuestFlaggedCompleted, questID)
            feita = ok and v or false
        end
        if C_QuestLog.IsQuestFlaggedCompletedOnAccount then
            local ok, v = pcall(C_QuestLog.IsQuestFlaggedCompletedOnAccount, questID)
            naConta = ok and v or false
        end
    end

    -- WHERE it is taken: the zone, by the name the game gives the map.
    local onde
    if q.m and C_Map and C_Map.GetMapInfo then
        local ok, info = pcall(C_Map.GetMapInfo, q.m)
        if ok and type(info) == "table" and type(info.name) == "string" and info.name ~= "" then
            onde = info.name
        end
    end

    if feita then
        return {
            kind = "quest", pct = 1, questID = questID, titulo = titulo, onde = onde,
            label = string.format(L['Quest "%s": completed'], titulo or "?"),
        }
    end

    -- FEITA EM OUTRO PERSONAGEM é informação, e não requisito cumprido: a montaria é deste.
    local extra = naConta and L["  —  already done on another character"] or ""

    -- (!) THE CHAIN (28/09). The user, with the Ochre Dreamtalon at 0%: *"Montaria de missão com 0
    -- porcento, verifica se esta correto isso"*. The quest of the mount is the last of five, and
    -- "the last one is not done" is true from the first day to the twenty-third. The game tells
    -- whether each quest is done: the number is how far along the chain the character is, and
    -- the line says which quest comes next. A chain is known for the quests of
    -- `Data/MountPlaces.lua` that have one; for the others nothing changes -- not knowing the
    -- chain is not having walked it.
    local cadeia = type(q.chain) == "table" and #q.chain >= 2 and q.chain or nil
    if cadeia and C_QuestLog and C_QuestLog.IsQuestFlaggedCompleted then
        -- The furthest one done: a step the game skipped for this character, or the other
        -- faction's, is behind it all the same.
        local feitas = 0
        for i, passo in ipairs(cadeia) do
            local ok, v = pcall(C_QuestLog.IsQuestFlaggedCompleted, passo)
            if ok and v then feitas = i end
        end
        -- (The last of the chain is the mount's quest, and with that one done the answer was
        -- given above: here `feitas` is at most one short of the chain.)
        local proxima = cadeia[feitas + 1]
        local nome
        if proxima and proxima ~= questID and C_QuestLog.GetTitleForQuestID then
            if C_QuestLog.RequestLoadQuestByID then pcall(C_QuestLog.RequestLoadQuestByID, proxima) end
            local ok, t = pcall(C_QuestLog.GetTitleForQuestID, proxima)
            if ok and type(t) == "string" and t ~= "" then nome = t end
        end
        return {
            kind = "quest", pct = feitas / #cadeia, questID = questID, titulo = titulo, onde = onde,
            naConta = naConta, steps = #cadeia, done = feitas, nextQuest = proxima,
            label = string.format(L['Quest "%s": %d of the %d quests that lead to it done'],
                titulo or "?", feitas, #cadeia)
                .. (nome and string.format(L['  ·  next: "%s"'], nome) or "")
                .. (onde and ("  ·  " .. onde) or "") .. extra,
        }
    end

    return {
        kind = "quest", pct = 0, questID = questID, titulo = titulo, onde = onde,
        naConta = naConta,
        label = string.format(L['Quest "%s": not completed%s%s'], titulo or "?",
            onde and ("  ·  " .. onde) or "", extra),
    }
end

--------------------------------------------------------------------------------
-- Busca em texto livre
--------------------------------------------------------------------------------
-- (!) A BUSCA NÃO PODE SER SÓ PELO NOME, e o exemplo do usuário prova: *"não achei a montaria
-- que dropa no Fyrakk"*. A montaria do Fyrakk se chama **Anu'relos, Flame's Guidance** — a
-- palavra "Fyrakk" não aparece no nome dela em lugar nenhum. Ela aparece no texto de origem do
-- jogo e no nome do chefe que o catálogo guarda.
--
-- Então o que se pesquisa é tudo que o addon sabe sobre a montaria: nome, o texto da Blizzard,
-- o chefe, o vendedor, a zona e a facção. Quem procura "fyrakk", "aberrus" ou "vendedor" acha.

-- Acentos fora, para "fenix" achar "Fênix". São os pares do português, em UTF-8: cada acentuado
-- ocupa dois bytes, então `gsub` byte a byte não serve e a substituição é por par.
local ACENTOS = {
    ["á"]="a", ["à"]="a", ["â"]="a", ["ã"]="a", ["ä"]="a",
    ["é"]="e", ["è"]="e", ["ê"]="e", ["ë"]="e",
    ["í"]="i", ["ì"]="i", ["î"]="i", ["ï"]="i",
    ["ó"]="o", ["ò"]="o", ["ô"]="o", ["õ"]="o", ["ö"]="o",
    ["ú"]="u", ["ù"]="u", ["û"]="u", ["ü"]="u",
    ["ç"]="c", ["ñ"]="n",
}

function ns.Fold(texto)
    if type(texto) ~= "string" then return "" end
    texto = texto:lower()
    for acentuado, simples in pairs(ACENTOS) do
        texto = texto:gsub(acentuado, simples)
    end
    return texto
end

---Tudo que dá para pesquisar numa montaria, junto e sem acento.
local function Haystack(e)
    -- (!) ONE MISSING PIECE USED TO END THE LIST (found on 28/09). The pieces were a table
    -- walked with `ipairs`, which stops at the first nil: a mount with no boss lost its
    -- faction, its vendor, its source and its expansion from the search. Each piece is looked
    -- at on its own now.
    local limpo = {}
    local function Mais(...)
        for i = 1, select("#", ...) do
            local parte = select(i, ...)
            if type(parte) == "string" and parte ~= "" then limpo[#limpo + 1] = parte end
        end
    end
    Mais(e.name, e.sourceText, e.description, e.bossName, e.instanceName, e.dropName,
        e.rep and e.rep.factionName,
        ns.SOURCE_NAMES[e.sourceType],
        -- A expansão entra na busca: quem digita "midnight" ou "legion" acha por ela.
        e.expansionName)
    for _, nome in ipairs(e.bossNames or {}) do Mais(nome) end
    for _, v in ipairs(e.vendors or {}) do Mais(v.npc) end
    -- A zona de cada lugar também entra: quem lembra da zona e não do nome do vendedor acha.
    local function Zona(m)
        if not (m and C_Map and C_Map.GetMapInfo) then return end
        local ok, info = pcall(C_Map.GetMapInfo, m)
        if ok and type(info) == "table" then Mais(info.name) end
    end
    for _, v in ipairs(e.vendors or {}) do Zona(v.m) end
    for _, wp in ipairs(e.coords or {}) do
        Zona(wp.m)
        Mais(wp.n)
    end
    return ns.Fold(table.concat(limpo, " "))
end

ns.Haystack = Haystack

--------------------------------------------------------------------------------
-- Monta a lista
--------------------------------------------------------------------------------

-- Só interessa o que o personagem pode de fato buscar.
local function Playable(isFactionSpecific, faction, shouldHideOnChar)
    if shouldHideOnChar then return false end
    if isFactionSpecific and faction ~= nil then
        local mine = UnitFactionGroup("player")
        local want = (faction == 0) and "Horde" or "Alliance"
        if mine and mine ~= want then return false end
    end
    return true
end

---@param onlyID number|nil build the entry of THIS mount alone, collected or not, usable by this
---character or not: the card of the Collection tab (02/10) describes any mount of the game.
function ns.BuildList(onlyID)
    local out = {}
    local ids = onlyID and { onlyID } or C_MountJournal.GetMountIDs()
    if not ids then return out end

    for _, mountID in ipairs(ids) do
        -- A sliced build stops here when its share of the frame is spent (Score.lua).
        if ns.buildYield then ns.buildYield() end
        local name, spellID, icon, _, _, sourceType, _, isFactionSpecific,
              faction, shouldHideOnChar, isCollected = C_MountJournal.GetMountInfoByID(mountID)

        if name and (not isCollected or onlyID) then
            local playable = Playable(isFactionSpecific, faction, shouldHideOnChar)
            if playable or not ns.db.hideUnavailable or onlyID then
                local e = {
                    mountID = mountID,
                    collected = isCollected and true or nil,
                    spellID = spellID,
                    name = name,
                    icon = icon,
                    sourceType = sourceType or 0,
                    isFactionSpecific = isFactionSpecific,
                    faction = faction,
                    playable = playable,
                    -- "Horde" / "Alliance" / nil. Vira rótulo e vira filtro: até aqui a facção
                    -- só servia para ESCONDER a montaria, e esconder não é informar.
                    factionOnly = isFactionSpecific and faction ~= nil
                        and ((faction == 0) and "Horde" or "Alliance") or nil,
                }

                -- O texto que a Blizzard escreve explicando de onde a montaria vem,
                -- já no idioma do cliente. É o melhor "como pega" que existe de graça.
                local _, description, source = C_MountJournal.GetMountInfoExtraByID(mountID)
                e.description = description
                e.sourceText = source

                e.itemID = ns.VerifiedMountItem(mountID)
                -- LEFT THE GAME (28/09): the game itself marks them -- the journal's source text
                -- of such a mount is the single word "Legacy". `Data/MountGone.lua` has the ids,
                -- from the game's own table (tools/coletar_legado.py).
                e.unobtainable = type(ns.MountGone) == "table" and ns.MountGone[mountID] == true

                -- THE REPUTATION (25/09): the vendor's condition and what renown gives, from
                -- `Data/MountReputation.lua`. The Gilded Prowler asks for Exalted with The
                -- Ascended, and the item's own data does not say so.
                if type(ns.MountReputation) == "table" and type(ns.MountReputation[mountID]) == "table" then
                    local r = ns.MountReputation[mountID]
                    e.rep = ReputationProgress(r)
                    e.isRenown = r.renown and true or false
                end

                -- THE BOSS, from the game's Adventure Guide (28/09): the name is the game's, in
                -- the player's language.
                local chefe = ns.OwnBoss(mountID)
                if type(chefe) == "table" then
                    e.bossName, e.bossNames = chefe.name, chefe.names
                    e.instanceID, e.instanceName = chefe.instance, chefe.zone
                    e.worldBoss = chefe.world
                    -- What the tags and the map ask: a raid, a dungeon, or neither.
                    e.groupSize = (chefe.raid and 10) or (not chefe.world and 5) or nil
                    e.difficulties = chefe.difficulties
                    e.bossFrom = "own"
                end
                local okD, porDificuldade = pcall(ns.OwnChances, mountID)
                e.chanceBy = okD and porDificuldade or nil

                -- WHERE IT IS GOT (28/09): vendors, chests and quests, from
                -- `Data/MountPlaces.lua`.
                local okP, nosso = pcall(ns.OwnPlaces, mountID, e.sourceType)
                if okP and type(nosso) == "table" then
                    if #nosso.vendors > 0 then
                        e.vendors = nosso.vendors
                        e.vendor = e.vendors[1]
                        for _, v in ipairs(e.vendors) do
                            if v.m and v.x then e.vendor = v; break end
                        end
                        e.vendorVago = not (e.vendor.m and e.vendor.x)
                        e.isVendorMount = true
                        e.placesFrom = "own"
                    end
                    if #nosso.coords > 0 then
                        e.coords = nosso.coords
                        e.placesFrom = "own"
                    end
                    if #nosso.quests > 0 then
                        local okQ, missao = pcall(QuestProgress, nosso.quests)
                        if okQ and missao then e.quest = missao end
                    end
                    e.box = nosso.box
                end

                -- (!) A GUILD VENDOR IS A REQUIREMENT NOT MET, and not "unknown". Every mount of a
                -- guild vendor asks for Exalted with the guild, and a good part of them for an
                -- achievement OF THE GUILD too (the Dark Phoenix: Guild Glory of the Cataclysm
                -- Raider). Neither can be measured here -- the achievement of the guild is not
                -- linked to the mount anywhere, and the reputation depends on the guild of the
                -- day -- so it goes in as access at 0%: it cannot be said to be met, so it is not.
                -- AFTER the reputation is read, never before: the reading would wipe it.
                e.vendorGuilda = false
                for _, v in ipairs(e.vendors or {}) do
                    if v.guild then e.vendorGuilda = true end
                end
                if e.vendorGuilda and not e.rep then
                    e.rep = {
                        kind = "guild", pct = 0, unreadable = true,
                        label = L["Guild vendor: asks for Exalted with the guild and, in most cases, an achievement OF THE GUILD"],
                    }
                end

                e.cost = CostProgress(mountID, source)

                -- (!) O QUE O PRÓPRIO JOGO DIZ QUE FALTA. É a fonte que fecha o buraco que a
                -- Fênix Negra abriu: o catálogo não sabe da conquista de guilda, e o tooltip do
                -- item sabe — em português, e certo depois do próximo patch também.
                -- A conquista que o JOGO diz que dá esta montaria. Fecha o buraco das 126
                -- marcadas "SPECIAL" no catálogo, que não tinham requisito nenhum.
                if ns.Achievements then
                    e.achievementReward = ns.Achievements.Gate(e.name, mountID)
                end

                -- The chance (see "THE DROP CHANCE, FROM OUR OWN TABLE").
                local okCh, nossa = pcall(ns.OwnChance, e.itemID)
                if okCh and nossa then
                    if nossa.sure then
                        e.chance, e.sureDrop = nil, nossa
                    else
                        e.chance, e.chanceRough = nossa.n, nossa.rough
                    end
                    e.chanceFrom = "own"
                    e.dropNpc, e.dropName, e.dropCreatures = nossa.npc, nossa.name, nossa.creatures
                elseif e.box and tonumber(e.box.count) and tonumber(e.box.outof)
                    and e.box.count > 0 and e.box.outof > 0 then
                    -- THE CONTAINER (28/09): a chest, a bag, a reputation's trove. The same two
                    -- rules of the creatures: nearly every time is not a chance, and a small
                    -- sample is rough.
                    local taxa = e.box.count / e.box.outof
                    local nome = e.box.name
                    if e.box.kind == "object" then
                        nome = NomeDoObjeto(e.box.id, nome)
                    elseif C_Item and C_Item.GetItemNameByID then
                        local okN, n = pcall(C_Item.GetItemNameByID, e.box.id)
                        if okN and type(n) == "string" and n ~= "" then nome = n end
                    end
                    if taxa >= SURE_DROP then
                        e.chance, e.sureDrop = nil, { name = nome, box = true }
                    else
                        e.chance, e.chanceRough = 1 / taxa, e.box.count < ENOUGH_DROPS
                    end
                    e.chanceFrom = "own"
                    e.dropName = nome
                    -- (!) A BAG OR A TROVE IS NOT AN ATTEMPT YOU MAKE WHEN YOU WANT. A kill is;
                    -- a chest standing in the world is. How a bag is earned -- a weekly quest,
                    -- a reputation filled again and again -- is not in this table, and a 25%
                    -- trove that takes weeks to come is no short farm (Score.lua).
                    e.chanceIndirect = e.box.kind == "item"
                end
                -- (!) READ ONLY WHAT ARRIVED. An item out of the cache answers with an empty
                -- tooltip, and empty is not "no requirement". Until it loads, the mount cannot be
                -- confirmed (Score.lua), and the validation (Core.lua) waits for it.
                e.tooltipState = e.itemID and ns.Tooltip and ns.Tooltip.State(e.itemID) or nil
                if e.tooltipState == "ok" then
                    -- When another character holds the reputation, THIS one's red "Requires
                    -- <faction> - Exalted" is not what stands in the way.
                    --
                    -- (!) THE SAME REPUTATION IS NOT COUNTED TWICE (01/10, the goats of Gina
                    -- Mudclaw). A character Revered with The Tillers, 33,646 of 42,000, read
                    -- "0% - Requires The Tillers - Exalted - and 1 more requirement": the red
                    -- line is worth 0 or 1, so it beat the measured 80%, and it added a
                    -- requirement that is the same one. While the table's reputation is
                    -- measured and NOT met, the item's line that names that faction says
                    -- nothing new and steps aside. Met by the table and red in the game, the
                    -- line stays: the tooltip is still the negative signal.
                    --
                    -- A faction this character never met has no name from the game (the API
                    -- answers nothing), so there the line is known by its FORMAT ("Requires %s
                    -- - %s"). That is safe on our own data: of the 110 mounts whose item has
                    -- such a line, all 110 name the faction of the table
                    -- (`tools/auditar_reputacao.py`).
                    -- (!) ONE OF A PAIR (05/10): the item read may be the OTHER side's (the
                    -- talbuk's names the Kurenai to a character of the Horde), and that line is
                    -- no requirement of this character at all. The reputation line of such an
                    -- item steps aside whatever it names; the table measures the right one.
                    local aside
                    if e.rep and e.rep.paired then
                        aside = { e.rep.factionName }
                    elseif e.rep and e.rep.char then
                        aside = { e.rep.factionName }
                    elseif e.rep and e.rep.pct and e.rep.pct < 1
                        and type(e.rep.factionName) == "string" and e.rep.factionName ~= "" then
                        aside = { e.rep.factionName, onlyNamed = not e.rep.unreadable }
                    end
                    e.tooltipGate = ns.Tooltip.Gate(e.itemID, aside)
                end
                -- What a vendor told THIS character, when it stood in front of one.
                e.vendorCheck = ns.VendorVerdict(mountID)
                -- Montado uma vez por varredura, e não a cada tecla digitada.
                e.expansion, e.expansionName = ns.Expansion and ns.Expansion.Of(mountID)
                e.busca = Haystack(e)

                out[#out + 1] = e
            end
        end
    end

    return out
end

---The item that teaches this mount, from `Data/MountItems.lua` -- only when the game agrees.
-- mountID -> item, or false: an item never changes mount within a session. Kept for the TABLE it
-- was read from: another table is another answer.
local conferido, deQual = {}, nil
function ns.VerifiedMountItem(mountID)
    if deQual ~= ns.MountItems then conferido, deQual = {}, ns.MountItems end
    if conferido[mountID] ~= nil then return conferido[mountID] or nil end
    local item = ns.MountItems and ns.MountItems[mountID]
    if not (item and C_MountJournal and C_MountJournal.GetMountFromItem) then return nil end
    local ok, m = pcall(C_MountJournal.GetMountFromItem, item)
    conferido[mountID] = (ok and m == mountID) and item or false
    return conferido[mountID] or nil
end

--------------------------------------------------------------------------------
-- THE VENDOR'S OWN VERDICT
--
-- (!) Reported on 23/09 with a screenshot, standing at Trader Araanda (Lunarfall): *"tem montaria
-- que posso pegar, mas no addon não mostra"*. Rocktusk Battleboar, 10,000 gold, the player
-- holding 19,334. The catalogue knows only the price, so the mount went to "Asks for more than
-- the price" -- the band that sits at the END of the list since the Black Phoenix (price known,
-- guild achievement missing, shown as "just go get it"). Right for the Phoenix, wrong here: for
-- the boar, the price IS the whole story, and nothing in the data could say so.
--
-- The game can. With the vendor open, `C_MerchantFrame.GetItemInfo` answers `isPurchasable`
-- and `isUsable` for every item, and Blizzard tints an item red exactly when either is false
-- (`MerchantFrame.lua:362`, 12.1.0). The screenshot shows it is about REQUIREMENTS, not money:
-- a 500-gold item is red with 19k in the bag, and the 20k Witherhide Cliffstomper is NOT red
-- although the player cannot afford it.
--
-- This is not "no data, so it is fine" -- the family of defect this addon keeps fighting. It is
-- the game itself saying "you may buy this". It is recorded per character (the verdict belongs
-- to who stood at the vendor), with the day, and read as an ACCESS requirement: met, or not.
--------------------------------------------------------------------------------
local function CharKey()
    local name = UnitName and UnitName("player")
    if not name then return nil end
    return name .. "-" .. (GetRealmName and GetRealmName() or "")
end

---What the game paints red on an item's tooltip for this character, as one string: "" when
---nothing is red, nil when the tooltip has not arrived (then nothing can be said).
local function RedLines(itemID)
    if not (ns.Tooltip and ns.Tooltip.State and ns.Tooltip.Gate) or type(itemID) ~= "number" then return nil end
    if ns.Tooltip.State(itemID) ~= "ok" then return nil end
    local g = ns.Tooltip.Gate(itemID)
    return g and g.label or ""
end

---What the vendor said to THIS character about this mount, as an access requirement.
---
---(!) A "NO" IS A PHOTOGRAPH, AND IT IS LOOKED AT AGAIN EVERY TIME THE LIST IS BUILT (01/10).
---The user: *"tu vai criar uma forma que sempre que o usuário logar, ele vai reler, validar e
---revisar tudo?"*. Everything else the list reads comes live from the game; the vendor's
---verdict is the one judgement that is SAVED, and a refusal stayed for ever: refused at Revered,
---the mount still read "the vendor does not sell it to you yet" at Exalted, until the player
---walked back to the vendor. So the refusal is kept with what the item's tooltip painted red
---that day; when the red lines are other ones now (the requirement was met, or a new one
---appeared), the refusal is of another situation and no longer counts -- the mount goes back to
---what the game says today. A refusal the tooltip never explained (a guild vendor) has nothing
---to compare and stays, with its date.
---@return table|nil `{ pct = 1|0, label }`, nil when this character never saw it at a vendor
function ns.VendorVerdict(mountID)
    local chave = CharKey()
    local porChar = chave and ns.db and ns.db.vendorSeen and ns.db.vendorSeen[chave]
    local v = porChar and porChar[mountID]
    if not v then return nil end
    if not v.ok and v.sig ~= nil then
        local agora = RedLines(v.item)
        if agora ~= nil and agora ~= v.sig then return nil end
    end
    local quando = date and v.t and date(L["%m/%d"], v.t) or "?"
    if v.ok then
        return { pct = 1, label = string.format(L["the vendor sells it to you (seen %s)"], quando) }
    end
    return { pct = 0, label = string.format(L["the vendor does not sell it to you yet (seen %s)"], quando) }
end

---What the vendor charges for the item at `index`, in MCL's shape: gold from `price` (copper),
---the rest from the extended cost (`GetMerchantItemCostItem`, the call Blizzard's own frame makes
---to draw the price, `MerchantFrame.lua:479` in 12.1.0). `partial` when a part could not be read.
---@return table|nil
local function MerchantCost(index, info)
    local out = {}
    local preco = tonumber(info.price) or 0
    if preco > 0 then out[#out + 1] = { type = "gold", id = 0, amount = preco } end
    if info.hasExtendedCost and GetMerchantItemCostInfo and GetMerchantItemCostItem then
        local okN, n = pcall(GetMerchantItemCostInfo, index)
        for j = 1, math.min(okN and tonumber(n) or 0, MAX_ITEM_COST or 3) do
            local ok, textura, quanto, link = pcall(GetMerchantItemCostItem, index, j)
            if not ok then
                out.partial = true
            elseif textura then
                local tipo, id
                if type(link) == "string" and not (issecretvalue and issecretvalue(link)) then
                    tipo, id = link:match("|H(%a+):(%d+)")
                end
                quanto = tonumber(quanto)
                if (tipo == "currency" or tipo == "item") and quanto and quanto > 0 then
                    out[#out + 1] = { type = tipo, id = tonumber(id), amount = quanto }
                else
                    out.partial = true
                end
            end
        end
    end
    if #out == 0 and not out.partial then return nil end
    out.t = time and time() or 0
    return out
end

---Reads the open vendor. Called on MERCHANT_SHOW and MERCHANT_UPDATE.
---@return boolean changed whether any verdict is new or different
function ns.ScanMerchant()
    if not (GetMerchantNumItems and GetMerchantItemID and C_MerchantFrame
        and C_MerchantFrame.GetItemInfo and C_MountJournal and C_MountJournal.GetMountFromItem) then
        return false
    end
    local chave = CharKey()
    if not (chave and ns.db) then return false end
    ns.db.vendorSeen = ns.db.vendorSeen or {}
    ns.db.vendorSeen[chave] = ns.db.vendorSeen[chave] or {}
    local reg = ns.db.vendorSeen[chave]

    local mudou = false
    local okN, n = pcall(GetMerchantNumItems)
    for i = 1, (okN and n or 0) do
        local okI, itemID = pcall(GetMerchantItemID, i)
        local okM, mountID = pcall(C_MountJournal.GetMountFromItem, okI and itemID or 0)
        if okM and type(mountID) == "number" then
            local okInfo, info = pcall(C_MerchantFrame.GetItemInfo, i)
            if okInfo and type(info) == "table" then
                -- The same test Blizzard uses to tint the item red.
                local ok = info.isPurchasable and info.isUsable and true or false
                local antes = reg[mountID]
                if not antes or antes.ok ~= ok then mudou = true end
                -- With the item and what its tooltip painted red at this moment: what a
                -- refusal is compared with later (`ns.VendorVerdict`).
                reg[mountID] = { ok = ok, t = time and time() or 0, item = itemID, sig = RedLines(itemID) }
                -- And what it CHARGES: the verdict above is about requirements, not money.
                local okC, custo = pcall(MerchantCost, i, info)
                local escrito = ""
                if okC and custo then
                    ns.db.vendorCost = ns.db.vendorCost or {}
                    local era = ns.db.vendorCost[mountID]
                    if type(era) ~= "table" or #era ~= #custo then mudou = true end
                    for j, c in ipairs(custo) do
                        escrito = escrito .. (j > 1 and " + " or "") .. c.amount .. " " .. c.type .. ":" .. c.id
                        local a = type(era) == "table" and era[j]
                        if not a or a.type ~= c.type or a.id ~= c.id or a.amount ~= c.amount then
                            mudou = true
                        end
                    end
                    ns.db.vendorCost[mountID] = custo
                    -- And for this character, whose price it is (see `VendorCost`).
                    local meu = reg[mountID].cost
                    if type(meu) ~= "table" or #meu ~= #custo then mudou = true end
                    for j, c in ipairs(custo) do
                        local a = type(meu) == "table" and meu[j]
                        if not a or a.type ~= c.type or a.id ~= c.id or a.amount ~= c.amount then mudou = true end
                    end
                    reg[mountID].cost = custo
                end
                ns.Log.Add("merchant", {
                    mount = mountID, item = itemID, name = info.name,
                    purchasable = info.isPurchasable, usable = info.isUsable, verdict = ok,
                    cost = escrito, partial = okC and custo and custo.partial or false,
                })
            end
        end
    end
    return mudou
end
