-- RocketMount | Data/AchievementMounts.lua
-- GENERATED by tools/coletar_conquistas.py on 2026-09-25 -- do not edit by hand.
--
-- { achievement id, mount id, faction } from the game's own data tables (Achievement.
-- RewardItemID -> the item's "learn" effect -> Mount, via wago.tools), plus the reward line
-- naming the mount exactly and MCL's achievement table. It reaches what the achievement
-- window does not list: secret achievements and folded steps of a series. One achievement
-- may give two mounts, and one mount may come from two achievements (one per faction).
local ADDON, ns = ...

ns.AchievementMounts = {
    { 614, 271, "Alliance" }, -- For the Alliance! -> Black War Bear
    { 614, 272, "Alliance" }, -- For the Alliance! -> Black War Bear
    { 619, 271, "Horde" }, -- For the Horde! -> Black War Bear
    { 619, 272, "Horde" }, -- For the Horde! -> Black War Bear
    { 2136, 262 }, -- Glory of the Hero -> Red Proto-Drake
    { 2143, 268 }, -- Leading the Cavalry -> Albino Drake
    { 2144, 267 }, -- What a Long, Strange Trip It's Been -> Violet Proto-Drake
    { 2536, 291, "Alliance" }, -- Mountain o' Mounts -> Blue Dragonhawk
    { 2537, 292, "Horde" }, -- Mountain o' Mounts -> Red Dragonhawk
    { 2957, 307 }, -- Glory of the Ulduar Raider (10 player) -> Rusted Proto-Drake
    { 2958, 306 }, -- Glory of the Ulduar Raider (25 player) -> Ironbound Proto-Drake
    { 4079, 345, "Horde" }, -- A Tribute to Immortality -> Crusader's Black Warhorse
    { 4156, 344, "Alliance" }, -- A Tribute to Immortality -> Crusader's White Warhorse
    { 4602, 365 }, -- Glory of the Icecrown Raider (10 player) -> Bloodbathed Frostbrood Vanquisher
    { 4603, 364 }, -- Glory of the Icecrown Raider (25 player) -> Icebound Frostbrood Vanquisher
    { 4845, 391 }, -- Glory of the Cataclysm Hero -> Volcanic Stone Drake
    { 4853, 392 }, -- Glory of the Cataclysm Raider -> Drake of the East Wind
    { 4988, 401 }, -- Guild Glory of the Cataclysm Raider -> Dark Phoenix
    { 5828, 417 }, -- Glory of the Firelands Raider -> Corrupted Fire Hawk
    { 5858, 419 }, -- Bear-ly Made It -> Amani Battle Bear
    { 5866, 413 }, -- The Molten Front Offensive -> Flameward Hippogryph
    { 6169, 443 }, -- Glory of the Dragon Soul Raider -> Twilight Harbinger
    { 6827, 450, "Horde" }, -- Pandaren Ambassador -> Pandaren Kite
    { 6828, 516, "Alliance" }, -- Pandaren Ambassador -> Pandaren Kite
    { 6927, 472 }, -- Glory of the Pandaria Hero -> Crimson Cloud Serpent
    { 6932, 474 }, -- Glory of the Pandaria Raider -> Heavenly Crimson Cloud Serpent
    { 7860, 521, "Alliance" }, -- We're Going to Need More Saddles -> Jade Pandaren Kite
    { 7862, 521, "Horde" }, -- We're Going to Need More Saddles -> Jade Pandaren Kite
    { 8124, 530 }, -- Glory of the Thundering Raider -> Armored Skyscreamer
    { 8302, 548, "Horde" }, -- Mount Parade -> Armored Red Dragonhawk
    { 8304, 549, "Alliance" }, -- Mount Parade -> Armored Blue Dragonhawk
    { 8398, 558 }, -- Ahead of the Curve: Garrosh Hellscream (10 player) -> Kor'kron War Wolf
    { 8399, 558 }, -- Ahead of the Curve: Garrosh Hellscream (25 player) -> Kor'kron War Wolf
    { 8454, 557 }, -- Glory of the Orgrimmar Raider -> Spawn of Galakras
    { 8898, 654 }, -- Challenge Warlord: Silver -> Challenger's War Yeti
    { 8985, 607 }, -- Glory of the Draenor Raider -> Gorestrider Gronnling
    { 9239, 759 }, -- Gladiator: Warlords Season 1 -> Primal Gladiator's Felblood Gronnling
    { 9396, 623 }, -- Glory of the Draenor Hero -> Frostplains Battleboar
    { 9496, 651 }, -- Warlord's Deathwheel -> Warlord's Deathwheel
    { 9539, 621, "Alliance" }, -- Advanced Husbandry -> Armored Frostboar
    { 9540, 644, "Alliance" }, -- The Stable Master -> Armored Frostwolf
    { 9550, 606 }, -- Boldly, You Sought the Power of Ragnaros -> Core Hound
    { 9598, 416, "Alliance" }, -- Mountacular -> Felfire Hawk
    { 9599, 416, "Horde" }, -- Mountacular -> Felfire Hawk
    { 9669, 619 }, -- Guild Glory of the Draenor Raider -> Blacksteel Battleboar
    { 9705, 621, "Horde" }, -- Advanced Husbandry -> Armored Frostboar
    { 9706, 644, "Horde" }, -- The Stable Master -> Armored Frostwolf
    { 9713, 664 }, -- Awake the Drakes -> Emerald Drake
    { 9909, 679 }, -- Heirloom Hoarder -> Chauffeured Mekgineer's Chopper
    { 10018, 772 }, -- Draenor Pathfinder -> Soaring Skyterror
    { 10098, 760 }, -- Gladiator: Warlords Season 2 -> Wild Gladiator's Felblood Gronnling
    { 10110, 761 }, -- Gladiator: Warlords Season 3 -> Warmongering Gladiator's Felblood Gronnling
    { 10149, 758 }, -- Glory of the Hellfire Raider -> Infernal Direwolf
    { 10355, 477, "Horde" }, -- Lord of the Reins -> Heavenly Azure Cloud Serpent
    { 10356, 477, "Alliance" }, -- Lord of the Reins -> Heavenly Azure Cloud Serpent
    { 11011, 848 }, -- Gladiator: Legion Season 1 -> Vindictive Gladiator's Storm Dragon
    { 11013, 849 }, -- Gladiator: Legion Season 2 -> Fearless Gladiator's Storm Dragon
    { 11038, 850 }, -- Gladiator: Legion Season 3 -> Cruel Gladiator's Storm Dragon
    { 11061, 851 }, -- Gladiator: Legion Season 4 -> Ferocious Gladiator's Storm Dragon
    { 11066, 804 }, -- Underbelly Tycoon -> Ratstallion
    { 11163, 846 }, -- Glory of the Legion Hero -> Leyfeather Hippogryph
    { 11176, 845 }, -- Remember to Share -> Mechanized Lumber Extractor
    { 11180, 773 }, -- Glory of the Legion Raider -> Grove Defiler
    { 11987, 972 }, -- Glory of the Argus Raider -> Antoran Gloomhound
    { 12045, 852 }, -- Gladiator: Legion Season 5 -> Fierce Gladiator's Storm Dragon
    { 12103, 986 }, -- ...And Chew Mana Buns -> Bleakhoof Ruinstrider
    { 12167, 853 }, -- Gladiator: Legion Season 6 -> Dominant Gladiator's Storm Dragon
    { 12168, 948 }, -- Gladiator: Legion Season 7 -> Demonic Gladiator's Storm Dragon
    { 12401, 306 }, -- Glory of the Ulduar Raider -> Ironbound Proto-Drake
    { 12401, 307 }, -- Glory of the Ulduar Raider -> Rusted Proto-Drake
    { 12604, 1172, "Horde" }, -- Conqueror of Azeroth -> Conqueror's Scythemaw
    { 12605, 1172, "Alliance" }, -- Conqueror of Azeroth -> Conqueror's Scythemaw
    { 12806, 963 }, -- Glory of the Uldir Raider -> Bloodgorged Crawg
    { 12812, 933 }, -- Glory of the Wartorn Hero -> Obsidian Krolusk
    { 12866, 1190 }, -- 100 Exalted Reputations -> Pureheart Courser
    { 12895, 826 }, -- Honor Level 15 -> Prestigious Bronze Courser
    { 12903, 833 }, -- Honor Level 40 -> Prestigious Ivory Courser
    { 12906, 834 }, -- Honor Level 70 -> Prestigious Azure Courser
    { 12910, 832 }, -- Honor Level 125 -> Prestigious Forest Courser
    { 12911, 831 }, -- Honor Level 150 -> Prestigious Royal Courser
    { 12914, 836 }, -- Honor Level 250 -> Prestigious Midnight Courser
    { 12917, 1192 }, -- Honor Level 500 -> Prestigious Bloodforged Courser
    { 12931, 1167, "Horde" }, -- No Stable Big Enough -> Frostshard Infernal
    { 12932, 1167, "Alliance" }, -- No Stable Big Enough -> Frostshard Infernal
    { 12933, 1191, "Alliance" }, -- A Horde of Hoofbeats -> Frenzied Feltalon
    { 12934, 1191, "Horde" }, -- A Horde of Hoofbeats -> Frenzied Feltalon
    { 12961, 1030 }, -- Gladiator: Battle for Azeroth Season 1 -> Dread Gladiator's Proto-Drake
    { 13136, 1045, "Horde" }, -- Dread Combatant -> Vicious War Clefthoof
    { 13137, 1050, "Alliance" }, -- Dread Combatant -> Vicious War Riverbeast
    { 13212, 1031 }, -- Gladiator: Battle for Azeroth Season 2 -> Sinister Gladiator's Proto-Drake
    { 13227, 1196, "Horde" }, -- Sinister Combatant -> Vicious Black Bonesteed
    { 13228, 1195, "Alliance" }, -- Sinister Combatant -> Vicious Black Warsaber
    { 13250, 1224 }, -- Battle for Azeroth Pathfinder, Part Two -> Wonderwing 2.0
    { 13315, 1218 }, -- Glory of the Dazar'alor Raider -> Dazar'alor Windreaver
    { 13517, 1245 }, -- Two Sides to Every Tale -> Bloodflank Charger
    { 13517, 1246 }, -- Two Sides to Every Tale -> Ironclad Frostclaw
    { 13541, 1247 }, -- Mecha-Done -> Mechacycle Model W
    { 13636, 1026, "Horde" }, -- Notorious Combatant -> Vicious War Basilisk
    { 13637, 1027, "Alliance" }, -- Notorious Combatant -> Vicious War Basilisk
    { 13638, 1238 }, -- Undersea Usurper -> Snapback Scuttler
    { 13647, 1032 }, -- Gladiator: Battle for Azeroth Season 3 -> Notorious Gladiator's Proto-Drake
    { 13687, 1232 }, -- Glory of the Eternal Raider -> Azshari Bloatray
    { 13931, 1240 }, -- Memories of Fel, Frost and Fire -> Obsidian Worldbreaker
    { 13943, 1194, "Alliance" }, -- Corrupted Combatant -> Vicious White Warsaber
    { 13944, 1197, "Horde" }, -- Corrupted Combatant -> Vicious White Bonesteed
    { 13967, 1035 }, -- Gladiator: Battle for Azeroth Season 4 -> Corrupted Gladiator's Proto-Drake
    { 13994, 1282 }, -- Through the Depths of Visions -> Black Serpent of N'Zoth
    { 14145, 1326 }, -- Battle for Azeroth Keystone Master: Season Four -> Awakened Mindborer
    { 14146, 1322 }, -- Glory of the Ny'alotha Raider -> Wriggling Parasite
    { 14322, 1443 }, -- Glory of the Shadowlands Hero -> Voracious Gorger
    { 14355, 1377 }, -- Glory of the Nathria Raider -> Rampart Screecher
    { 14532, 1419 }, -- Shadowlands Keystone Master: Season One -> Sintouched Deathwalker
    { 14570, 1442 }, -- Twisting Corridors: Layer 8 -> Corridor Creeper
    { 14611, 1352, "Horde" }, -- Sinful Combatant -> Vicious War Spider
    { 14612, 1351, "Alliance" }, -- Sinful Combatant -> Vicious War Spider
    { 14689, 1363 }, -- Gladiator: Shadowlands Season 1 -> Sinful Gladiator's Soul Eater
    { 14751, 1367 }, -- The Gang's All Here -> Chosen Tauralus
    { 14752, 1371 }, -- Things To Do When You're Dead -> Armored Chosen Tauralus
    { 14966, 1459, "Horde" }, -- Unchained Combatant -> Vicious War Gorm
    { 14967, 1460, "Alliance" }, -- Unchained Combatant -> Vicious War Gorm
    { 14972, 1480 }, -- Gladiator: Shadowlands Season 2 -> Unchained Gladiator's Soul Eater
    { 15064, 1504 }, -- Breaking the Chains -> Hand of Salaranga
    { 15078, 1520 }, -- Shadowlands Keystone Master: Season Two -> Soultwisted Deathwalker
    { 15089, 1416 }, -- Flawless Master (Layer 12) -> Mawsworn Charger
    { 15130, 1417 }, -- Glory of the Dominant Raider -> Hand of Hrestimorak
    { 15178, 1446 }, -- Fake It 'Til You Make It -> Tazavesh Gearglider
    { 15254, 1566 }, -- The Jailer's Gauntlet: Layer 4 -> Colossal Ebonclaw Mawrat
    { 15310, 1532 }, -- A Tour of Towers -> Soaring Spelltome
    { 15322, 1564 }, -- Flawless Master (Layer 16) -> Colossal Soulshredder Mawrat
    { 15336, 1551 }, -- From A to Zereth -> Cryptic Aurelid
    { 15346, 1451, "Horde" }, -- Cosmic Combatant -> Vicious War Croaker
    { 15347, 1452, "Alliance" }, -- Cosmic Combatant -> Vicious War Croaker
    { 15352, 1572 }, -- Gladiator: Shadowlands Season 3 -> Cosmic Gladiator's Soul Eater
    { 15394, 1590 }, -- Ohn'a'Roll -> Windborne Velocidrake
    { 15402, 1431 }, -- Cyphers of the First Ones -> Pale Regal Cervid
    { 15491, 1549 }, -- Glory of the Sepulcher Raider -> Shimmering Aurelid
    { 15499, 1544 }, -- Shadowlands Keystone Master: Season Three -> Wastewarped Deathwalker
    { 15598, 1466, "Horde" }, -- Eternal Combatant -> Vicious Warstalker
    { 15599, 1465, "Alliance" }, -- Eternal Combatant -> Vicious Warstalker
    { 15605, 1599 }, -- Gladiator: Shadowlands Season 4 -> Eternal Gladiator's Soul Eater
    { 15684, 1576 }, -- Fates of the Shadowlands Raids -> Jigglesworth Sr.
    { 15690, 1405 }, -- Shadowlands Keystone Master: Season Four -> Restoration Deathwalker
    { 15833, 1654, "Horde" }, -- Thanks for the Carry! -> Otterworldly Ottuk Carrier
    { 15834, 1654, "Alliance" }, -- Thanks for the Carry! -> Otterworldly Ottuk Carrier
    { 15942, 1689, "Horde" }, -- Crimson Combatant -> Vicious Sabertooth
    { 15943, 1688, "Alliance" }, -- Crimson Combatant -> Vicious Sabertooth
    { 15957, 1660 }, -- Gladiator: Dragonflight Season 1 -> Crimson Gladiator's Drake
    { 16295, 1626 }, -- Glory of the Dragonflight Hero -> Shellack
    { 16334, 1589 }, -- Waking Hope -> Renewed Proto-Drake
    { 16336, 1563 }, -- Azure Spanner -> Highland Drake
    { 16355, 1644 }, -- Glory of the Vault Raider -> Raging Magmammoth
    { 16363, 1591 }, -- Just Don't Ask Me to Spell It -> Cliffside Wylderdrake
    { 16492, 1621 }, -- Into the Storm -> Coralscale Salamanther
    { 16649, 1681 }, -- Dragonflight Keystone Master: Season One -> Hailstorm Armoredon
    { 17727, 1740, "Alliance" }, -- Obsidian Combatant -> Vicious War Snail
    { 17728, 1741, "Horde" }, -- Obsidian Combatant -> Vicious War Snail
    { 17740, 1739 }, -- Gladiator: Dragonflight Season 2 -> Obsidian Gladiator's Slitherdrake
    { 17779, 1588 }, -- A Serpentine Discovery -> Winding Slitherdrake
    { 17785, 1733 }, -- Que Zara(lek), Zara(lek) -> Calescent Shalewing
    { 17844, 1725 }, -- Dragonflight Keystone Master: Season Two -> Inferno Armoredon
    { 18251, 1734 }, -- Glory of the Aberrus Raider -> Shadowflame Shalewing
    { 18646, 1794 }, -- Whodunnit? -> Pattie
    { 19011, 1801 }, -- Dragonflight Keystone Master: Season Three -> Verdant Armoredon
    { 19079, 1737 }, -- Master of the Turbulent Timeways -> Sandy Shalewing
    { 19091, 1831 }, -- Gladiator: Dragonflight Season 3 -> Verdant Gladiator's Slitherdrake
    { 19140, 1819, "Alliance" }, -- Verdant Combatant -> Vicious Moonbeast
    { 19141, 1820, "Horde" }, -- Verdant Combatant -> Vicious Moonbeast
    { 19349, 1814 }, -- Glory of the Dream Raider -> Shadow Dusk Dreamsaber
    { 19458, 1825 }, -- A World Awoken -> Taivan
    { 19479, 1669 }, -- Wake Me Up -> Bestowed Ohuna Spotter
    { 19481, 1474 }, -- Centaur of Attention -> Bestowed Thunderspine Packleader
    { 19482, 1633 }, -- Army of the Fed -> Bestowed Trawling Mammoth
    { 19483, 1651 }, -- Flight Club -> Bestowed Ottuk Vanguard
    { 19485, 1618 }, -- Closing Time -> Bestowed Sandskimmer
    { 19486, 1614 }, -- Across the Isles -> Stormtouched Bruffalon
    { 19490, 1822 }, -- Gladiator: Dragonflight Season 4 -> Draconic Gladiator's Drake
    { 19501, 2056, "Alliance" }, -- Draconic Combatant -> Vicious Dreamtalon
    { 19502, 2057, "Horde" }, -- Draconic Combatant -> Vicious Dreamtalon
    { 19574, 2091 }, -- Awakening the Dragonflight Raids -> Voyaging Wilderling
    { 19782, 2055 }, -- Dragonflight Keystone Master: Season Four -> Infinite Armoredon
    { 19876, 2143 }, -- Vale of Eternal Blossoms -> Astral Emperor's Serpent
    { 20501, 2114 }, -- Back from the Beyond -> Zovaal's Soul Eater
    { 20525, 2244 }, -- The War Within Keystone Master: Season One -> Diamond Mechsuit
    { 20593, 2142 }, -- Time Trial -> August Phoenix
    { 40097, 2167 }, -- Ruffious's Bid -> Raging Cinderbee
    { 40193, 1621 }, -- Into the Storm (copy) -> Coralscale Salamanther
    { 40232, 2180 }, -- Glory of the Nerub-ar Raider -> Shadowed Swarmite
    { 40307, 2214 }, -- Allied Races: Earthen -> Slatestone Ramolith
    { 40393, 2218 }, -- Gladiator: The War Within Season 1 -> Forged Gladiator's Fel Bat
    { 40396, 2211, "Alliance" }, -- Forged Combatant -> Vicious Skyflayer
    { 40397, 2150, "Horde" }, -- Forged Combatant -> Vicious Skyflayer
    { 40438, 2230 }, -- Glory of the War Within Delver -> Ivory Goliathus
    { 40539, 2188 }, -- The Derby Dash -> Kah, Legend of the Deep
    { 40702, 2181 }, -- Khaz Algar Glyph Hunter -> Swarmite Skyhunter
    { 40951, 2508 }, -- The War Within Keystone Legend: Season Two -> Enterprising Shreddertank
    { 40953, 2339 }, -- A Farewell to Arms -> Jani's Trashpile
    { 40956, 1277 }, -- I'm On Island Time -> Honeyback Hivemother
    { 40976, 2261 }, -- A Cool Twenty Years -> Coldflame Tempest
    { 41032, 2298 }, -- Gladiator: The War Within Season 2 -> Prized Gladiator's Fel Bat
    { 41049, 2326 }, -- Gladiator: The War Within Season 3 -> Astral Gladiator's Fel Bat
    { 41056, 2321 }, -- Master of the Turbulent Timeways II -> Timely Buzzbee
    { 41128, 2300, "Alliance" }, -- Prized Combatant -> Vicious Electro Eel
    { 41129, 2299, "Horde" }, -- Prized Combatant -> Vicious Electro Eel
    { 41133, 2332 }, -- Isle Remember You -> The Breaker's Song
    { 41201, 2190 }, -- You Xal Not Pass -> Shadow of Doubt
    { 41286, 2313 }, -- Glory of the Liberation of Undermine Raider -> Junkmaestro's Magnetomech
    { 41533, 2480 }, -- The War Within Keystone Master: Season Two -> Crimson Shreddertank
    { 41597, 2549 }, -- Glory of the Omega Raider -> Umbral K'arroc
    { 41751, 2144 }, -- Delver's Dirigible Recovery -> Delver's Dirigible
    { 41779, 2518 }, -- Master of the Turbulent Timeways III -> Chrono Corsair
    { 41929, 1282 }, -- Through the Depths of Visions -> Black Serpent of N'Zoth
    { 41966, 2500 }, -- Mastering the Visions -> Ny'alothan Shadow Worm
    { 41973, 2633 }, -- The War Within Keystone Master: Season Three -> Azure Void Flyer
    { 41980, 2511 }, -- Vigilante -> Terror of the Night
    { 42042, 2571, "Horde" }, -- Astral Combatant -> Vicious Void Creeper
    { 42043, 2570, "Alliance" }, -- Astral Combatant -> Vicious Void Creeper
    { 42172, 2631 }, -- The War Within Keystone Legend: Season Three -> Scarlet Void Flyer
    { 42212, 2604 }, -- Titan Console Overcharged -> OC91 Chariot
    { 42300, 2608 }, -- Two Minutes to Midnight -> Light-Forged Mechsuit
    { 42504, 2726 }, -- Timerunner: Paladin -> Felscorned Highlord's Charger
    { 42684, 2731 }, -- Timerunner: Warrior -> Felscorned War Wyrm
    { 42685, 2720 }, -- Timerunner: Death Knight -> Felscorned Vilebrood Vanquisher
    { 42686, 2729 }, -- Timerunner: Shaman -> Farseer's Felscorned Tempest
    { 42687, 2723 }, -- Timerunner: Hunter -> Felscorned Wolfhawk
    { 42703, 2771 }, -- Prey: Nightmare Mode III -> Preyseeker's Nightmare
    { 61017, 2655 }, -- Phase-Lost-and-Found -> Phase-Lost Slateback
    { 61084, 2728 }, -- Timerunner: Rogue -> Shadowblade's Felscorned Omen
    { 61085, 2725 }, -- Timerunner: Monk -> Felscorned Grandmaster's Companion
    { 61087, 2721 }, -- Timerunner: Demon Hunter -> Slayer's Felscorned Shrieker
    { 61088, 2727 }, -- Timerunner: Priest -> High Priest's Felscorned Seeker
    { 61089, 2724 }, -- Timerunner: Mage -> Archmage's Felscorned Disc
    { 61090, 2730 }, -- Timerunner: Warlock -> Felscorned Netherlord's Dreadsteed
    { 61188, 2801 }, -- Gladiator: Midnight Season 1 -> Galactic Gladiator's Goredrake
    { 61256, 2733 }, -- Midnight Keystone Master: Season 1 -> Calamitous Carrion
    { 61258, 2734 }, -- Midnight Keystone Legend: Season 1 -> Convalescent Carrion
    { 61263, 2912 }, -- Treasures of Harandar -> Vivacious Chloroceros
    { 61380, 2831 }, -- Glory of the Midnight Raider -> Tenebrous Harrower
    { 61403, 2793, "Horde" }, -- Galactic Combatant -> Vicious Snaplizard
    { 61405, 2794, "Alliance" }, -- Galactic Combatant -> Vicious Snaplizard
    { 61451, 2802 }, -- Worldsoul-Searching -> Geargrinder Mk. 11
    { 61463, 2806 }, -- Master of the Turbulent Timeways V -> Spawn of Vyranoth
    { 61506, 2616 }, -- Allied Race: Haranir -> Ivory Grimlynx
    { 61584, 2756 }, -- Midnight Glyph Hunter -> Crimson Dragonhawk
    { 61799, 2842 }, -- Let Me Solo Him: Nullaeus -> Arcanovoid Construct
    { 61906, 2773 }, -- Glory of the Midnight Delver -> Giganto Manis
    { 62096, 2917, "Horde" }, -- Insurmountable Collection -> Anu'shalla, Shadow's Guidance
    { 62103, 2917, "Alliance" }, -- Insurmountable Collection -> Anu'shalla, Shadow's Guidance
    { 62190, 2755 }, -- Life of the Party -> Umbral Dragonhawk
    { 62385, 2829 }, -- Staring Into The Void -> Lab-Grown Stormray
    { 62386, 2707 }, -- Light Up the Night -> Brilliant Petalwing
    { 62447, 3063 }, -- Midnight Keystone Master: Season 2 -> Breath of Blight
    { 62449, 3064 }, -- Midnight Keystone Legend: Season 2 -> Breath of Ruin
    { 62563, 2915 }, -- Void Response Team -> Unbound Manawyrm
    { 62873, 2988 }, -- A Trip Around the Stars -> Voidmancer's Starcarver
    { 62874, 2990 }, -- A Trip Through the Stars -> Netherforged Nullframe
    { 62930, 2821 }, -- Gladiator: Midnight Season 2 -> Venomous Gladiator's Goredrake
    { 63099, 3003, "Horde" }, -- Venomous Combatant -> Vicious Lightbloom Boar
    { 63103, 3002, "Alliance" }, -- Venomous Combatant -> Vicious Lightbloom Boar
    { 63104, 3069 }, -- Umbral Champion: Midnight Season 1 -> Umbral Ashes
    { 63254, 3021 }, -- Glory of the Venomous Raider -> Crimson Venomfang
    { 63264, 3033 }, -- Heroic Showdowns -> Tortured Gorger
    { 63333, 3029 }, -- Let Me Solo Him: Azta'rec -> Apophic Soul Crusher
    { 63359, 3023 }, -- Treasures of the Coiled Isle -> Auriferous Venomfang
    { 63630, 3062 }, -- Assault the Vault -> Venomous Coiler
    { 63653, 3053 }, -- Pro Poison Patroller -> Emerald Skyfang
    { 63715, 3144 }, -- Let Me Solo Him: Kindo'jan -> Loa-Blessed Wayfarer
}
