-- RocketMount | Data/MobDrops.lua
-- GENERATED by tools/coletar_raros.py on 2026-09-23 -- do not edit by hand.
--
-- Source: wowhead.com item pages, `Dropped by` list. For each creature, keyed by npc id:
-- `c` is Wowhead's classification (0 normal, 1 elite, 2 rare elite, 3 boss, 4 rare), and
-- for each mount the item id, how many times it dropped (`count`) and in how many kills
-- (`outof`). These are Wowhead's samples, not Blizzard's rates -- a small `count` is a
-- rough estimate, and the alert says so.
local ADDON, ns = ...

ns.MobDrops = {
    [10184] = { name = "Onyxia", c = 1,
        { item = 49636, count = 1220, outof = 83927 }, -- Reins of the Onyxian Drake
    },
    [15246] = { name = "Qiraji Mindslayer", c = 1,
        { item = 21321, count = 6307, outof = 633232 }, -- Red Qiraji Resonating Crystal
    },
    [15247] = { name = "Qiraji Brainwasher", c = 1,
        { item = 21321, count = 3314, outof = 318539 }, -- Red Qiraji Resonating Crystal
    },
    [15249] = { name = "Qiraji Lasher", c = 1,
        { item = 21321, count = 1121, outof = 114071 }, -- Red Qiraji Resonating Crystal
    },
    [15250] = { name = "Qiraji Slayer", c = 1,
        { item = 21321, count = 5940, outof = 645558 }, -- Red Qiraji Resonating Crystal
    },
    [15252] = { name = "Qiraji Champion", c = 1,
        { item = 21321, count = 3154, outof = 323656 }, -- Red Qiraji Resonating Crystal
    },
    [15262] = { name = "Obsidian Eradicator", c = 1,
        { item = 21321, count = 2171, outof = 229541 }, -- Red Qiraji Resonating Crystal
    },
    [15264] = { name = "Anubisath Sentinel", c = 1,
        { item = 21321, count = 5897, outof = 572152 }, -- Red Qiraji Resonating Crystal
    },
    [15277] = { name = "Anubisath Defender", c = 1,
        { item = 21321, count = 3513, outof = 377040 }, -- Red Qiraji Resonating Crystal
    },
    [15311] = { name = "Anubisath Warder", c = 1,
        { item = 21321, count = 1498, outof = 176120 }, -- Red Qiraji Resonating Crystal
    },
    [15312] = { name = "Obsidian Nullifier", c = 1,
        { item = 21321, count = 4766, outof = 350956 }, -- Red Qiraji Resonating Crystal
    },
    [16152] = { name = "Attumen the Huntsman", c = 1,
        { item = 30480, count = 3820, outof = 346946 }, -- Fiery Warhorse's Reins
    },
    [19622] = { name = "Kael'thas Sunstrider", c = 1,
        { item = 32458, count = 3179, outof = 187121 }, -- Ashes of Al'ar
    },
    [23035] = { name = "Anzu", c = 1,
        { item = 32768, count = 5346, outof = 332250 }, -- Reins of the Raven Lord
    },
    [24664] = { name = "Kael'thas Sunstrider", c = 1,
        { item = 35513, count = 8835, outof = 167661 }, -- Swift White Hawkstrider
    },
    [26693] = { name = "Skadi the Ruthless", c = 1,
        { item = 44151, count = 2407, outof = 197358 }, -- Reins of the Blue Proto-Drake
    },
    [28860] = { name = "Sartharion", c = 1,
        { item = 43954, count = 15739, outof = 36305 }, -- Reins of the Twilight Drake
        { item = 43986, count = 10749, outof = 36305 }, -- Reins of the Black Drake
    },
    [31125] = { name = "Archavon the Stone Watcher", c = 1,
        { item = 43959, count = 736, outof = 69331 }, -- Reins of the Grand Black War Mammoth
        { item = 44083, count = 576, outof = 69331 }, -- Reins of the Grand Black War Mammoth
    },
    [32273] = { name = "Infinite Corruptor", c = 1,
        { item = 43951, count = 23208, outof = 25266 }, -- Reins of the Bronze Drake
    },
    [32491] = { name = "Time-Lost Proto-Drake", c = 4,
        { item = 44168, count = 1870, outof = 1894 }, -- Reins of the Time-Lost Proto-Drake
    },
    [33288] = { name = "Yogg-Saron", c = 1,
        { item = 45693, count = 24, outof = 2442 }, -- Mimiron's Head
    },
    [33993] = { name = "Emalon the Storm Watcher", c = 1,
        { item = 43959, count = 686, outof = 67747 }, -- Reins of the Grand Black War Mammoth
        { item = 44083, count = 467, outof = 67747 }, -- Reins of the Grand Black War Mammoth
    },
    [35013] = { name = "Koralon the Flame Watcher", c = 1,
        { item = 43959, count = 666, outof = 65790 }, -- Reins of the Grand Black War Mammoth
        { item = 44083, count = 504, outof = 65790 }, -- Reins of the Grand Black War Mammoth
    },
    [36597] = { name = "The Lich King", c = 1,
        { item = 50818, count = 2054, outof = 265761 }, -- Invincible's Reins
    },
    [38433] = { name = "Toravon the Ice Watcher", c = 1,
        { item = 43959, count = 438, outof = 54178 }, -- Reins of the Grand Black War Mammoth
        { item = 44083, count = 427, outof = 54178 }, -- Reins of the Grand Black War Mammoth
    },
    [43214] = { name = "Slabhide", c = 1,
        { item = 63043, count = 975, outof = 110566 }, -- Reins of the Vitreous Stone Drake
    },
    [43873] = { name = "Altairus", c = 1,
        { item = 63040, count = 1073, outof = 139155 }, -- Reins of the Drake of the North Wind
    },
    [45412] = { name = "Lord Aurius Rivendare", c = 1,
        { item = 13335, count = 1671, outof = 193530 }, -- Deathcharger's Reins
    },
    [50005] = { name = "Poseidus", c = 4,
        { item = 67151, count = 2028, outof = 2049 }, -- Reins of Poseidus
    },
    [50062] = { name = "Aeonaxx", c = 4,
        { item = 63042, count = 1015, outof = 1015 }, -- Reins of the Phosphorescent Stone Drake
    },
    [50245] = { name = "Dormus the Camel-Hoarder", c = 1,
        { item = 63046, count = 1169, outof = 1170 }, -- Reins of the Grey Riding Camel
    },
    [52059] = { name = "High Priestess Kilnara", c = 1,
        { item = 68824, count = 2593, outof = 285605 }, -- Swift Zulian Panther
    },
    [52151] = { name = "Bloodlord Mandokir", c = 1,
        { item = 68823, count = 2116, outof = 308873 }, -- Armored Razzashi Raptor
    },
    [52530] = { name = "Alysrazor", c = 1,
        { item = 71665, count = 2643, outof = 127445 }, -- Flametalon of Alysrazor
    },
    [60491] = { name = "Sha of Anger", c = 1,
        { item = 87771, count = 240, outof = 87235 }, -- Reins of the Heavenly Onyx Cloud Serpent
    },
    [167749] = { name = "Doomwalker", c = 1,
        { item = 43959, count = 12, outof = 14545 }, -- Reins of the Grand Black War Mammoth
        { item = 44083, count = 12, outof = 14545 }, -- Reins of the Grand Black War Mammoth
    },
    [174062] = { name = "Skadi the Ruthless", c = 2,
        { item = 44151, count = 85, outof = 13717 }, -- Reins of the Blue Proto-Drake
    },
    [248741] = { name = "Rhazul", c = 4,
        { item = 246735, count = 7, outof = 6391 }, -- Rootstalker Grimlynx
    },
    [249844] = { name = "Chironex", c = 4,
        { item = 246735, count = 7, outof = 5714 }, -- Rootstalker Grimlynx
    },
    [249849] = { name = "Ha'kalawe", c = 4,
        { item = 246735, count = 8, outof = 6653 }, -- Rootstalker Grimlynx
    },
    [249902] = { name = "Tallcap the Truthspreader", c = 4,
        { item = 246735, count = 9, outof = 4488 }, -- Rootstalker Grimlynx
    },
    [249962] = { name = "Queen Lashtongue", c = 4,
        { item = 246735, count = 12, outof = 6790 }, -- Rootstalker Grimlynx
    },
    [249997] = { name = "Chlorokyll", c = 4,
        { item = 246735, count = 5, outof = 4997 }, -- Rootstalker Grimlynx
    },
    [250086] = { name = "Stumpy", c = 2,
        { item = 246735, count = 9, outof = 5560 }, -- Rootstalker Grimlynx
    },
    [250180] = { name = "Serrasa", c = 4,
        { item = 246735, count = 11, outof = 5494 }, -- Rootstalker Grimlynx
    },
    [250226] = { name = "Mindrot", c = 4,
        { item = 246735, count = 7, outof = 5634 }, -- Rootstalker Grimlynx
    },
    [250231] = { name = "Dracaena", c = 4,
        { item = 246735, count = 7, outof = 5862 }, -- Rootstalker Grimlynx
    },
    [250246] = { name = "Treetop", c = 4,
        { item = 246735, count = 8, outof = 5193 }, -- Rootstalker Grimlynx
    },
    [250317] = { name = "Oro'ohna", c = 2,
        { item = 246735, count = 15, outof = 5390 }, -- Rootstalker Grimlynx
    },
    [250321] = { name = "Pterrock", c = 4,
        { item = 246735, count = 5, outof = 4191 }, -- Rootstalker Grimlynx
    },
    [250347] = { name = "Ahl'ua'huhi", c = 4,
        { item = 246735, count = 7, outof = 5881 }, -- Rootstalker Grimlynx
    },
    [250358] = { name = "Annulus the Worldshaker", c = 2,
        { item = 246735, count = 5, outof = 2508 }, -- Rootstalker Grimlynx
    },
}
