-- RocketMount | Data/MobDrops.lua
-- GENERATED by tools/coletar_raros.py on 2026-10-06 -- do not edit by hand.
--
-- Source: wowhead.com item pages, `Dropped by` list. For each creature, keyed by npc id:
-- `c` is Wowhead's classification (0 normal, 1 elite, 2 rare elite, 3 boss, 4 rare), and
-- for each mount the item id, how many times it dropped (`count`) and in how many kills
-- (`outof`). These are Wowhead's samples, not Blizzard's rates -- a small `count` is a
-- rough estimate, and the alert says so. `unknown = true` is a creature the GAME'S JOURNAL
-- names as the one that drops the mount, with no drop recorded yet: no chance is stated.
-- `where` is where Wowhead's map puts the creature: { [uiMapID] = { x1, y1, x2, y2, ... } },
-- in the 0-100 scale: every distinct place, points closer than 3.5 collapsed. Feeds the map pins.
-- A sample that Wowhead repeats, lonely, over 3 or more creatures of one map is the zone's and
-- not a place: left out (2 of them in this build).
-- `route` is for the creature that WALKS: { [uiMapID] = { { x1, y1, x2, y2, ... }, ... } },
-- the points it was seen at, in the order of the shortest path through them (`loop = true`
-- when the path closes). Such a creature has ONE place in `where` per route, where it was
-- seen most, and the map draws the route. An estimate: Wowhead records sightings, not paths.
-- 31 routes in this build.
local ADDON, ns = ...

ns.MobDrops = {
    [7604] = { name = "Sergeant Bly", c = 1,
        { item = 133543, count = 1, outof = 10013 }, -- Infinite Timereaver
    },
    [10184] = { name = "Onyxia", c = 1,
        { item = 49636, count = 654, outof = 39251 }, -- Onyxian Drake
    },
    [11143] = { name = "Postmaster Malown", c = 1,
        { item = 133543, count = 2, outof = 1336 }, -- Infinite Timereaver
    },
    [15246] = { name = "Qiraji Mindslayer", c = 1,
        { item = 21218, count = 46762, outof = 570362 }, -- Blue Qiraji Battle Tank
        { item = 21321, count = 5417, outof = 570362 }, -- Red Qiraji Battle Tank
        { item = 21323, count = 47362, outof = 570362 }, -- Green Qiraji Battle Tank
        { item = 21324, count = 44185, outof = 570362 }, -- Yellow Qiraji Battle Tank
    },
    [15247] = { name = "Qiraji Brainwasher", c = 1,
        { item = 21218, count = 19817, outof = 259351 }, -- Blue Qiraji Battle Tank
        { item = 21321, count = 2526, outof = 259351 }, -- Red Qiraji Battle Tank
        { item = 21323, count = 23639, outof = 259351 }, -- Green Qiraji Battle Tank
        { item = 21324, count = 21388, outof = 259351 }, -- Yellow Qiraji Battle Tank
    },
    [15249] = { name = "Qiraji Lasher", c = 1,
        { item = 21218, count = 8167, outof = 94946 }, -- Blue Qiraji Battle Tank
        { item = 21321, count = 892, outof = 94946 }, -- Red Qiraji Battle Tank
        { item = 21323, count = 7122, outof = 94946 }, -- Green Qiraji Battle Tank
        { item = 21324, count = 7984, outof = 94946 }, -- Yellow Qiraji Battle Tank
    },
    [15250] = { name = "Qiraji Slayer", c = 1,
        { item = 21218, count = 48320, outof = 588728 }, -- Blue Qiraji Battle Tank
        { item = 21321, count = 5103, outof = 588728 }, -- Red Qiraji Battle Tank
        { item = 21323, count = 50258, outof = 588728 }, -- Green Qiraji Battle Tank
        { item = 21324, count = 48394, outof = 588728 }, -- Yellow Qiraji Battle Tank
    },
    [15252] = { name = "Qiraji Champion", c = 1,
        { item = 21218, count = 24718, outof = 291658 }, -- Blue Qiraji Battle Tank
        { item = 21321, count = 2755, outof = 291658 }, -- Red Qiraji Battle Tank
        { item = 21323, count = 24228, outof = 291658 }, -- Green Qiraji Battle Tank
        { item = 21324, count = 24108, outof = 291658 }, -- Yellow Qiraji Battle Tank
    },
    [15262] = { name = "Obsidian Eradicator", c = 1,
        { item = 21218, count = 14351, outof = 169140 }, -- Blue Qiraji Battle Tank
        { item = 21321, count = 1479, outof = 169140 }, -- Red Qiraji Battle Tank
        { item = 21323, count = 13084, outof = 169140 }, -- Green Qiraji Battle Tank
        { item = 21324, count = 13796, outof = 169140 }, -- Yellow Qiraji Battle Tank
    },
    [15264] = { name = "Anubisath Sentinel", c = 1,
        { item = 21218, count = 31568, outof = 395878 }, -- Blue Qiraji Battle Tank
        { item = 21321, count = 3960, outof = 395878 }, -- Red Qiraji Battle Tank
        { item = 21323, count = 34309, outof = 395878 }, -- Green Qiraji Battle Tank
        { item = 21324, count = 35918, outof = 395878 }, -- Yellow Qiraji Battle Tank
    },
    [15277] = { name = "Anubisath Defender", c = 1,
        { item = 21218, count = 25818, outof = 335135 }, -- Blue Qiraji Battle Tank
        { item = 21321, count = 2984, outof = 335135 }, -- Red Qiraji Battle Tank
        { item = 21323, count = 27016, outof = 335135 }, -- Green Qiraji Battle Tank
        { item = 21324, count = 28776, outof = 335135 }, -- Yellow Qiraji Battle Tank
    },
    [15311] = { name = "Anubisath Warder", c = 1,
        { item = 21218, count = 14401, outof = 156180 }, -- Blue Qiraji Battle Tank
        { item = 21321, count = 1160, outof = 156180 }, -- Red Qiraji Battle Tank
        { item = 21323, count = 12331, outof = 156180 }, -- Green Qiraji Battle Tank
        { item = 21324, count = 15098, outof = 156180 }, -- Yellow Qiraji Battle Tank
    },
    [15312] = { name = "Obsidian Nullifier", c = 1,
        { item = 21218, count = 25073, outof = 314416 }, -- Blue Qiraji Battle Tank
        { item = 21321, count = 4293, outof = 314416 }, -- Red Qiraji Battle Tank
        { item = 21323, count = 25616, outof = 314416 }, -- Green Qiraji Battle Tank
        { item = 21324, count = 25826, outof = 314416 }, -- Yellow Qiraji Battle Tank
    },
    [16061] = { name = "Instructor Razuvious", c = 1,
        { item = 206585, count = 531, outof = 35435 }, -- Valiance
    },
    [16152] = { name = "Attumen the Huntsman", c = 1,
        { item = 30480, count = 3820, outof = 346945 }, -- Fiery Warhorse
    },
    [17941] = { name = "Mennu the Betrayer", c = 1,
        { item = 133543, count = 51, outof = 33177 }, -- Infinite Timereaver
    },
    [19622] = { name = "Kael'thas Sunstrider", c = 1,
        { item = 32458, count = 2810, outof = 170188 }, -- Ashes of Al'ar
    },
    [23035] = { name = "Anzu", c = 1,
        { item = 32768, count = 5346, outof = 332250 }, -- Raven Lord
    },
    [23872] = { name = "Coren Direbrew", c = 4,
        { item = 248761, unknown = true }, -- Brewfest Bomber
    },
    [24664] = { name = "Kael'thas Sunstrider", c = 1,
        { item = 35513, count = 8835, outof = 167661 }, -- Swift White Hawkstrider
    },
    [25740] = { name = "Ahune", c = 4,
        { item = 275464, unknown = true }, -- Sun Festival's Painted Roc
    },
    [26693] = { name = "Skadi the Ruthless", c = 1,
        { item = 44151, count = 2407, outof = 197358 }, -- Blue Proto-Drake
    },
    [28860] = { name = "Sartharion", c = 1,
        { item = 43954, count = 15739, outof = 20977 }, -- Twilight Drake
        { item = 43986, count = 10749, outof = 15328 }, -- Black Drake
    },
    [29573] = { name = "Drakkari Elemental", c = 1,
        { item = 133543, count = 15, outof = 72875 }, -- Infinite Timereaver
    },
    [31125] = { name = "Archavon the Stone Watcher", c = 1,
        { item = 43959, count = 498, outof = 44134 }, -- Grand Black War Mammoth
        { item = 44083, count = 309, outof = 44134 }, -- Grand Black War Mammoth
    },
    [32273] = { name = "Infinite Corruptor", c = 1,
        { item = 43951, count = 23208, outof = 25266 }, -- Bronze Drake
    },
    [32491] = { name = "Time-Lost Proto-Drake", c = 4,
        { item = 44168, count = 1870, outof = 1894 }, -- Time-Lost Proto-Drake
        where = { [120] = { 28, 65.4, 36.6, 69.8, 39.4, 84.4, 41.2, 68.2 } },
    },
    [33288] = { name = "Yogg-Saron", c = 1,
        { item = 45693, count = 24, outof = 2028 }, -- Mimiron's Head
    },
    [33993] = { name = "Emalon the Storm Watcher", c = 1,
        { item = 43959, count = 468, outof = 43903 }, -- Grand Black War Mammoth
        { item = 44083, count = 279, outof = 43903 }, -- Grand Black War Mammoth
    },
    [35013] = { name = "Koralon the Flame Watcher", c = 1,
        { item = 43959, count = 486, outof = 43271 }, -- Grand Black War Mammoth
        { item = 44083, count = 352, outof = 43271 }, -- Grand Black War Mammoth
    },
    [36296] = { name = "Apothecary Hummel", c = 4,
        { item = 232926, unknown = true }, -- Love Witch's Sweeper
        { item = 235658, unknown = true }, -- Spring Butterfly
    },
    [36597] = { name = "The Lich King", c = 1,
        { item = 50818, count = 2054, outof = 205760 }, -- Invincible
    },
    [38433] = { name = "Toravon the Ice Watcher", c = 1,
        { item = 43959, count = 284, outof = 35210 }, -- Grand Black War Mammoth
        { item = 44083, count = 300, outof = 35210 }, -- Grand Black War Mammoth
    },
    [39625] = { name = "General Umbriss", c = 1,
        { item = 133543, count = 17, outof = 83101 }, -- Infinite Timereaver
    },
    [40177] = { name = "Forgemaster Throngus", c = 1,
        { item = 133543, count = 52, outof = 84846 }, -- Infinite Timereaver
    },
    [40319] = { name = "Drahga Shadowburner", c = 1,
        { item = 133543, count = 24, outof = 83935 }, -- Infinite Timereaver
    },
    [40484] = { name = "Erudax", c = 1,
        { item = 133543, count = 4, outof = 76847 }, -- Infinite Timereaver
    },
    [40586] = { name = "Lady Naz'jar", c = 1,
        { item = 133543, count = 8, outof = 91594 }, -- Infinite Timereaver
    },
    [40765] = { name = "Commander Ulthok", c = 1,
        { item = 133543, count = 5, outof = 71399 }, -- Infinite Timereaver
    },
    [40788] = { name = "Mindbender Ghur'sha", c = 1,
        { item = 133543, count = -1, outof = 11190 }, -- Infinite Timereaver
    },
    [42188] = { name = "Ozruk", c = 1,
        { item = 133543, count = 7, outof = 93086 }, -- Infinite Timereaver
    },
    [42333] = { name = "High Priestess Azil", c = 1,
        { item = 133543, count = 10, outof = 94005 }, -- Infinite Timereaver
    },
    [43214] = { name = "Slabhide", c = 1,
        { item = 63043, count = 1877, outof = 238367 }, -- Vitreous Stone Drake
        { item = 133543, count = 72, outof = 82558 }, -- Infinite Timereaver
    },
    [43438] = { name = "Corborus", c = 1,
        { item = 133543, count = 86, outof = 71289 }, -- Infinite Timereaver
    },
    [43612] = { name = "High Prophet Barim", c = 1,
        { item = 133543, count = 6, outof = 101130 }, -- Infinite Timereaver
    },
    [43873] = { name = "Altairus", c = 1,
        { item = 63040, count = 1514, outof = 175024 }, -- Drake of the North Wind
        { item = 133543, count = 6, outof = 81285 }, -- Infinite Timereaver
    },
    [43875] = { name = "Asaad", c = 1,
        { item = 133543, count = 4, outof = 88928 }, -- Infinite Timereaver
    },
    [43878] = { name = "Grand Vizier Ertan", c = 1,
        { item = 133543, count = 40, outof = 87512 }, -- Infinite Timereaver
    },
    [44577] = { name = "General Husam", c = 1,
        { item = 133543, count = 36, outof = 99060 }, -- Infinite Timereaver
    },
    [44819] = { name = "Siamat", c = 1,
        { item = 133543, count = 46, outof = 106661 }, -- Infinite Timereaver
    },
    [45412] = { name = "Lord Aurius Rivendare", c = 1,
        { item = 13335, count = 1671, outof = 193530 }, -- Rivendare's Deathcharger
    },
    [49045] = { name = "Augh", c = 1,
        { item = 133543, count = 7, outof = 98052 }, -- Infinite Timereaver
    },
    [50005] = { name = "Poseidus", c = 4,
        { item = 67151, count = 2028, outof = 2049 }, -- Subdued Seahorse
        where = { [204] = { 40.6, 75.6 }, [205] = { 44.6, 49.6, 40, 67.2, 58.2, 83.2, 65.8, 43.2 } },
        route = { [204] = { { 40.6, 73, 40.6, 75.6 } } },
    },
    [50062] = { name = "Aeonaxx", c = 4,
        { item = 63042, count = 1015, outof = 1015 }, -- Phosphorescent Stone Drake
        where = { [207] = { 47, 57.4, 61.4, 26.4, 41.4, 82.4, 66, 64.4 } },
        route = { [207] = { { 53.6, 39.4, 51.6, 42.8, 46.4, 44.8, 41.8, 43.6, 35, 42, 31.2, 42.6, 39.4, 48.8, 43.2, 48.4, 42.8, 58.4, 47, 57.4, 55, 54 }, { 61.4, 26.4, 64.8, 19.2 } } },
    },
    [50245] = { name = "Dormus the Camel-Hoarder", c = 1,
        { item = 63046, count = 1169, outof = 1170 }, -- Grey Riding Camel
        where = { [69] = { 69.4, 73.2 } },
    },
    [50883] = { name = "Pathrunner", c = 2,
        { item = 116773, count = 3883, outof = 3885 }, -- Swift Breezestrider
        where = { [539] = { 39.4, 36.4, 43, 31.6, 44.6, 43.4, 45.8, 67.4, 53.4, 30.8, 56.6, 52.6 } },
    },
    [50981] = { name = "Luk'hok", c = 2,
        { item = 116661, count = 3318, outof = 3318 }, -- Mottled Meadowstomper
        where = { [550] = { 66.2, 44, 72.6, 53.8, 75.2, 32.2, 79.4, 56, 84.2, 63.2 } },
    },
    [50985] = { name = "Poundfist", c = 2,
        { item = 116792, count = 2560, outof = 2564 }, -- Sunhide Gronnling
        where = { [543] = { 42, 25, 43.2, 55.5, 45.4, 47.5, 47, 54.1, 51.4, 43.1 } },
    },
    [50990] = { name = "Nakk the Thunderer", c = 2,
        { item = 116659, count = 1464, outof = 1464 }, -- Bloodhoof Bull
        where = { [550] = { 55, 35.4, 63, 16 } },
        route = { [550] = { { 50, 34.2, 55, 35.4, 60.2, 32 }, { 63, 16, 64.4, 20 } } },
    },
    [50992] = { name = "Gorok", c = 2,
        { item = 116674, count = 3722, outof = 3723 }, -- Great Greytusk
        where = { [525] = { 23.2, 65.6, 51.2, 50.6, 58.4, 19.2, 63.6, 80.4, 64.4, 52.4 } },
    },
    [51015] = { name = "Silthide", c = 2,
        { item = 116767, count = 2252, outof = 2252 }, -- Sapphire Riverbeast
        where = { [535] = { 55, 81.2, 62, 32.4, 62.4, 46.2, 67.2, 59.8, 80, 55.4 } },
    },
    [52059] = { name = "High Priestess Kilnara", c = 1,
        { item = 68824, count = 2593, outof = 285605 }, -- Swift Zulian Panther
    },
    [52151] = { name = "Bloodlord Mandokir", c = 1,
        { item = 68823, count = 2116, outof = 308873 }, -- Armored Razzashi Raptor
    },
    [52530] = { name = "Alysrazor", c = 1,
        { item = 71665, count = 950, outof = 53292 }, -- Flametalon of Alysrazor
    },
    [54123] = { name = "Echo of Sylvanas", c = 1,
        { item = 133543, count = 47, outof = 50457 }, -- Infinite Timereaver
    },
    [54445] = { name = "Echo of Jaina", c = 1,
        { item = 133543, count = 5, outof = 32079 }, -- Infinite Timereaver
    },
    [54544] = { name = "Echo of Tyrande", c = 1,
        { item = 133543, count = 16, outof = 54012 }, -- Infinite Timereaver
    },
    [60491] = { name = "Sha of Anger", c = 1,
        { item = 87771, count = 240, outof = 87235 }, -- Heavenly Onyx Cloud Serpent
        where = { [379] = { 54.4, 63.2 } },
    },
    [62346] = { name = "Galleon", c = 1,
        { item = 89783, count = 162, outof = 63300 }, -- Son of Galleon
        where = { [376] = { 71.6, 64.4 } },
    },
    [64403] = { name = "Alani", c = 1,
        { item = 90655, count = 954, outof = 954 }, -- Thundering Ruby Cloud Serpent
        where = { [390] = { 55.2, 48.6 } },
        route = { [390] = { { 18, 22.8, 21.2, 18.2, 31.2, 23, 35.6, 26, 34.8, 30.2, 40.6, 30.8, 41.4, 32.8, 38.8, 37, 28.6, 38.4, 16.4, 38, 18.6, 44.6, 22.4, 48.8, 24.2, 54.6, 24.2, 62.2, 24.6, 67.8, 25.2, 71.8, 32, 72.8, 36.4, 68.2, 37, 63.8, 41.2, 67.8, 46, 69.6, 50.6, 69.4, 41.6, 60.4, 43.4, 56.8, 45.6, 50.4, 47.4, 46.6, 55.2, 48.6, 59, 49.4, 62.4, 50.6, 60.4, 45.4, 56.2, 42.6, 52.6, 38.6, 54, 31.6, 60.2, 30.6, 59, 25.6, 54.6, 23.6, 52.4, 24.8, 48.4, 27, 46, 31.2, 46.2, 36.8, 48, 43, 43.6, 43.8, 36.8, 43.2, 35.8, 48, 30.6, 54.2 } } },
    },
    [65090] = { name = "Fabious", c = 4,
        { item = 169201, unknown = true }, -- Fabious
        where = { [1355] = { 37.8, 11, 27, 31.4, 74, 52.2, 48.8, 85.2, 38.8, 53 } },
        route = { [1355] = { { 37.8, 11, 39.6, 13 }, { 27, 31.4, 28, 33, 31.2, 30.4 }, { 74, 52.2, 77.6, 51.8 } } },
    },
    [68476] = { name = "Horridon", c = 1,
        { item = 93666, count = 439, outof = 11100 }, -- Spawn of Horridon
    },
    [69099] = { name = "Nalak", c = 1,
        { item = 95057, count = 165, outof = 49516 }, -- Thundering Cobalt Cloud Serpent
        where = { [504] = { 60.5, 37.3 } },
    },
    [69161] = { name = "Oondasta", c = 1,
        { item = 94228, count = 149, outof = 38360 }, -- Cobalt Primordial Direhorn
        where = { [507] = { 49.9, 54 } },
    },
    [69712] = { name = "Ji-Kun", c = 1,
        { item = 95059, count = 1211, outof = 36146 }, -- Clutch of Ji-Kun
    },
    [69768] = { name = "Zandalari Warscout", c = 4,
        { item = 94230, count = 15, outof = 298824 }, -- Amber Primordial Direhorn
        where = { [371] = { 45, 17.8 }, [379] = { 74.2, 67.2 }, [388] = { 37.2, 86 }, [418] = { 38.4, 65.6, 57.8, 29.2 }, [422] = { 46.4, 59.6 } },
        route = { [371] = { { 45, 17.8, 47.6, 21, 51.6, 20, 52.8, 23.8, 53.8, 28.6, 53.2, 30.6, 53, 36.4 } }, [379] = { { 66.2, 65, 69.6, 65.2, 74.2, 67.2, 72.4, 71.2, 70.6, 75.4, 67, 81 } }, [388] = { { 37.2, 86, 40.4, 89.6, 44.2, 90.2, 46.8, 89.6, 48.8, 84.6, 48.8, 74.2, 45.6, 75.2, 40.4, 77.4, 39.6, 81, loop = true } }, [418] = { { 36.2, 60.2, 38.4, 65.6 } }, [422] = { { 38, 48.6, 41.2, 50.2, 45.4, 56, 46.4, 59.6, 49, 62.6, 50, 64.8, 56, 66.6, 57.6, 66 } } },
    },
    [69769] = { name = "Zandalari Warbringer", c = 2,
        { item = 94229, count = 3757, outof = 93318 }, -- Slate Primordial Direhorn
        where = { [371] = { 52.6, 19 }, [379] = { 75, 67.4 }, [388] = { 36.4, 85.4 }, [418] = { 38.8, 66.4 }, [422] = { 47.6, 61.4 } },
    },
    [69841] = { name = "Zandalari Warbringer", c = 2,
        { item = 94230, count = 2652, outof = 54875 }, -- Amber Primordial Direhorn
        where = { [371] = { 52.6, 19 }, [379] = { 75, 67.4 }, [388] = { 36.4, 85.4 }, [422] = { 47.4, 61.6 } },
    },
    [69842] = { name = "Zandalari Warbringer", c = 2,
        { item = 94231, count = 2073, outof = 52627 }, -- Jade Primordial Direhorn
        where = { [371] = { 52.6, 19 }, [379] = { 75, 67.4 }, [388] = { 36.4, 85.4 }, [422] = { 47.4, 61.6 } },
    },
    [71865] = { name = "Garrosh Hellscream", c = 1,
        { item = 104253, count = 856, outof = 37132 }, -- Kor'kron Juggernaut
    },
    [73167] = { name = "Huolon", c = 2,
        { item = 104269, count = 681, outof = 76296 }, -- Thundering Onyx Cloud Serpent
        where = { [554] = { 66.6, 57.6 } },
        route = { [554] = { { 57.6, 57.8, 66.6, 57.6, 68.6, 58.4, 72.4, 54.4, 73, 50.8, 74.2, 41.6, 65.4, 36.2, loop = true } } },
    },
    [74475] = { name = "Magmolatus", c = 1,
        { item = 133543, count = 3, outof = 18657 }, -- Infinite Timereaver
    },
    [77325] = { name = "Blackhand", c = 1,
        { item = 116660, count = 2730, outof = 73599 }, -- Ironhoof Destroyer
    },
    [81001] = { name = "Nok-Karosh", c = 1,
        { item = 116794, count = 13745, outof = 13746 }, -- Garn Nighthowl
        where = { [525] = { 13.6, 51 } },
    },
    [83746] = { name = "Rukhmar", c = 1,
        { item = 116771, count = 185, outof = 5479 }, -- Solar Spirehawk
        where = { [542] = { 47.1, 78.4 } },
    },
    [90802] = { name = "Annihilon", c = 1,
        { item = 116663, count = 7, outof = 2076 }, -- Shadowhide Pearltusk
        { item = 116673, count = 10, outof = 2076 }, -- Giant Coldsnout
        { item = 116779, count = 25, outof = 2076 }, -- Garn Steelmaw
    },
    [90841] = { name = "Commander Dro'gan", c = 1,
        { item = 116663, count = 4, outof = 2949 }, -- Shadowhide Pearltusk
        { item = 116673, count = 25, outof = 2949 }, -- Giant Coldsnout
        { item = 116779, count = 7, outof = 2949 }, -- Garn Steelmaw
        { item = 116786, count = 20, outof = 2949 }, -- Smoky Direwolf
    },
    [90943] = { name = "Gaur", c = 1,
        { item = 116673, count = 21, outof = 1127 }, -- Giant Coldsnout
        { item = 116779, count = 3, outof = 1127 }, -- Garn Steelmaw
        { item = 116786, count = 2, outof = 1127 }, -- Smoky Direwolf
    },
    [90946] = { name = "Teluur", c = 1,
        { item = 116673, count = 19, outof = 895 }, -- Giant Coldsnout
        { item = 116779, count = 2, outof = 895 }, -- Garn Steelmaw
        { item = 116786, count = 5, outof = 895 }, -- Smoky Direwolf
    },
    [90995] = { name = "Mage Lord Gogg'nathog", c = 1,
        { item = 116663, count = 23, outof = 990 }, -- Shadowhide Pearltusk
        { item = 116673, count = 3, outof = 990 }, -- Giant Coldsnout
        { item = 116779, count = 3, outof = 990 }, -- Garn Steelmaw
        { item = 116786, count = 29, outof = 990 }, -- Smoky Direwolf
    },
    [91012] = { name = "Lady Fleshsear", c = 1,
        { item = 116663, count = 13, outof = 1931 }, -- Shadowhide Pearltusk
        { item = 116673, count = 12, outof = 1931 }, -- Giant Coldsnout
        { item = 116779, count = 5, outof = 1931 }, -- Garn Steelmaw
        { item = 116786, count = 77, outof = 1931 }, -- Smoky Direwolf
    },
    [91331] = { name = "Archimonde", c = 1,
        { item = 123890, count = 2243, outof = 29965 }, -- Felsteel Annihilator
    },
    [95044] = { name = "Terrorfist", c = 4,
        { item = 116658, unknown = true }, -- Tundra Icehoof
        { item = 116669, unknown = true }, -- Armored Razorback
        { item = 116780, unknown = true }, -- Warsong Direfang
        where = { [534] = { 14.2, 60.6 } },
        route = { [534] = { { 14.2, 60.6, 15.2, 63.6 } } },
    },
    [95053] = { name = "Deathtalon", c = 4,
        { item = 116658, unknown = true }, -- Tundra Icehoof
        { item = 116669, unknown = true }, -- Armored Razorback
        { item = 116780, unknown = true }, -- Warsong Direfang
        where = { [534] = { 23.6, 39.8 } },
    },
    [95054] = { name = "Vengeance", c = 4,
        { item = 116658, unknown = true }, -- Tundra Icehoof
        { item = 116669, unknown = true }, -- Armored Razorback
        { item = 116780, unknown = true }, -- Warsong Direfang
        where = { [534] = { 32.4, 73.8 } },
    },
    [95056] = { name = "Doomroller", c = 4,
        { item = 116658, unknown = true }, -- Tundra Icehoof
        { item = 116669, unknown = true }, -- Armored Razorback
        { item = 116780, unknown = true }, -- Warsong Direfang
        where = { [534] = { 47, 52.6 } },
    },
    [95888] = { name = "Cordana Felsong", c = 1,
        { item = 133543, count = 3, outof = 14174 }, -- Infinite Timereaver
    },
    [98970] = { name = "Latosius", c = 1,
        { item = 133543, count = 5, outof = 15911 }, -- Infinite Timereaver
    },
    [104154] = { name = "Gul'dan", c = 1,
        { item = 137574, count = -1, outof = 7 }, -- Felblaze Infernal
        { item = 137575, count = -1, outof = 7 }, -- Hellfire Infernal
    },
    [111022] = { name = "The Demon Within", c = 1,
        { item = 137574, count = 168, outof = 38537 }, -- Felblaze Infernal
        { item = 137575, count = 3093, outof = 38537 }, -- Hellfire Infernal
    },
    [111573] = { name = "Kosumoth the Hungering", c = 4,
        { item = 138201, unknown = true }, -- Fathom Dweller
        where = { [790] = { 46.4, 49.2 } },
    },
    [114262] = { name = "Attumen the Huntsman", c = 1,
        { item = 142236, count = 1038, outof = 78508 }, -- Midnight
    },
    [114637] = { name = "Spectral Sentry", c = 1,
        { item = 142552, count = 3, outof = 11730 }, -- Smoldering Ember Wyrm
    },
    [114803] = { name = "Spectral Stable Hand", c = 1,
        { item = 142236, count = 7, outof = 20551 }, -- Midnight
    },
    [114895] = { name = "Nightbane", c = 1,
        { item = 142552, count = 5754, outof = 30881 }, -- Smoldering Ember Wyrm
    },
    [115767] = { name = "Mistress Sassz'ine", c = 1,
        { item = 143643, count = 89, outof = 32281 }, -- Abyss Worm
    },
    [119629] = { name = "Lord Hel'nurath", c = 2,
        { item = 142233, count = 8, outof = 14 }, -- Netherlord's Accursed Wrathsteed
        where = { [646] = { 45.2, 51.8 } },
    },
    [122958] = { name = "Blistermaw", c = 2,
        { item = 152905, count = 1441, outof = 49748 }, -- Crimson Slavermaw
        where = { [885] = { 61.8, 37.2 } },
    },
    [124828] = { name = "Argus the Unmaker", c = 1,
        { item = 152789, count = -1, outof = 19 }, -- Shackled Ur'zul
    },
    [126040] = { name = "Puscilla", c = 2,
        { item = 152903, count = 389, outof = 10133 }, -- Biletooth Gnasher
        where = { [885] = { 64, 20.8 } },
    },
    [126187] = { name = "Corpse Bringer Yal'kar", c = 4,
        { item = 163575, count = 26, outof = 93354 }, -- Leaping Veinseeker
        where = { [863] = { 41.2, 53.4 } },
    },
    [126199] = { name = "Vrax'thul", c = 2,
        { item = 152903, count = 1384, outof = 40874 }, -- Biletooth Gnasher
        where = { [885] = { 53, 36.4 } },
    },
    [126852] = { name = "Wrangler Kravos", c = 2,
        { item = 152814, count = 1670, outof = 45811 }, -- Maddened Chaosrunner
        where = { [882] = { 55.6, 59.8 } },
    },
    [126867] = { name = "Venomtail Skyfin", c = 2,
        { item = 152844, count = 1176, outof = 36536 }, -- Lambent Mana Ray
        where = { [882] = { 33.4, 48.2 } },
    },
    [126912] = { name = "Skreeg the Devourer", c = 2,
        { item = 152904, count = 1050, outof = 38707 }, -- Acid Belcher
        where = { [882] = { 49.4, 9.8 } },
    },
    [126983] = { name = "Harlan Sweete", c = 1,
        { item = 159842, count = 863, outof = 173721 }, -- Sharkbait
    },
    [127288] = { name = "Houndmaster Kerrax", c = 2,
        { item = 152790, count = 2208, outof = 63395 }, -- Vile Fiend
        where = { [885] = { 63.6, 22.6 } },
    },
    [128686] = { name = "Kamid the Trapper", c = 4,
        { item = 163576, count = 22, outof = 48421 }, -- Dune Scavenger
        where = { [864] = { 35.2, 51.4 } },
    },
    [130079] = { name = "Wagga Snarltusk", c = 4,
        { item = 163573, count = 2, outof = 45181 }, -- Goldenmane
    },
    [130897] = { name = "Captain Razorspine", c = 4,
        { item = 163573, count = 26, outof = 168858 }, -- Goldenmane
        where = { [942] = { 47.2, 65.4 } },
    },
    [131404] = { name = "Foreman Scripps", c = 4,
        { item = 163573, count = 68, outof = 95703 }, -- Goldenmane
        where = { [942] = { 64.4, 65.8 } },
    },
    [133007] = { name = "Unbound Abomination", c = 1,
        { item = 160829, count = 546, outof = 132843 }, -- Underrot Crawg
    },
    [134745] = { name = "Skycarver Krakit", c = 4,
        { item = 163576, count = 81, outof = 77872 }, -- Dune Scavenger
        where = { [864] = { 51.4, 36.2 } },
    },
    [138794] = { name = "Dunegorger Kraulok", c = 2,
        { item = 174842, count = 128, outof = 1966 }, -- Mollie
        where = { [864] = { 44.2, 55.8 } },
    },
    [140474] = { name = "Adherent of the Abyss", c = 2,
        { item = 161479, count = 1326, outof = 2345 }, -- Nazjatar Blood Serpent
        where = { [942] = { 46.5, 36.1 }, [1182] = { 59.4, 54.2 } },
    },
    [141143] = { name = "Sister Absinthe", c = 4,
        { item = 163573, count = 5, outof = 92777 }, -- Goldenmane
        where = { [942] = { 61.4, 57 } },
    },
    [141286] = { name = "Poacher Zane", c = 4,
        { item = 163573, count = 3, outof = 84786 }, -- Goldenmane
        where = { [942] = { 34.4, 67.4 } },
    },
    [142423] = { name = "Overseer Krix", c = 2,
        { item = 163646, count = 11676, outof = 175730 }, -- Lil' Donkey
        where = { [14] = { 27, 56.4, 33, 36.4 } },
    },
    [142437] = { name = "Skullripper", c = 2,
        { item = 163645, count = 11580, outof = 186189 }, -- Skullripper
        where = { [14] = { 56.8, 45 } },
    },
    [142692] = { name = "Nimar the Slayer", c = 4,
        { item = 163706, count = 11420, outof = 205547 }, -- Witherbark Direwing
        where = { [14] = { 67.4, 60.8 } },
    },
    [142709] = { name = "Beastrider Kama", c = 4,
        { item = 163644, count = 12619, outof = 222413 }, -- Swift Albino Raptor
        where = { [14] = { 65.4, 70.4 } },
        route = { [14] = { { 65.4, 70.4, 66.6, 66.8 } } },
    },
    [142739] = { name = "Knight-Captain Aldrin", c = 4,
        { item = 163578, count = 7720, outof = 115848 }, -- Broken Highland Mustang
        where = { [14] = { 48.8, 40.2 } },
    },
    [142741] = { name = "Doomrider Helgrim", c = 4,
        { item = 163579, count = 7825, outof = 115070 }, -- Highland Mustang
        where = { [14] = { 53.2, 57.4 } },
    },
    [144796] = { name = "High Tinker Mekkatorque", c = 1,
        { item = 166518, count = -2, outof = 9957 }, -- G.M.O.D.
    },
    [147701] = { name = "Moxo the Beheader", c = 4,
        { item = 166434, count = 1569, outof = 29976 }, -- Umber Nightsaber
        where = { [62] = { 64.2, 20 } },
    },
    [148037] = { name = "Athil Dewfire", c = 4,
        { item = 166803, count = 3981, outof = 80017 }, -- Umber Nightsaber
        where = { [62] = { 41.4, 74.8 } },
    },
    [148787] = { name = "Alash'anir", c = 2,
        { item = 166432, count = 4684, outof = 84132 }, -- Ashenvale Chimaera
        where = { [62] = { 56.6, 30.8 } },
    },
    [148790] = { name = "Frightened Kodo", c = 4,
        { item = 166433, unknown = true }, -- Frightened Kodo
        where = { [62] = { 38.4, 65.4 } },
        route = { [62] = { { 38.8, 50, 41.2, 54.2, 39, 57, 38.4, 65.4, 43.8, 67.4 } } },
    },
    [149652] = { name = "Agathe Wyrmwood", c = 4,
        { item = 166438, count = 1102, outof = 25073 }, -- Blackpaw
        where = { [62] = { 49.4, 24.8 } },
    },
    [149655] = { name = "Croz Bloodrage", c = 4,
        { item = 166437, count = 1176, outof = 26887 }, -- Kaldorei Nightsaber
        where = { [62] = { 50.4, 32.4 } },
    },
    [149660] = { name = "Blackpaw", c = 4,
        { item = 166428, count = 4801, outof = 80790 }, -- Blackpaw
        where = { [62] = { 49.4, 24.8 } },
    },
    [149663] = { name = "Shadowclaw", c = 4,
        { item = 166435, count = 4329, outof = 84727 }, -- Kaldorei Nightsaber
        where = { [62] = { 39.4, 33.2 } },
    },
    [150397] = { name = "King Mechagon", c = 1,
        { item = 168830, count = 519, outof = 8960 }, -- Aerial Unit R-21/X
    },
    [151329] = { name = "Warden Skoldus", c = 1,
        { item = 188700, count = 44, outof = 18298 }, -- Colossal Umbrahide Mawrat
    },
    [151331] = { name = "Cellblock Sentinel", c = 1,
        { item = 188700, count = 38, outof = 20108 }, -- Colossal Umbrahide Mawrat
    },
    [151934] = { name = "Arachnoid Harvester", c = 2,
        { item = 168823, count = 286, outof = 88278 }, -- Rusty Mechanocrawler
        where = { [1462] = { 52.4, 40.8 } },
    },
    [152182] = { name = "Rustfeather", c = 4,
        { item = 168370, count = 405, outof = 82093 }, -- Junkheap Drifter
        where = { [1462] = { 65.4, 78.4 } },
    },
    [152290] = { name = "Soundless", c = 4,
        { item = 169163, count = 220, outof = 14985 }, -- Silent Glider
        where = { [1355] = { 54.8, 50.6 } },
        route = { [1355] = { { 58, 42, 53.8, 42.2, 54.8, 50.6, 60, 47.8, 64.4, 51.6, 62.4, 59.4 } } },
    },
    [152995] = { name = "Warden of Souls", c = 1,
        { item = 188700, count = 6, outof = 8966 }, -- Colossal Umbrahide Mawrat
    },
    [153011] = { name = "Binder Baritas", c = 1,
        { item = 188700, count = 13, outof = 9284 }, -- Colossal Umbrahide Mawrat
    },
    [153165] = { name = "Custodian Thonar", c = 1,
        { item = 188700, count = 44, outof = 18655 }, -- Colossal Umbrahide Mawrat
    },
    [153174] = { name = "Watchers of Death", c = 1,
        { item = 188700, count = 14, outof = 9302 }, -- Colossal Umbrahide Mawrat
    },
    [153382] = { name = "Maw of the Maw", c = 1,
        { item = 188700, count = 12, outof = 9215 }, -- Colossal Umbrahide Mawrat
    },
    [153451] = { name = "Kosarus the Fallen", c = 1,
        { item = 188700, count = 23, outof = 17036 }, -- Colossal Umbrahide Mawrat
    },
    [154342] = { name = "Arachnoid Harvester", c = 2,
        { item = 168823, count = 23, outof = 7063 }, -- Rusty Mechanocrawler
        where = { [1462] = { 53.2, 40.6 } },
    },
    [155250] = { name = "Decayspeaker", c = 1,
        { item = 188700, count = 18, outof = 14187 }, -- Colossal Umbrahide Mawrat
    },
    [155251] = { name = "Elder Longbranch", c = 1,
        { item = 188700, count = 15, outof = 13357 }, -- Colossal Umbrahide Mawrat
    },
    [155945] = { name = "Gherus the Chained", c = 1,
        { item = 188700, count = 24, outof = 18265 }, -- Colossal Umbrahide Mawrat
    },
    [156015] = { name = "Writhing Soulmass", c = 1,
        { item = 188700, count = 8, outof = 16757 }, -- Colossal Umbrahide Mawrat
    },
    [156239] = { name = "Dark Ascended Corrus", c = 1,
        { item = 188700, count = 16, outof = 13934 }, -- Colossal Umbrahide Mawrat
    },
    [157122] = { name = "Patrician Cromwell", c = 1,
        { item = 188700, count = 26, outof = 16473 }, -- Colossal Umbrahide Mawrat
    },
    [157134] = { name = "Ishak of the Four Winds", c = 2,
        { item = 174641, count = 456, outof = 15287 }, -- Drake of the Four Winds
        where = { [1527] = { 73.8, 83.4 } },
    },
    [157146] = { name = "Rotfeaster", c = 4,
        { item = 174753, count = 349, outof = 10398 }, -- Waste Marauder
        where = { [1527] = { 68, 31.6 } },
    },
    [157153] = { name = "Ha-Li", c = 2,
        { item = 173887, count = 427, outof = 14737 }, -- Clutch of Ha-Li
        where = { [1530] = { 31.6, 41.8 } },
        route = { [1530] = { { 31.6, 41.8, 36.4, 33.8 } } },
    },
    [157160] = { name = "Houndlord Ren", c = 4,
        { item = 174841, count = 329, outof = 11093 }, -- Ren's Stalwart Hound
        where = { [1530] = { 11.4, 30.4 } },
        route = { [1530] = { { 9.4, 34.4, 11.4, 30.4, 12.4, 27.2 } } },
    },
    [157162] = { name = "Rei Lun", c = 2,
        { item = 174649, unknown = true }, -- Rajani Warserpent
        where = { [1530] = { 21.8, 12.8 } },
    },
    [157309] = { name = "Violet Mistake", c = 4,
        { item = 182079, count = 352, outof = 9476 }, -- Hulking Deathroc
        where = { [1536] = { 58.4, 74.2 } },
    },
    [157466] = { name = "Anh-De the Loyal", c = 4,
        { item = 174840, count = 325, outof = 11846 }, -- Xinlao
        where = { [1530] = { 34.2, 68 } },
    },
    [159190] = { name = "Synod", c = 1,
        { item = 188700, count = 27, outof = 16489 }, -- Colossal Umbrahide Mawrat
    },
    [159755] = { name = "The Grand Malleare", c = 1,
        { item = 188700, count = 26, outof = 15195 }, -- Colossal Umbrahide Mawrat
    },
    [160708] = { name = "Mail Muncher", c = 4,
        { item = 174653, count = 792, outof = 792 }, -- Mail Muncher
        where = { [2403] = { 58.8, 51, 39.4, 79.4, 39.6, 48.6, 52.4, 76.8 }, [2404] = { 54.6, 56.2, 61.8, 74, 62.2, 31.6, 75.6, 64.2, 49.6, 86.4 } },
        route = { [2403] = { { 58.8, 51, 67.6, 39.6 }, { 36.8, 75.2, 39.4, 79.4, 38.2, 86 } } },
    },
    [160821] = { name = "Worldedge Gorger", c = 2,
        { item = 182589, unknown = true }, -- Loyal Gorger
        where = { [1525] = { 38.8, 72 } },
    },
    [162147] = { name = "Corpse Eater", c = 4,
        { item = 174769, count = 337, outof = 27603 }, -- Malevolent Drone
        where = { [1527] = { 30.4, 49.4 } },
    },
    [162586] = { name = "Tahonta", c = 4,
        { item = 182075, count = 299, outof = 48174 }, -- Bonehoof Tauralus
        where = { [1536] = { 44.2, 51.4 } },
    },
    [162689] = { name = "Surgeon Stitchflesh", c = 1,
        { item = 133543, count = 1, outof = 1684 }, -- Infinite Timereaver
    },
    [162690] = { name = "Nerissa Heartless", c = 4,
        { item = 182084, count = 531, outof = 24361 }, -- Gorespine
        where = { [1536] = { 66, 35.2 } },
    },
    [162693] = { name = "Nalthor the Rimebinder", c = 1,
        { item = 133543, count = 1, outof = 1960 }, -- Infinite Timereaver
    },
    [162741] = { name = "Gieger", c = 4,
        { item = 182080, count = 1033, outof = 44499 }, -- Predatory Plagueroc
        where = { [1536] = { 31.4, 35.6 } },
    },
    [162819] = { name = "Warbringer Mal'Korak", c = 2,
        { item = 182085, count = 442, outof = 18182 }, -- Blisterback Bloodtusk
        where = { [1536] = { 33.6, 80 } },
    },
    [162853] = { name = "Unbreakable Urtz", c = 1,
        { item = 184062, count = 476, outof = 95244 }, -- Battle-Bound Warhound
        where = { [1536] = { 50.6, 47.6 } },
    },
    [162872] = { name = "Xantuth the Blighted", c = 1,
        { item = 184062, count = 178, outof = 34769 }, -- Battle-Bound Warhound
        where = { [1536] = { 50.2, 47.4 } },
    },
    [162873] = { name = "Azmogal", c = 1,
        { item = 184062, count = 91, outof = 16176 }, -- Battle-Bound Warhound
        where = { [1536] = { 50.2, 47.4 } },
    },
    [162874] = { name = "Ti'or", c = 1,
        { item = 184062, count = 190, outof = 46322 }, -- Battle-Bound Warhound
        where = { [1536] = { 50.2, 47.2 } },
    },
    [162875] = { name = "Devmorta", c = 1,
        { item = 184062, count = 84, outof = 23872 }, -- Battle-Bound Warhound
        where = { [1536] = { 50.2, 47.6 } },
    },
    [162880] = { name = "Mistress Dyrax", c = 1,
        { item = 184062, count = 157, outof = 40176 }, -- Battle-Bound Warhound
        where = { [1536] = { 50.4, 47.4 } },
    },
    [163042] = { name = "Ivory Cloud Serpent", c = 4,
        { item = 174752, unknown = true }, -- Ivory Cloud Serpent
        where = { [1530] = { 27.4, 53.2 } },
        route = { [1530] = { { 4, 60.8, 5.4, 56.6, 6.4, 53, 7.2, 49.2, 8.6, 46.2, 9.8, 44.2, 12.2, 39.2, 13.4, 36.4, 14.4, 32, 14.6, 26.8, 15.2, 24.2, 20.2, 20, 24.2, 18.8, 29.6, 18.2, 34.4, 17.6, 37.4, 18.4, 42.2, 21.4, 44.8, 21.8, 48.8, 23.4, 54.4, 18.6, 58.2, 21, 61.6, 26.8, 63.2, 29.8, 68.8, 31.4, 72.6, 34.6, 76.6, 38.8, 78.4, 39.8, 79.8, 43.2, 81.6, 49.4, 81.2, 54.6, 77, 56.8, 70.2, 56.4, 67.2, 59, 62.8, 59.2, 57.8, 60, 51, 63.8, 47.6, 66.8, 43.8, 67.6, 42.4, 66, 41.6, 59.6, 41.4, 55.2, 41.6, 50.2, 41, 46.6, 38.8, 42.2, 31.8, 45.8, 30.4, 47, 27.4, 53.2, 28.2, 57, 26.4, 58.2, 25.2, 62.2, 23.4, 64.6, 22, 67.6, 20, 70.6, 15, 73.4, 12.6, 69.2, 11.2, 66, 7, 65, loop = true } } },
    },
    [164107] = { name = "Gormtamer Tizo", c = 4,
        { item = 180725, count = 2610, outof = 4061 }, -- Spinemaw Gladechewer
        where = { [1565] = { 28.4, 55 } },
    },
    [164112] = { name = "Humon'gozz", c = 4,
        { item = 182650, unknown = true }, -- Arboreal Gulper
    },
    [165290] = { name = "Harika the Horrid", c = 4,
        { item = 180461, count = 1437, outof = 67516 }, -- Horrid Dredwing
        where = { [1525] = { 46, 78.4 } },
    },
    [166521] = { name = "Famu the Infinite", c = 2,
        { item = 180582, count = 371, outof = 42414 }, -- Endmire Flyer
        where = { [1525] = { 62.6, 47 } },
    },
    [166679] = { name = "Hopecrusher", c = 2,
        { item = 180581, count = 418, outof = 28081 }, -- Hopecrusher Gargon
        where = { [1525] = { 51.4, 52.4 } },
    },
    [167749] = { name = "Doomwalker", c = 1,
        { item = 43959, count = 12, outof = 14545 }, -- Grand Black War Mammoth
        { item = 44083, count = 12, outof = 14545 }, -- Grand Black War Mammoth
        { item = 186469, count = 1678, outof = 14545 }, -- Illidari Doomhawk
        { item = 208572, count = 206, outof = 14545 }, -- Azure Worldchiller
        where = { [71] = { 63.1, 49.8 } },
    },
    [168135] = { name = "Night Mare", c = 2,
        { item = 180728, count = 1693, outof = 1977 }, -- Swift Gloomhoof
        where = { [1565] = { 60.6, 56.6 } },
        route = { [1565] = { { 58.8, 49.2, 61.6, 49.6, 62.6, 53.2, 62.6, 56.2, 60.6, 56.6, loop = true } } },
    },
    [168147] = { name = "Sabriel the Bonecleaver", c = 2,
        { item = 181815, count = 186, outof = 39026 }, -- Armored Bonehoof Tauralus
        where = { [1536] = { 50.4, 48 } },
    },
    [168647] = { name = "Valfir the Unrelenting", c = 2,
        { item = 180730, count = 270, outof = 25273 }, -- Wild Glimmerfur Prowler
        where = { [1565] = { 29.8, 55.6 } },
    },
    [169859] = { name = "Observer Zelgar", c = 1,
        { item = 188700, count = 31, outof = 16004 }, -- Colossal Umbrahide Mawrat
    },
    [170418] = { name = "Goxul the Devourer", c = 1,
        { item = 188700, count = 21, outof = 15973 }, -- Colossal Umbrahide Mawrat
    },
    [170439] = { name = "Sundancer", c = 4,
        { item = 180773, unknown = true }, -- Sundancer
        where = { [1533] = { 59.4, 95 } },
        route = { [1533] = { { 59.4, 95, 61.4, 91.2, 62, 86.2, 62.6, 83.4, 61.6, 80.2 } } },
    },
    [170548] = { name = "Sundancer", c = 4,
        { item = 180773, unknown = true }, -- Sundancer
        where = { [1533] = { 60, 93.4 } },
    },
    [171422] = { name = "Arch-Suppressor Laguas", c = 1,
        { item = 188700, count = 22, outof = 16490 }, -- Colossal Umbrahide Mawrat
    },
    [171767] = { name = "Shizgher", c = 1,
        { item = 180727, unknown = true }, -- Shimmermist Runner
        where = { [1565] = { 26.4, 59 } },
    },
    [173468] = { name = "Dead Blanchy", c = 4,
        { item = 182614, unknown = true }, -- Sinrunner Blanchy
        where = { [1525] = { 62.8, 43.6 } },
    },
    [174062] = { name = "Skadi the Ruthless", c = 2,
        { item = 44151, count = 85, outof = 13717 }, -- Blue Proto-Drake
        where = { [118] = { 57.4, 56 } },
    },
    [174861] = { name = "Gorged Shadehound", c = 1,
        { item = 184167, count = 365, outof = 19842 }, -- Mawsworn Soulhunter
        where = { [1543] = { 53.6, 78.8 } },
    },
    [175726] = { name = "Skyja", c = 1,
        { item = 186656, count = 57, outof = 12716 }, -- Sanctum Gloomcharger
    },
    [176578] = { name = "Vault Sentinel", c = 1,
        { item = 188700, count = 67, outof = 5931 }, -- Colossal Umbrahide Mawrat
    },
    [177269] = { name = "So'leah", c = 1,
        { item = 186638, count = 102, outof = 4704 }, -- Cartel Master's Gearglider
    },
    [177330] = { name = "Promathiz", c = 1,
        { item = 185973, count = 6, outof = 3678 }, -- Hand of Bahmethra
        where = { [1543] = { 22.6, 35.4, 22.8, 52.4, 28, 48.4, 30.4, 14, 33.4, 42.2, 39.6, 60.8, 44.4, 46.8 } },
    },
    [177972] = { name = "Malleus Grakizz", c = 1,
        { item = 185973, count = 2, outof = 3241 }, -- Hand of Bahmethra
        where = { [1543] = { 22.6, 35.4, 22.8, 52.4, 28, 48.4, 30.4, 14.2, 34, 42, 39.4, 61, 44.2, 46.6 } },
    },
    [177981] = { name = "Versya the Damned", c = 1,
        { item = 185973, count = 2, outof = 3521 }, -- Hand of Bahmethra
        where = { [1543] = { 22.4, 35.4, 22.8, 52.2, 28, 48.4, 30.4, 14, 34, 42, 39.8, 60.6, 44.4, 46.8 } },
    },
    [178883] = { name = "Sentinel Shakorzeth", c = 1,
        { item = 185973, count = 3, outof = 2812 }, -- Hand of Bahmethra
        where = { [1543] = { 22.4, 35.4, 22.4, 52.4, 28.2, 48.4, 30, 14.4, 34, 42, 39.6, 60.8, 44.4, 46.8 } },
    },
    [178898] = { name = "Golmak The Monstrosity", c = 1,
        { item = 185973, count = 1, outof = 2922 }, -- Hand of Bahmethra
        where = { [1543] = { 22.4, 52, 39.4, 61, 22.2, 35.4, 30.2, 14.4 } },
        route = { [1543] = { { 22.4, 52, 28.2, 48.4, 34.2, 42, 44.2, 46.4, 44.8, 47.6 } } },
    },
    [178899] = { name = "Manifestation of Pain", c = 1,
        { item = 185973, count = 1, outof = 3253 }, -- Hand of Bahmethra
        where = { [1543] = { 22.6, 35.4, 22.8, 52.4, 28, 48.2, 30.4, 14.2, 34, 42, 39.4, 60.8, 44.4, 46.8 } },
    },
    [179433] = { name = "Vault Aegis", c = 1,
        { item = 188700, count = 87, outof = 6156 }, -- Colossal Umbrahide Mawrat
    },
    [179460] = { name = "Fallen Charger", c = 2,
        { item = 186659, count = 919, outof = 8635 }, -- Fallen Charger
        where = { [1543] = { 32.2, 44.8, 56.6, 86 } },
        route = { [1543] = { { 18, 48.6, 20.4, 45.8, 21.6, 41.6, 28.6, 35.4, 31.8, 40, 32.2, 44.8, 35.4, 48, 35, 51.2, 34.6, 53.8, 34.6, 57.6, 29.4, 61.8, 27, 66, 36.4, 62.4, 43.8, 63.4, 47.2, 60.6, 46.6, 58.4, 45.2, 53.8, 38.8, 46.4, 42.4, 44.6, 43.8, 41.6, 41, 39.2, 38.6, 35.2, 33, 36.6, 34.6, 33.4, 36.4, 30.4, 35.4, 27.4, 31.4, 28, 31.8, 25.8, 30.4, 20.4, 27.4, 17, 29.4, 15.6 } } },
    },
    [179472] = { name = "Konthrogz the Obliterator", c = 2,
        { item = 187183, count = 1479, outof = 62470 }, -- Rampaging Mauler
        where = { [1961] = { 44.4, 29.4, 44.6, 43, 47.6, 35.6, 51.4, 41.4, 52.4, 21.6, 56.2, 67, 58.8, 51.4 } },
    },
    [179526] = { name = "Troz'igal the Oppressor", c = 1,
        { item = 188700, count = 86, outof = 6311 }, -- Colossal Umbrahide Mawrat
    },
    [179684] = { name = "Malbog", c = 4,
        { item = 186645, count = 847, outof = 42345 }, -- Crimson Shardhide
        where = { [1961] = { 44.6, 29.6 } },
    },
    [179985] = { name = "Stygian Stonecrusher", c = 4,
        { item = 186479, unknown = true }, -- Mastercraft Gravewing
        where = { [1961] = { 45.6, 79.4 } },
    },
    [180013] = { name = "Escaped Wilderling", c = 4,
        { item = 186492, unknown = true }, -- Summer Wilderling
        where = { [1961] = { 33.6, 39.4 } },
    },
    [180032] = { name = "Wild Worldcracker", c = 4,
        { item = 186483, unknown = true }, -- Forsworn Aquilon
        where = { [1961] = { 47, 35.6 } },
    },
    [180042] = { name = "Fleshwing", c = 4,
        { item = 186489, unknown = true }, -- Lord of the Corpseflies
        where = { [1961] = { 59.4, 43.2 } },
    },
    [180160] = { name = "Reliwik the Defiant", c = 4,
        { item = 186652, count = 475, outof = 18177 }, -- Garnet Razorwing
        where = { [1961] = { 56.2, 66.8 } },
    },
    [180978] = { name = "Hirukon", c = 2,
        { item = 187676, count = 620, outof = 13501 }, -- Deepstar Aurelid
        where = { [1970] = { 51.4, 74.2 } },
    },
    [180990] = { name = "The Jailer", c = 1,
        { item = 190768, count = 87, outof = 9354 }, -- Zereth Overseer
    },
    [182120] = { name = "Rhuv, Gorger of Ruin", c = 1,
        { item = 190765, count = 311, outof = 1232 }, -- Colossal Plaguespew Mawrat
        where = { [1970] = { 63.2, 26 } },
    },
    [193209] = { name = "Zenet Avis", c = 4,
        { item = 198825, unknown = true }, -- Zenet Hatchling
        where = { [2023] = { 31.4, 63.8 } },
    },
    [195353] = { name = "Breezebiter", c = 1,
        { item = 201440, count = 140, outof = 7002 }, -- Liberated Slyvern
        where = { [2024] = { 28.4, 46 } },
    },
    [200537] = { name = "Gahz'raxes", c = 2,
        { item = 192772, count = 128, outof = 17143 }, -- Ancient Salamanther
        where = { [2151] = { 28, 38.6 } },
    },
    [200579] = { name = "Ishyra", c = 2,
        { item = 192772, count = 139, outof = 21677 }, -- Ancient Salamanther
        where = { [2151] = { 41, 14 } },
    },
    [200584] = { name = "Vraken the Hunter", c = 2,
        { item = 192772, count = 171, outof = 24645 }, -- Ancient Salamanther
        where = { [2151] = { 58.4, 48.6 } },
    },
    [200600] = { name = "Reisa the Drowned", c = 2,
        { item = 192772, count = 129, outof = 20283 }, -- Ancient Salamanther
        where = { [2151] = { 47.4, 20.4 } },
    },
    [200610] = { name = "Duzalgor", c = 2,
        { item = 192772, count = 62, outof = 9071 }, -- Ancient Salamanther
    },
    [200681] = { name = "Bonesifter Marwak", c = 2,
        { item = 192772, count = 123, outof = 15936 }, -- Ancient Salamanther
        where = { [2151] = { 43.4, 60.4 } },
    },
    [200717] = { name = "Galakhad", c = 2,
        { item = 192772, count = 114, outof = 16896 }, -- Ancient Salamanther
        where = { [2151] = { 44.8, 79.2 } },
    },
    [200721] = { name = "Grugoth the Hullcrusher", c = 2,
        { item = 192772, count = 151, outof = 20662 }, -- Ancient Salamanther
        where = { [2151] = { 44, 89.8 } },
    },
    [200885] = { name = "Lady Shaz'ra", c = 2,
        { item = 192772, count = 168, outof = 24280 }, -- Ancient Salamanther
        where = { [2151] = { 59.8, 58.8 } },
    },
    [200904] = { name = "Veltrax", c = 2,
        { item = 192772, count = 149, outof = 21095 }, -- Ancient Salamanther
        where = { [2151] = { 72.4, 67.4 } },
    },
    [200911] = { name = "Volcanakk", c = 2,
        { item = 192772, count = 52, outof = 6926 }, -- Ancient Salamanther
        where = { [1978] = { 70, 10.4 } },
    },
    [200956] = { name = "Ookbeard", c = 2,
        { item = 192772, count = 102, outof = 11821 }, -- Ancient Salamanther
        where = { [2151] = { 36.8, 12.2 } },
    },
    [200960] = { name = "Warden Entrix", c = 2,
        { item = 192772, count = 107, outof = 14015 }, -- Ancient Salamanther
    },
    [200978] = { name = "Pyrachniss", c = 2,
        { item = 192772, count = 99, outof = 13647 }, -- Ancient Salamanther
    },
    [201013] = { name = "Wyrmslayer Angvardi", c = 2,
        { item = 192772, count = 88, outof = 11253 }, -- Ancient Salamanther
        where = { [2151] = { 62.4, 32.6 } },
    },
    [201181] = { name = "Mad-Eye Carrey", c = 2,
        { item = 192772, count = 98, outof = 11269 }, -- Ancient Salamanther
        where = { [2151] = { 68.4, 45.6 } },
    },
    [203625] = { name = "Karokta", c = 2,
        { item = 205203, count = 217, outof = 26503 }, -- Cobalt Shalewing
        where = { [2133] = { 42.2, 65.4 } },
    },
    [204931] = { name = "Fyrakk", c = 1,
        { item = 210061, count = 68, outof = 10867 }, -- Anu'relos, Flame's Guidance
    },
    [205490] = { name = "Treasure Goblin", c = 2,
        { item = 76755, count = 454, outof = 51886 }, -- Tyrael's Charger
        { item = 246264, count = 1, outof = 60 }, -- Inarius' Charger
        where = { [1] = { 44, 19.4 }, [84] = { 40.2, 43.4, 50.4, 86, 54.6, 54, 63.6, 71, 65.4, 38.8 }, [85] = { 44, 48.8, 50, 78.8, 52.4, 36.4, 68.4, 41.4 }, [2022] = { 67, 38, 70.2, 44.4, 74.2, 36.2, 74.2, 44, 76.8, 47.4 }, [2023] = { 45.8, 65.4, 51, 55.8, 52, 49.4, 52.2, 44, 54.6, 62.6 }, [2024] = { 64, 43.6, 67.4, 30, 71.2, 35.4 }, [2025] = { 52.6, 65, 58.4, 77.6, 57.6, 84.4 }, [2112] = { 26.4, 57.6, 46, 29.6, 46, 65.2, 55, 79, 57.2, 19.4, 79.2, 44.8 }, [2248] = { 54.4, 54.8 } },
        route = { [1] = { { 43.4, 22.2, 45.6, 20.2, 44, 19.4, 44.4, 17, loop = true } } },
    },
    [207802] = { name = "Beledar's Spawn", c = 2,
        { item = 223315, count = 1346, outof = 24386 }, -- Beledar's Spawn
        where = { [2215] = { 25.8, 57.4, 32.8, 39.4, 37, 72, 37.4, 46, 38.4, 24.4, 42.8, 31.4, 45.2, 25.4, 47, 55, 48.8, 32, 50.4, 48.4, 51.2, 70.4, 54.8, 36.8, 58, 48.8, 58.4, 28.8, 60.4, 18.4, 61.4, 7.6, 62.4, 38.8, 68.2, 30.4, 71.8, 65, 72.6, 41.4 } },
    },
    [208029] = { name = "Doomshadow", c = 1,
        { item = 212645, count = 151, outof = 21877 }, -- Clayscale Hornstrider
        where = { [2024] = { 27.8, 46 } },
    },
    [215146] = { name = "Dr. Boom", c = 1,
        { item = 212522, count = 1887, outof = 62481 }, -- Compass Rose
        where = { [84] = { 34.2, 19.4 }, [2112] = { 62, 67.4 } },
    },
    [218370] = { name = "Queen Ansurek", c = 1,
        { item = 224147, count = 101, outof = 11314 }, -- Sureki Skyrazor
        { item = 224151, count = 78, outof = 543 }, -- Ascendant Skyrazor
    },
    [219281] = { name = "Alunira", c = 4,
        { item = 223270, count = 410, outof = 636 }, -- Alunira
        where = { [2248] = { 23, 58.6 } },
    },
    [220285] = { name = "Lurker of the Deeps", c = 2,
        { item = 223501, count = 131, outof = 2190 }, -- Ol' Mole Rufus
        where = { [2214] = { 56.8, 76.6, 60.8, 76.4 } },
    },
    [231075] = { name = "Chrome King Gallywix", c = 1,
        { item = 235626, count = 20, outof = 152 }, -- The Big G
        { item = 236960, count = 56, outof = 6944 }, -- Prototype A.S.M.R.
    },
    [231229] = { name = "Korgoth the Hungerer", c = 2,
        { item = 246159, unknown = true }, -- Translocated Gorger
        where = { [2371] = { 71.4, 27.4 } },
    },
    [231310] = { name = "Darkfuse Precipitant", c = 2,
        { item = 229955, count = 58, outof = 1345 }, -- Darkfuse Spy-Eye
        where = { [2346] = { 41.4, 92 } },
    },
    [232195] = { name = "Urmag", c = 4,
        { item = 246067, count = 655, outof = 8175 }, -- Pearlescent Krolusk
        where = { [2371] = { 70, 49.8 } },
    },
    [233824] = { name = "Dimensius", c = 1,
        { item = 243061, count = 15, outof = 87 }, -- Unbound Star-Eater
    },
    [234621] = { name = "Gallagio Garbage", c = 2,
        { item = 229953, count = 1181, outof = 74480 }, -- Salvaged Goblin Gazillionaire's Flying Machine
        where = { [2346] = { 32, 21.4, 36.2, 45.2, 38.4, 81, 50.6, 63.6, 52.4, 83.4, 67.4, 29.4, 69.4, 76.4 } },
    },
    [234845] = { name = "Sthaarbs", c = 2,
        { item = 246160, count = 347, outof = 5070 }, -- Sthaarbs's Last Lunch
        where = { [2371] = { 74, 32.4 } },
    },
    [234970] = { name = "Miasmawrath", c = 2,
        { item = 246159, unknown = true }, -- Translocated Gorger
        where = { [2371] = { 50.6, 54 } },
    },
    [235087] = { name = "The Harvester", c = 2,
        { item = 246159, unknown = true }, -- Translocated Gorger
        where = { [2371] = { 49.6, 64.2 } },
    },
    [235104] = { name = "The Wallbreaker", c = 2,
        { item = 246159, unknown = true }, -- Translocated Gorger
        where = { [2472] = { 28.4, 73.4 } },
        route = { [2472] = { { 28.8, 76.6, 28.4, 73.4, 30.6, 71.2 } } },
    },
    [237991] = { name = "Void-Scarred Gryphon", c = 1,
        { item = 235700, count = 714, outof = 715 }, -- Void-Scarred Gryphon
        where = { [2404] = { 67.4, 72.6 } },
    },
    [238079] = { name = "Void-Forged Stallion", c = 4,
        { item = 235705, count = 884, outof = 886 }, -- Void-Forged Stallion
        where = { [2404] = { 63.2, 36.4 } },
    },
    [238145] = { name = "Void-Scarred Wyvern Matriarch", c = 1,
        { item = 235707, count = 278, outof = 279 }, -- Void-Scarred Windrider
        where = { [2403] = { 48.8, 55 } },
    },
    [238498] = { name = "Territorial Voidscythe", c = 4,
        { item = 257085, count = 4, outof = 4235 }, -- Augmented Stormray
        { item = 260635, count = 9, outof = 4235 }, -- Sanguine Harrower
        where = { [2405] = { 34, 82 } },
    },
    [238836] = { name = "Void-Scarred Wolf", c = 4,
        { item = 235706, count = 76, outof = 76 }, -- Void-Scarred Pack Mother
        where = { [2403] = { 60.8, 54.8 } },
    },
    [239581] = { name = "Nesting Swarmite", c = 4,
        { item = 223265, count = 282, outof = 282 }, -- Nesting Swarmite
        where = { [2403] = { 40.4, 78.4, 47.4, 75.6, 50.4, 46.2, 57.6, 60.8, 68.4, 48.8 }, [2404] = { 62.6, 31.6, 56.6, 50.2, 74.6, 62.4, 65.4, 75.2, 52.4, 77.2 } },
        route = { [2404] = { { 61.2, 38.4, 63.2, 35.4, 62.6, 31.6 } } },
    },
    [240129] = { name = "Overfester Hydra", c = 4,
        { item = 257147, count = 14, outof = 6684 }, -- Cobalt Dragonhawk
        { item = 257156, count = 6, outof = 6684 }, -- Cerulean Hawkstrider
        where = { [2395] = { 54.6, 60.2 } },
    },
    [241443] = { name = "Tremora", c = 4,
        { item = 257085, count = 5, outof = 3268 }, -- Augmented Stormray
        { item = 260635, count = 6, outof = 3268 }, -- Sanguine Harrower
        where = { [2405] = { 36, 83.2 } },
    },
    [242023] = { name = "Necrohexxer Raz'ka", c = 4,
        { item = 257152, count = 10, outof = 8153 }, -- Amani Sharptalon
        { item = 257200, count = 6, outof = 8153 }, -- Witherbark Pango
        where = { [2437] = { 34.2, 33 } },
    },
    [242024] = { name = "The Snapping Scourge", c = 4,
        { item = 257152, count = 14, outof = 7380 }, -- Amani Sharptalon
        { item = 257200, count = 6, outof = 7380 }, -- Witherbark Pango
        where = { [2437] = { 51.6, 18.4 } },
    },
    [242025] = { name = "Skullcrusher Harak", c = 4,
        { item = 257152, count = 8, outof = 6409 }, -- Amani Sharptalon
        { item = 257200, count = 9, outof = 6409 }, -- Witherbark Pango
        where = { [2437] = { 51.4, 72.6 } },
    },
    [242026] = { name = "Elder Oaktalon", c = 4,
        { item = 257152, count = 5, outof = 4575 }, -- Amani Sharptalon
        { item = 257200, count = 11, outof = 4575 }, -- Witherbark Pango
        where = { [2437] = { 33.4, 89 } },
    },
    [242027] = { name = "Depthborn Eelamental", c = 4,
        { item = 257152, count = 7, outof = 7759 }, -- Amani Sharptalon
        { item = 257200, count = 13, outof = 7759 }, -- Witherbark Pango
        where = { [2437] = { 47.6, 20.6 } },
    },
    [242028] = { name = "Lightwood Borer", c = 4,
        { item = 257152, count = 9, outof = 8116 }, -- Amani Sharptalon
        { item = 257200, count = 8, outof = 8116 }, -- Witherbark Pango
        where = { [2437] = { 28.8, 24.2 } },
    },
    [242031] = { name = "Spinefrill", c = 4,
        { item = 257152, count = 8, outof = 7591 }, -- Amani Sharptalon
        { item = 257200, count = 12, outof = 7591 }, -- Witherbark Pango
        where = { [2437] = { 30.4, 44.4 } },
    },
    [242032] = { name = "Oophaga", c = 4,
        { item = 257152, count = 8, outof = 9311 }, -- Amani Sharptalon
        { item = 257200, count = 7, outof = 9311 }, -- Witherbark Pango
        where = { [2437] = { 46.4, 51.2 } },
    },
    [242033] = { name = "Tiny Vermin", c = 4,
        { item = 257152, count = 11, outof = 8467 }, -- Amani Sharptalon
        { item = 257200, count = 10, outof = 8467 }, -- Witherbark Pango
        where = { [2437] = { 47.8, 34.2 } },
    },
    [242034] = { name = "Voidtouched Crustacean", c = 4,
        { item = 257152, count = 9, outof = 5250 }, -- Amani Sharptalon
        { item = 257200, count = 7, outof = 5250 }, -- Witherbark Pango
        where = { [2437] = { 21.4, 70.6 } },
    },
    [242035] = { name = "The Devouring Invader", c = 4,
        { item = 257152, count = 6, outof = 7750 }, -- Amani Sharptalon
        { item = 257200, count = 6, outof = 7750 }, -- Witherbark Pango
        where = { [2437] = { 39.4, 20.4 } },
    },
    [242086] = { name = "Aln'sharan", c = 4,
        { item = 256424, unknown = true }, -- Echo of Aln'sharan
    },
    [244272] = { name = "Sundereth the Caller", c = 4,
        { item = 257085, count = 12, outof = 6020 }, -- Augmented Stormray
        { item = 260635, count = 11, outof = 6020 }, -- Sanguine Harrower
        where = { [2405] = { 29.4, 50 } },
    },
    [245044] = { name = "Nightbrood", c = 4,
        { item = 257085, count = 3, outof = 5327 }, -- Augmented Stormray
        { item = 260635, count = 2, outof = 5327 }, -- Sanguine Harrower
        where = { [2405] = { 40.2, 41.4 } },
    },
    [245182] = { name = "Eruundi", c = 4,
        { item = 257085, count = 6, outof = 2512 }, -- Augmented Stormray
        { item = 260635, count = 2, outof = 2512 }, -- Sanguine Harrower
        where = { [2444] = { 41.2, 89.6 } },
    },
    [245691] = { name = "The Decaying Diamondback", c = 2,
        { item = 257152, count = 8, outof = 4572 }, -- Amani Sharptalon
        { item = 257200, count = 1, outof = 4572 }, -- Witherbark Pango
        where = { [2437] = { 46.4, 43.5 } },
    },
    [245692] = { name = "Ash'an the Empowered", c = 2,
        { item = 257152, count = 11, outof = 6168 }, -- Amani Sharptalon
        { item = 257200, count = 6, outof = 6168 }, -- Witherbark Pango
        where = { [2437] = { 45.2, 41.6 } },
    },
    [245975] = { name = "Mrrlokk", c = 4,
        { item = 257152, count = 7, outof = 6959 }, -- Amani Sharptalon
        { item = 257200, count = 9, outof = 6959 }, -- Witherbark Pango
        where = { [2437] = { 50.8, 65.2 } },
    },
    [246332] = { name = "Warden of Weeds", c = 4,
        { item = 257147, count = 13, outof = 10122 }, -- Cobalt Dragonhawk
        { item = 257156, count = 12, outof = 10122 }, -- Cerulean Hawkstrider
        where = { [2395] = { 51.6, 74.6 } },
    },
    [246633] = { name = "Harried Hawkstrider", c = 4,
        { item = 257147, count = 20, outof = 10414 }, -- Cobalt Dragonhawk
        { item = 257156, count = 27, outof = 10414 }, -- Cerulean Hawkstrider
        where = { [2395] = { 45.2, 79 } },
    },
    [247976] = { name = "Poacher Rav'ik", c = 4,
        { item = 257152, count = 8, outof = 8473 }, -- Amani Sharptalon
        { item = 257200, count = 12, outof = 8473 }, -- Witherbark Pango
        where = { [2437] = { 39, 50 } },
    },
    [248068] = { name = "Nullspiral", c = 2,
        { item = 257085, count = 10, outof = 5783 }, -- Augmented Stormray
        { item = 260635, count = 6, outof = 5783 }, -- Sanguine Harrower
        where = { [2405] = { 29.4, 67.4 } },
    },
    [248459] = { name = "The Many-Broken", c = 2,
        { item = 257085, count = 4, outof = 4183 }, -- Augmented Stormray
        { item = 260635, count = 4, outof = 4183 }, -- Sanguine Harrower
        where = { [2405] = { 28.4, 70.2 } },
    },
    [248700] = { name = "Abysslick", c = 2,
        { item = 257085, count = 3, outof = 2717 }, -- Augmented Stormray
        { item = 260635, count = 4, outof = 2717 }, -- Sanguine Harrower
        where = { [2405] = { 28.2, 66 } },
    },
    [248741] = { name = "Rhazul", c = 4,
        { item = 246735, count = 7, outof = 6391 }, -- Rootstalker Grimlynx
        { item = 252012, count = 9, outof = 6391 }, -- Vibrant Petalwing
        where = { [2413] = { 51.2, 45.2 } },
    },
    [248791] = { name = "Voidseer Orivane", c = 2,
        { item = 257085, count = 11, outof = 7256 }, -- Augmented Stormray
        { item = 260635, count = 10, outof = 7256 }, -- Sanguine Harrower
        where = { [2405] = { 29.6, 67.6 } },
    },
    [248823] = { name = "Blackcore", c = 2,
        { item = 257085, count = 5, outof = 3478 }, -- Augmented Stormray
        { item = 260635, count = 11, outof = 3478 }, -- Sanguine Harrower
        where = { [2405] = { 24.8, 67.8 } },
    },
    [249844] = { name = "Chironex", c = 4,
        { item = 246735, count = 7, outof = 5714 }, -- Rootstalker Grimlynx
        { item = 252012, count = 5, outof = 5714 }, -- Vibrant Petalwing
        where = { [2413] = { 69.4, 40.4 } },
    },
    [249849] = { name = "Ha'kalawe", c = 4,
        { item = 246735, count = 8, outof = 6653 }, -- Rootstalker Grimlynx
        { item = 252012, count = 13, outof = 6653 }, -- Vibrant Petalwing
        where = { [2413] = { 69, 60.8 } },
    },
    [249902] = { name = "Tallcap the Truthspreader", c = 4,
        { item = 246735, count = 9, outof = 4488 }, -- Rootstalker Grimlynx
        { item = 252012, count = 8, outof = 4488 }, -- Vibrant Petalwing
        where = { [2413] = { 72.4, 69 } },
    },
    [249962] = { name = "Queen Lashtongue", c = 4,
        { item = 246735, count = 12, outof = 6790 }, -- Rootstalker Grimlynx
        { item = 252012, count = 10, outof = 6790 }, -- Vibrant Petalwing
        where = { [2413] = { 59.8, 46.8 } },
    },
    [249997] = { name = "Chlorokyll", c = 4,
        { item = 246735, count = 5, outof = 4997 }, -- Rootstalker Grimlynx
        { item = 252012, count = 14, outof = 4997 }, -- Vibrant Petalwing
        where = { [2413] = { 64.4, 47.6 } },
    },
    [250086] = { name = "Stumpy", c = 2,
        { item = 246735, count = 9, outof = 5560 }, -- Rootstalker Grimlynx
        { item = 252012, count = 10, outof = 5560 }, -- Vibrant Petalwing
        where = { [2413] = { 65.4, 32.4 } },
    },
    [250180] = { name = "Serrasa", c = 4,
        { item = 246735, count = 11, outof = 5494 }, -- Rootstalker Grimlynx
        { item = 252012, count = 2, outof = 5494 }, -- Vibrant Petalwing
        where = { [2413] = { 56.6, 33 } },
    },
    [250226] = { name = "Mindrot", c = 4,
        { item = 246735, count = 7, outof = 5634 }, -- Rootstalker Grimlynx
        { item = 252012, count = 9, outof = 5634 }, -- Vibrant Petalwing
        where = { [2413] = { 46, 30.4 } },
    },
    [250231] = { name = "Dracaena", c = 4,
        { item = 246735, count = 7, outof = 5862 }, -- Rootstalker Grimlynx
        { item = 252012, count = 11, outof = 5862 }, -- Vibrant Petalwing
        where = { [2413] = { 40.4, 43.2 } },
    },
    [250246] = { name = "Treetop", c = 4,
        { item = 246735, count = 8, outof = 5193 }, -- Rootstalker Grimlynx
        { item = 252012, count = 11, outof = 5193 }, -- Vibrant Petalwing
        where = { [2413] = { 36.6, 75 } },
    },
    [250317] = { name = "Oro'ohna", c = 2,
        { item = 246735, count = 15, outof = 5390 }, -- Rootstalker Grimlynx
        { item = 252012, count = 13, outof = 5390 }, -- Vibrant Petalwing
        where = { [2413] = { 28.4, 81.4 } },
    },
    [250321] = { name = "Pterrock", c = 4,
        { item = 246735, count = 5, outof = 4191 }, -- Rootstalker Grimlynx
        { item = 252012, count = 5, outof = 4191 }, -- Vibrant Petalwing
        where = { [2413] = { 27.2, 70.4 } },
    },
    [250347] = { name = "Ahl'ua'huhi", c = 4,
        { item = 246735, count = 7, outof = 5881 }, -- Rootstalker Grimlynx
        { item = 252012, count = 6, outof = 5881 }, -- Vibrant Petalwing
        where = { [2413] = { 39.8, 60.4 } },
    },
    [250358] = { name = "Annulus the Worldshaker", c = 2,
        { item = 246735, count = 5, outof = 2508 }, -- Rootstalker Grimlynx
        { item = 252012, count = 6, outof = 2508 }, -- Vibrant Petalwing
        where = { [2413] = { 43.6, 16.8 } },
    },
    [250582] = { name = "Bloated Snapdragon", c = 4,
        { item = 257147, count = 15, outof = 10870 }, -- Cobalt Dragonhawk
        { item = 257156, count = 15, outof = 10870 }, -- Cerulean Hawkstrider
        where = { [2395] = { 37.6, 64.2 } },
    },
    [250683] = { name = "Coralfang", c = 4,
        { item = 257147, count = 16, outof = 7571 }, -- Cobalt Dragonhawk
        { item = 257156, count = 7, outof = 7571 }, -- Cerulean Hawkstrider
        where = { [2395] = { 36.4, 36.4 } },
    },
    [250719] = { name = "Cre'van", c = 4,
        { item = 257147, count = 11, outof = 7837 }, -- Cobalt Dragonhawk
        { item = 257156, count = 5, outof = 7837 }, -- Cerulean Hawkstrider
        where = { [2395] = { 63.6, 49.2 } },
    },
    [250754] = { name = "Lady Liminus", c = 4,
        { item = 257147, count = 14, outof = 8792 }, -- Cobalt Dragonhawk
        { item = 257156, count = 16, outof = 8792 }, -- Cerulean Hawkstrider
        where = { [2395] = { 36.4, 77.2 } },
    },
    [250780] = { name = "Waverly", c = 4,
        { item = 257147, count = 14, outof = 7345 }, -- Cobalt Dragonhawk
        { item = 257156, count = 6, outof = 7345 }, -- Cerulean Hawkstrider
        where = { [2395] = { 34.8, 21 } },
    },
    [250806] = { name = "Lost Guardian", c = 4,
        { item = 257147, count = 15, outof = 8867 }, -- Cobalt Dragonhawk
        { item = 257156, count = 13, outof = 8867 }, -- Cerulean Hawkstrider
        where = { [2395] = { 59.2, 79.2 } },
    },
    [250826] = { name = "Banuran", c = 4,
        { item = 257147, count = 18, outof = 8743 }, -- Cobalt Dragonhawk
        { item = 257156, count = 13, outof = 8743 }, -- Cerulean Hawkstrider
        where = { [2395] = { 56.4, 77.4 } },
    },
    [250841] = { name = "Bad Zed", c = 4,
        { item = 257147, count = 8, outof = 5976 }, -- Cobalt Dragonhawk
        { item = 257156, count = 9, outof = 5976 }, -- Cerulean Hawkstrider
        where = { [2395] = { 48.4, 88 } },
    },
    [250876] = { name = "Terrinor", c = 4,
        { item = 257147, count = 6, outof = 6602 }, -- Cobalt Dragonhawk
        { item = 257156, count = 13, outof = 6602 }, -- Cerulean Hawkstrider
        where = { [2395] = { 40.2, 85.2 } },
    },
    [255087] = { name = "Malformed Leviathan", c = 2,
        { item = 276803, count = 1, outof = 183 }, -- Ruby Writhe
        where = { [2512] = { 46.9, 62.2 } },
    },
    [255088] = { name = "Looming Mutagenitor", c = 2,
        { item = 276549, count = 3, outof = 2084 }, -- Topaz Skyfang
        { item = 276803, count = 3, outof = 2084 }, -- Ruby Writhe
        where = { [2512] = { 26.6, 64.8, 26.6, 68.4 } },
    },
    [255302] = { name = "Duskburn", c = 4,
        { item = 257147, count = 12, outof = 9799 }, -- Cobalt Dragonhawk
        { item = 257156, count = 17, outof = 9799 }, -- Cerulean Hawkstrider
        where = { [2395] = { 42.4, 68.8 } },
    },
    [255329] = { name = "Malfunctioning Construct", c = 4,
        { item = 257147, count = 18, outof = 11018 }, -- Cobalt Dragonhawk
        { item = 257156, count = 18, outof = 11018 }, -- Cerulean Hawkstrider
        where = { [2395] = { 51.4, 45.8 } },
    },
    [255348] = { name = "Dame Bloodshed", c = 4,
        { item = 257147, count = 16, outof = 11940 }, -- Cobalt Dragonhawk
        { item = 257156, count = 16, outof = 11940 }, -- Cerulean Hawkstrider
        where = { [2395] = { 44.6, 38.2 } },
    },
    [255927] = { name = "Venom Lancer Ori'kassi", c = 2,
        { item = 276549, count = 4, outof = 3454 }, -- Topaz Skyfang
        { item = 276803, count = 6, outof = 3454 }, -- Ruby Writhe
        where = { [2512] = { 67.4, 77.8 } },
    },
    [256631] = { name = "Big Mon", c = 4,
        { item = 276549, count = 4, outof = 4442 }, -- Topaz Skyfang
        { item = 276803, count = 5, outof = 4442 }, -- Ruby Writhe
        where = { [2512] = { 70, 63.6 } },
    },
    [256770] = { name = "Bilemaw the Gluttonous", c = 4,
        { item = 257085, count = 9, outof = 5857 }, -- Augmented Stormray
        { item = 260635, count = 3, outof = 5857 }, -- Sanguine Harrower
        where = { [2405] = { 35.4, 50 } },
    },
    [256808] = { name = "Ravengerus", c = 2,
        { item = 257085, count = 4, outof = 2105 }, -- Augmented Stormray
        { item = 260635, count = 2, outof = 2105 }, -- Sanguine Harrower
        where = { [2405] = { 48.4, 53.4 } },
    },
    [256821] = { name = "Far'thana the Mad", c = 2,
        { item = 257085, count = 11, outof = 6064 }, -- Augmented Stormray
        { item = 260635, count = 6, outof = 6064 }, -- Sanguine Harrower
        where = { [2405] = { 53.8, 62.4 } },
    },
    [256922] = { name = "Screammaxa the Matriarch", c = 4,
        { item = 257085, count = 3, outof = 2227 }, -- Augmented Stormray
        { item = 260635, count = 3, outof = 2227 }, -- Sanguine Harrower
        where = { [2405] = { 43.6, 51.4 } },
    },
    [256923] = { name = "Bane of the Vilebloods", c = 4,
        { item = 257085, count = 11, outof = 4437 }, -- Augmented Stormray
        { item = 260635, count = 6, outof = 4437 }, -- Sanguine Harrower
        where = { [2405] = { 47, 80.6 } },
    },
    [256924] = { name = "Aeonelle Blackstar", c = 4,
        { item = 257085, count = 4, outof = 5191 }, -- Augmented Stormray
        { item = 260635, count = 8, outof = 5191 }, -- Sanguine Harrower
        where = { [2405] = { 39.2, 64 } },
    },
    [256925] = { name = "Lotus Darkblossom", c = 4,
        { item = 257085, count = 3, outof = 2275 }, -- Augmented Stormray
        { item = 260635, count = 9, outof = 2275 }, -- Sanguine Harrower
        where = { [2405] = { 37.8, 71.6 } },
    },
    [256926] = { name = "Queen o' War", c = 4,
        { item = 257085, count = 6, outof = 4678 }, -- Augmented Stormray
        { item = 260635, count = 11, outof = 4678 }, -- Sanguine Harrower
        where = { [2405] = { 55.6, 79.4 } },
    },
    [257027] = { name = "Rakshur the Bonegrinder", c = 4,
        { item = 257085, count = 7, outof = 3427 }, -- Augmented Stormray
        { item = 260635, count = 8, outof = 3427 }, -- Sanguine Harrower
        where = { [2444] = { 46.4, 40.8 } },
    },
    [257199] = { name = "Hardin Steellock", c = 2,
        { item = 257085, count = 3, outof = 1427 }, -- Augmented Stormray
        { item = 260635, count = 2, outof = 1427 }, -- Sanguine Harrower
        where = { [2444] = { 28.4, 56.8 } },
    },
    [257231] = { name = "Gar'chak Skullcleave", c = 2,
        { item = 257085, count = 6, outof = 1368 }, -- Augmented Stormray
        { item = 260635, count = 5, outof = 1368 }, -- Sanguine Harrower
        where = { [2444] = { 69.6, 77.2 } },
    },
    [257863] = { name = "Vassti, the Exalted Broodmother", c = 2,
        { item = 276549, count = 1, outof = 2527 }, -- Topaz Skyfang
        { item = 276803, count = 3, outof = 2527 }, -- Ruby Writhe
        where = { [2512] = { 45.2, 28.4 } },
    },
    [257906] = { name = "Coin-Eye Skully", c = 4,
        { item = 276549, count = 1, outof = 1817 }, -- Topaz Skyfang
        { item = 276803, count = 4, outof = 1817 }, -- Ruby Writhe
        where = { [2512] = { 58.4, 66.4 } },
    },
    [258916] = { name = "Garsecg", c = 4,
        { item = 276549, count = 7, outof = 5944 }, -- Topaz Skyfang
        { item = 276803, count = 5, outof = 5944 }, -- Ruby Writhe
        where = { [2512] = { 69.6, 45 } },
    },
    [258920] = { name = "Nar'zira", c = 4,
        { item = 276549, count = 3, outof = 6327 }, -- Topaz Skyfang
        { item = 276803, count = 4, outof = 6327 }, -- Ruby Writhe
        where = { [2512] = { 52, 44.8 } },
    },
    [258928] = { name = "Ral'kala", c = 4,
        { item = 275659, unknown = true }, -- Hexflame Reaver
        where = { [2512] = { 29.4, 65, 52.9, 42.2, 68.4, 45 } },
    },
    [261109] = { name = "Sss'alik", c = 4,
        { item = 276549, count = 4, outof = 4610 }, -- Topaz Skyfang
        { item = 276803, count = 5, outof = 4610 }, -- Ruby Writhe
        where = { [2512] = { 58, 40 } },
    },
    [261142] = { name = "Destra", c = 4,
        { item = 276549, count = 2, outof = 1740 }, -- Topaz Skyfang
        { item = 276803, count = 3, outof = 1740 }, -- Ruby Writhe
        where = { [2512] = { 51.9, 32.3 } },
    },
    [263456] = { name = "Szarith the Fanged", c = 4,
        { item = 276549, count = 1, outof = 1230 }, -- Topaz Skyfang
    },
    [265237] = { name = "Lockjaw", c = 4,
        { item = 276549, count = 1, outof = 2650 }, -- Topaz Skyfang
        { item = 276803, count = 1, outof = 2650 }, -- Ruby Writhe
        where = { [2512] = { 31.6, 56.8 } },
    },
    [265262] = { name = "Hisstara", c = 4,
        { item = 276549, count = 5, outof = 2831 }, -- Topaz Skyfang
        { item = 276803, count = 3, outof = 2831 }, -- Ruby Writhe
        where = { [2512] = { 43.8, 50.8 } },
    },
    [268049] = { name = "Siltmouth", c = 4,
        { item = 276549, count = 1, outof = 3279 }, -- Topaz Skyfang
        { item = 276803, count = 2, outof = 3279 }, -- Ruby Writhe
        where = { [2512] = { 50.2, 69.4 } },
    },
    [268090] = { name = "Kari'zah the Forgotten", c = 4,
        { item = 276549, count = 4, outof = 1893 }, -- Topaz Skyfang
        { item = 276803, count = 1, outof = 1893 }, -- Ruby Writhe
        where = { [2512] = { 24.6, 73.4 } },
    },
}
