-- RocketMount | Data/MountReputation.lua
-- GENERATED by tools/coletar_reputacao.py on 2026-09-25 -- do not edit by hand.
--
-- mount id -> the reputation its purchase asks for, read from Wowhead's item tooltips (which
-- record the VENDOR's condition too, like the Gilded Prowler's "Requires Exalted with The
-- Ascended.") and checked against MCL. Same shape as MCL's GuideRepData, so the addon reads
-- both the same way; MCL's own record wins when it has one.
local ADDON, ns = ...

ns.MountReputation = {
    [153] = { factionId = 978, factionName = "Kurenai", levelName = "Exalted" }, -- Cobalt War Talbuk
    [154] = { factionId = 978, factionName = "Kurenai", levelName = "Exalted" }, -- White War Talbuk
    [155] = { factionId = 978, factionName = "Kurenai", levelName = "Exalted" }, -- Silver War Talbuk
    [156] = { factionId = 978, factionName = "Kurenai", levelName = "Exalted" }, -- Tan War Talbuk
    [170] = { factionId = 978, factionName = "Kurenai", levelName = "Exalted" }, -- Cobalt Riding Talbuk
    [172] = { factionId = 978, factionName = "Kurenai", levelName = "Exalted" }, -- Silver Riding Talbuk
    [173] = { factionId = 978, factionName = "Kurenai", levelName = "Exalted" }, -- Tan Riding Talbuk
    [174] = { factionId = 978, factionName = "Kurenai", levelName = "Exalted" }, -- White Riding Talbuk
    [176] = { factionId = 1031, factionName = "Sha'tari Skyguard", levelName = "Exalted" }, -- Green Riding Nether Ray
    [177] = { factionId = 1031, factionName = "Sha'tari Skyguard", levelName = "Exalted" }, -- Red Riding Nether Ray
    [178] = { factionId = 1031, factionName = "Sha'tari Skyguard", levelName = "Exalted" }, -- Purple Riding Nether Ray
    [179] = { factionId = 1031, factionName = "Sha'tari Skyguard", levelName = "Exalted" }, -- Silver Riding Nether Ray
    [180] = { factionId = 1031, factionName = "Sha'tari Skyguard", levelName = "Exalted" }, -- Blue Riding Nether Ray
    [203] = { factionId = 942, factionName = "Cenarion Expedition", levelName = "Exalted" }, -- Cenarion War Hippogryph
    [249] = { factionId = 1091, factionName = "The Wyrmrest Accord", levelName = "Exalted" }, -- Red Drake
    [258] = { factionId = 1119, factionName = "The Sons of Hodir", levelName = "Revered" }, -- Ice Mammoth
    [259] = { factionId = 1119, factionName = "The Sons of Hodir", levelName = "Revered" }, -- Ice Mammoth
    [288] = { factionId = 1119, factionName = "The Sons of Hodir", levelName = "Exalted" }, -- Grand Ice Mammoth
    [289] = { factionId = 1119, factionName = "The Sons of Hodir", levelName = "Exalted" }, -- Grand Ice Mammoth
    [318] = { factionId = 930, factionName = "Exodar", levelName = "Exalted" }, -- Great Red Elekk
    [319] = { factionId = 69, factionName = "Darnassus", levelName = "Exalted" }, -- Swift Moonsaber
    [320] = { factionId = 911, factionName = "Silvermoon City", levelName = "Exalted" }, -- Swift Red Hawkstrider
    [321] = { factionId = 72, factionName = "Stormwind", levelName = "Exalted" }, -- Swift Gray Steed
    [322] = { factionId = 81, factionName = "Thunder Bluff", levelName = "Exalted" }, -- Great Golden Kodo
    [323] = { factionId = 54, factionName = "Gnomeregan", levelName = "Exalted" }, -- Turbostrider
    [324] = { factionId = 47, factionName = "Ironforge", levelName = "Exalted" }, -- Swift Violet Ram
    [325] = { factionId = 530, factionName = "Darkspear Trolls", levelName = "Exalted" }, -- Swift Purple Raptor
    [326] = { factionId = 68, factionName = "Undercity", levelName = "Exalted" }, -- White Skeletal Warhorse
    [327] = { factionId = 76, factionName = "Orgrimmar", levelName = "Exalted" }, -- Swift Burgundy Wolf
    [329] = { factionId = 1094, factionName = "The Silver Covenant", levelName = "Exalted" }, -- Silver Covenant Hippogryph
    [330] = { factionId = 1124, factionName = "The Sunreavers", levelName = "Exalted" }, -- Sunreaver Dragonhawk
    [331] = { factionId = 1094, factionName = "The Silver Covenant", levelName = "Exalted" }, -- Quel'dorei Steed
    [332] = { factionId = 1124, factionName = "The Sunreavers", levelName = "Exalted" }, -- Sunreaver Hawkstrider
    [394] = { factionId = 1178, factionName = "Hellscream's Reach", levelName = "Exalted" }, -- Drake of the West Wind
    [398] = { factionId = 1173, factionName = "Ramkahen", levelName = "Exalted" }, -- Brown Riding Camel
    [399] = { factionId = 1173, factionName = "Ramkahen", levelName = "Exalted" }, -- Tan Riding Camel
    [405] = { factionId = 1177, factionName = "Baradin's Wardens", levelName = "Exalted" }, -- Spectral Steed
    [406] = { factionId = 1178, factionName = "Hellscream's Reach", levelName = "Exalted" }, -- Spectral Wolf
    [448] = { factionId = 1271, factionName = "Order of the Cloud Serpent", levelName = "Exalted" }, -- Jade Cloud Serpent
    [449] = { factionId = 1302, factionName = "The Anglers", levelName = "Exalted" }, -- Azure Water Strider
    [463] = { factionId = 1337, factionName = "The Klaxxi", levelName = "Exalted" }, -- Amber Scorpion
    [464] = { factionId = 1271, factionName = "Order of the Cloud Serpent", levelName = "Exalted" }, -- Azure Cloud Serpent
    [465] = { factionId = 1271, factionName = "Order of the Cloud Serpent", levelName = "Exalted" }, -- Golden Cloud Serpent
    [475] = { factionId = 1492, factionName = "Emperor Shaohao", levelName = "Exalted" }, -- Heavenly Golden Cloud Serpent
    [479] = { factionId = 1269, factionName = "Golden Lotus", levelName = "Exalted" }, -- Azure Riding Crane
    [480] = { factionId = 1269, factionName = "Golden Lotus", levelName = "Exalted" }, -- Golden Riding Crane
    [481] = { factionId = 1269, factionName = "Golden Lotus", levelName = "Exalted" }, -- Regal Riding Crane
    [488] = { factionId = 1358, factionName = "Nat Pagle", friendship = true, levelName = "Best Friend" }, -- Crimson Water Strider
    [504] = { factionId = 1341, factionName = "The August Celestials", levelName = "Exalted" }, -- Thundering August Cloud Serpent
    [505] = { factionId = 1270, factionName = "Shado-Pan", levelName = "Exalted" }, -- Green Shado-Pan Riding Tiger
    [506] = { factionId = 1270, factionName = "Shado-Pan", levelName = "Exalted" }, -- Blue Shado-Pan Riding Tiger
    [507] = { factionId = 1270, factionName = "Shado-Pan", levelName = "Exalted" }, -- Red Shado-Pan Riding Tiger
    [508] = { factionId = 1272, factionName = "The Tillers", levelName = "Exalted" }, -- Brown Riding Goat
    [509] = { factionId = 1345, factionName = "The Lorewalkers", levelName = "Exalted" }, -- Red Flying Cloud
    [510] = { factionId = 1272, factionName = "The Tillers", levelName = "Exalted" }, -- White Riding Goat
    [511] = { factionId = 1272, factionName = "The Tillers", levelName = "Exalted" }, -- Black Riding Goat
    [526] = { factionId = 1376, factionName = "Operation: Shieldwall", levelName = "Exalted" }, -- Grand Armored Gryphon
    [527] = { factionId = 1375, factionName = "Dominance Offensive", levelName = "Exalted" }, -- Grand Armored Wyvern
    [545] = { factionId = 1387, factionName = "Kirin Tor Offensive", levelName = "Exalted" }, -- Golden Primal Direhorn
    [546] = { factionId = 1388, factionName = "Sunreaver Onslaught", levelName = "Exalted" }, -- Crimson Primal Direhorn
    [617] = { factionId = 1731, factionName = "Council of Exarchs", levelName = "Exalted" }, -- Dusty Rockhide
    [618] = { factionId = 1710, factionName = "Sha'tari Defense", levelName = "Exalted" }, -- Armored Irontusk
    [624] = { factionId = 1850, factionName = "The Saberstalkers", levelName = "Honored" }, -- Wild Goretusk
    [625] = { factionId = 1711, factionName = "Steamwheedle Preservation Society", levelName = "Exalted" }, -- Domesticated Razorback
    [635] = { factionId = 1515, factionName = "Arakkoa Outcasts", levelName = "Exalted" }, -- Shadowmane Charger
    [638] = { factionId = 1681, factionName = "Vol'jin's Spear", levelName = "Exalted" }, -- Breezestrider Stallion
    [639] = { factionId = 1682, factionName = "Wrynn's Vanguard", levelName = "Exalted" }, -- Pale Thorngrazer
    [645] = { factionId = 1708, factionName = "Laughing Skull Orcs", levelName = "Exalted" }, -- Ironside Warwolf
    [648] = { factionId = 1445, factionName = "Frostwolf Orcs", levelName = "Exalted" }, -- Swift Frostwolf
    [753] = { factionId = 1849, factionName = "Order of the Awakened", levelName = "Friendly" }, -- Corrupted Dreadwing
    [765] = { factionId = 1850, factionName = "The Saberstalkers", levelName = "Exalted" }, -- Bristling Hellboar
    [768] = { factionId = 1847, factionName = "Hand of the Prophet", levelName = "Exalted" }, -- Deathtusk Felboar
    [800] = { factionId = 1975, factionName = "Conjurer Margoss", friendship = true, levelName = "Best Friend" }, -- Brinedeep Bottom-Feeder
    [877] = { factionId = 2018, factionName = "Talon's Vengeance", levelName = "Exalted" }, -- Ivory Hawkstrider
    [881] = { factionId = 1859, factionName = "The Nightfallen", levelName = "Exalted" }, -- Arcanist's Manasaber
    [926] = { factionId = 2158, factionName = "Voldunai", levelName = "Exalted" }, -- Alabaster Hyena
    [932] = { factionId = 2165, factionName = "Army of the Light", levelName = "Exalted" }, -- Lightforged Warframe
    [939] = { factionId = 2170, factionName = "Argussian Reach", levelName = "Exalted" }, -- Sable Ruinstrider
    [958] = { factionId = 2103, factionName = "Zandalari Empire", levelName = "Exalted" }, -- Spectral Pterrorwing
    [964] = { factionId = 2170, factionName = "Argussian Reach", levelName = "Exalted" }, -- Amethyst Ruinstrider
    [965] = { factionId = 2170, factionName = "Argussian Reach", levelName = "Exalted" }, -- Cerulean Ruinstrider
    [966] = { factionId = 2170, factionName = "Argussian Reach", levelName = "Exalted" }, -- Beryl Ruinstrider
    [967] = { factionId = 2170, factionName = "Argussian Reach", levelName = "Exalted" }, -- Umber Ruinstrider
    [968] = { factionId = 2170, factionName = "Argussian Reach", levelName = "Exalted" }, -- Russet Ruinstrider
    [1010] = { factionId = 2160, factionName = "Proudmoore Admiralty", levelName = "Exalted" }, -- Admiralty Stallion
    [1015] = { factionId = 2162, factionName = "Storm's Wake", levelName = "Exalted" }, -- Dapple Gray
    [1016] = { factionId = 2161, factionName = "Order of Embers", levelName = "Exalted" }, -- Smoky Charger
    [1058] = { factionId = 2103, factionName = "Zandalari Empire", levelName = "Exalted" }, -- Cobalt Pterrordax
    [1059] = { factionId = 2156, factionName = "Talanji's Expedition", levelName = "Exalted" }, -- Captured Swampstalker
    [1060] = { factionId = 2158, factionName = "Voldunai", levelName = "Exalted" }, -- Voldunai Dunescraper
    [1061] = { factionId = 2156, factionName = "Talanji's Expedition", levelName = "Exalted" }, -- Expedition Bloodswarmer
    [1062] = { factionId = 2161, factionName = "Order of Embers", levelName = "Exalted" }, -- Dusky Waycrest Gryphon
    [1063] = { factionId = 2162, factionName = "Storm's Wake", levelName = "Exalted" }, -- Stormsong Coastwatcher
    [1064] = { factionId = 2160, factionName = "Proudmoore Admiralty", levelName = "Exalted" }, -- Proudmoore Sea Scout
    [1230] = { factionId = 2373, factionName = "The Unshackled", levelName = "Exalted" }, -- Unshackled Waveray
    [1231] = { factionId = 2400, factionName = "Waveblade Ankoan", levelName = "Exalted" }, -- Ankoan Waveray
    [1254] = { factionId = 2391, factionName = "Rustbolt Resistance", levelName = "Exalted" }, -- Rustbolt Resistor
    [1318] = { factionId = 2417, factionName = "Uldum Accord", levelName = "Exalted" }, -- Wastewander Skyterror
    [1356] = { factionId = 2464, factionName = "Court of Night", levelName = "Revered" }, -- Winterborn Runestag
    [1359] = { factionId = 2463, factionName = "Marasmius", levelName = "Revered" }, -- Enchanted Winterborn Runestag
    [1361] = { factionId = 2465, factionName = "The Wild Hunt", levelName = "Exalted" }, -- Duskflutter Ardenmoth
    [1375] = { factionId = 2410, factionName = "The Undying Army", levelName = "Exalted" }, -- Lurid Bloodtusk
    [1376] = { factionId = 2445, factionName = "The Ember Court", levelName = "Exalted" }, -- Silvertip Dredwing
    [1382] = { factionId = 2439, factionName = "The Avowed", levelName = "Exalted" }, -- Inquisition Gargon
    [1420] = { factionId = 2464, factionName = "Court of Night", levelName = "Revered" }, -- Umbral Scythehorn
    [1421] = { factionId = 2413, factionName = "Court of Harvesters", levelName = "Exalted" }, -- Court Sinrunner
    [1425] = { factionId = 2407, factionName = "The Ascended", levelName = "Exalted" }, -- Gilded Prowler
    [1429] = { factionId = 2463, factionName = "Marasmius", levelName = "Revered" }, -- Vibrant Flutterwing
    [1436] = { factionId = 2470, factionName = "Death's Advance", levelName = "Exalted" }, -- Battle-Hardened Aquilon
    [1450] = { factionId = 2472, factionName = "The Archivists' Codex", friendship = true, level = 6, levelName = "Rank 6" }, -- Soaring Razorwing
    [1486] = { factionId = 2470, factionName = "Death's Advance", levelName = "Exalted" }, -- Winter Wilderling
    [1491] = { factionId = 2470, factionName = "Death's Advance", levelName = "Exalted" }, -- Pale Gravewing
    [1497] = { factionId = 2470, factionName = "Death's Advance", levelName = "Exalted" }, -- Battlefield Swarmer
    [1505] = { factionId = 2470, factionName = "Death's Advance", levelName = "Revered" }, -- Amber Shardhide
    [1522] = { factionId = 2478, factionName = "The Enlightened", levelName = "Exalted" }, -- Heartlight Vombata
    [1529] = { factionId = 2478, factionName = "The Enlightened", levelName = "Revered" }, -- Anointed Protostag
    [1615] = { factionId = 2507, factionName = "Dragonscale Expedition", renown = true, level = 25 }, -- Tamed Skitterfly
    [1616] = { factionId = 2507, factionName = "Dragonscale Expedition", renown = true, level = 25 }, -- Azure Skitterfly
    [1653] = { factionId = 2511, factionName = "Iskaara Tuskarr", renown = true, level = 30 }, -- Brown War Ottuk
    [1655] = { factionId = 2511, factionName = "Iskaara Tuskarr", renown = true, level = 30 }, -- Yellow War Ottuk
    [1657] = { factionId = 2511, factionName = "Iskaara Tuskarr", renown = true, level = 25 }, -- Brown Scouting Ottuk
    [1659] = { factionId = 2511, factionName = "Iskaara Tuskarr", renown = true, level = 25 }, -- Yellow Scouting Ottuk
    [1738] = { factionId = 2564, factionName = "Loamm Niffen", renown = true, level = 18 }, -- Morsel Sniffer
    [1808] = { factionId = 2574, factionName = "Dream Wardens", renown = true, level = 18 }, -- Blossoming Dreamstag
    [1809] = { factionId = 2574, factionName = "Dream Wardens", renown = true, level = 17 }, -- Suntouched Dreamstag
    [1810] = { factionId = 2574, factionName = "Dream Wardens", renown = true, level = 18 }, -- Rekindled Dreamstag
    [1811] = { factionId = 2574, factionName = "Dream Wardens", renown = true, level = 17 }, -- Lunar Dreamstag
    [1816] = { factionId = 2574, factionName = "Dream Wardens", renown = true, level = 18 }, -- Evening Sun Dreamsaber
    [1817] = { factionId = 2574, factionName = "Dream Wardens", renown = true, level = 18 }, -- Morning Flourish Dreamsaber
    [1833] = { factionId = 2574, factionName = "Dream Wardens", renown = true, level = 18 }, -- Springtide Dreamtalon
    [1835] = { factionId = 2574, factionName = "Dream Wardens", renown = true, level = 18 }, -- Snowfluff Dreamtalon
    [2148] = { factionId = 2590, factionName = "Council of Dornogal", renown = true, level = 23 }, -- Smoldering Cinderbee
    [2162] = { factionId = 2594, factionName = "The Assembly of the Deeps", renown = true, level = 23 }, -- Cyan Glowmite
    [2171] = { factionId = 2601, factionName = "The Weaver", friendship = true, levelName = "Conspirator" }, -- Widow's Undercrawler
    [2172] = { factionId = 2605, factionName = "The General", friendship = true, levelName = "Conspirator" }, -- Heritage Undercrawler
    [2174] = { factionId = 2607, factionName = "The Vizier", friendship = true, levelName = "Conspirator" }, -- Royal Court Undercrawler
    [2177] = { factionId = 2600, factionName = "The Severed Threads", renown = true, level = 22 }, -- Aquamarine Swarmite
    [2184] = { factionId = 2600, factionName = "The Severed Threads", renown = true, level = 17 }, -- Ferocious Jawcrawler
    [2191] = { factionId = 2570, factionName = "Hallowfall Arathi", renown = true, level = 23 }, -- Shackled Shadow
    [2193] = { factionId = 2570, factionName = "Hallowfall Arathi", renown = true, level = 21 }, -- Vermillion Imperial Lynx
    [2209] = { factionId = 2594, factionName = "The Assembly of the Deeps", renown = true, level = 19 }, -- Crimson Mudnose
    [2213] = { factionId = 2590, factionName = "Council of Dornogal", renown = true, level = 18 }, -- Shale Ramolith
    [2272] = { factionId = 2673, factionName = "Bilgewater Cartel", levelName = "Exalted" }, -- Crimson Armored Growler
    [2276] = { factionId = 2685, factionName = "Gallagio Loyalty Rewards Club", renown = true, level = 17 }, -- Darkfuse Chompactor
    [2277] = { factionId = 2653, factionName = "The Cartels of Undermine", renown = true, level = 15 }, -- Violet Armored Growler
    [2278] = { factionId = 2685, factionName = "Gallagio Loyalty Rewards Club", renown = true, level = 20 }, -- Flarendo the Furious
    [2279] = { factionId = 2685, factionName = "Gallagio Loyalty Rewards Club", renown = true, level = 8 }, -- Thunderdrum Misfire
    [2280] = { factionId = 2653, factionName = "The Cartels of Undermine", renown = true, level = 19 }, -- The Topskimmer Special
    [2284] = { factionId = 2671, factionName = "Venture Company", levelName = "Exalted" }, -- Ochre Delivery Rocket
    [2286] = { factionId = 2675, factionName = "Blackwater Cartel", levelName = "Exalted" }, -- Blackwater Shredder Deluxe Mk 2
    [2287] = { factionId = 2669, factionName = "Darkfuse Solutions", levelName = "Revered" }, -- Darkfuse Demolisher
    [2294] = { factionId = 2677, factionName = "Steamwheedle Cartel", levelName = "Exalted" }, -- Mean Green Flying Machine
    [2510] = { factionId = 2658, factionName = "The K'aresh Trust", renown = true, level = 19 }, -- Terror of the Wastes
    [2519] = { factionId = 2688, factionName = "Flame's Radiance", renown = true, level = 9 }, -- Radiant Imperial Lynx
    [2556] = { factionId = 2658, factionName = "The K'aresh Trust", renown = true, level = 15 }, -- Ruby Void Creeper
    [2614] = { factionId = 2704, factionName = "Hara'ti", renown = true, level = 16 }, -- Fierce Grimlynx
    [2694] = { factionId = 2696, factionName = "Amani Tribe", renown = true, level = 19 }, -- Amani Windcaller
    [2710] = { factionId = 2704, factionName = "Hara'ti", renown = true, level = 19 }, -- Cerulean Sporeglider
    [2753] = { factionId = 2710, factionName = "Silvermoon Court", renown = true, level = 19 }, -- Fiery Dragonhawk
    [2761] = { factionId = 2710, factionName = "Silvermoon Court", renown = true, level = 17 }, -- Crimson Silvermoon Hawkstrider
    [2776] = { factionId = 2696, factionName = "Amani Tribe", renown = true, level = 17 }, -- Amani Blessed Bear
    [2789] = { factionId = 2699, factionName = "The Singularity", renown = true, level = 17 }, -- Ravenous Shredclaw
    [2791] = { factionId = 2770, factionName = "Slayer's Duellum", levelName = "Exalted" }, -- Prowling Shredclaw
    [2792] = { factionId = 2770, factionName = "Slayer's Duellum", levelName = "Exalted" }, -- Frenzied Shredclaw
    [2807] = { factionId = 2766, factionName = "Brawl'gar Arena", friendship = true, level = 6, levelName = "Rank 6" }, -- Brawlin' Bruno
    [2808] = { factionId = 2766, factionName = "Brawl'gar Arena", friendship = true, level = 8, levelName = "Rank 8" }, -- Ballistic Bronco
    [2828] = { factionId = 2699, factionName = "The Singularity", renown = true, level = 19 }, -- Voidbound Stormray
    [2935] = { factionId = 2792, factionName = "Ritual Sites", renown = true, level = 8 }, -- Void-Touched Hawkstrider
    [3019] = { factionId = 2773, factionName = "Captain Tokka", friendship = true, levelName = "Bloodsworn Crew" }, -- Sea-Dwelling Isle Serpent
    [3054] = { factionId = 2772, factionName = "Zul'jarra's Forces", renown = true, level = 19 }, -- Violet-Backed Skyfang
    [3060] = { factionId = 2772, factionName = "Zul'jarra's Forces", renown = true, level = 17 }, -- Indigo Coiled Horror
}
