-- RocketMount | Data/MountGone.lua
-- GENERATED by tools/coletar_legado.py on 2026-09-28 -- do not edit by hand.
--
-- The mounts that can no longer be obtained, as the game itself marks them: the journal's
-- source text of each of these is the single word "Legacy". From the game's own Mount table.
local ADDON, ns = ...

ns.MountGone = {
    [8] = true, -- White Stallion
    [13] = true, -- Red Wolf
    [15] = true, -- Winter Wolf
    [22] = true, -- Black Ram
    [28] = true, -- Skeletal Horse
    [32] = true, -- Tiger
    [35] = true, -- Ivory Raptor
    [42] = true, -- White Mechanostrider Mod B
    [45] = true, -- Black Nightsaber
    [46] = true, -- Ancient Frostsaber
    [50] = true, -- Red Wolf
    [51] = true, -- Arctic Wolf
    [52] = true, -- Palomino
    [53] = true, -- White Stallion
    [54] = true, -- Mottled Red Raptor
    [56] = true, -- Ivory Raptor
    [62] = true, -- Icy Blue Mechanostrider Mod A
    [63] = true, -- Frost Ram
    [64] = true, -- Black Ram
    [70] = true, -- Riding Kodo
    [73] = true, -- Green Kodo
    [74] = true, -- Teal Kodo
    [111] = true, -- Swift Zulian Tiger
    [116] = true, -- Black Qiraji Battle Tank
    [121] = true, -- Black Qiraji Battle Tank
    [169] = true, -- Swift Nether Drake
    [199] = true, -- Amani War Bear
    [201] = true, -- Brewfest Ram
    [206] = true, -- Merciless Nether Drake
    [207] = true, -- Merciless Nether Drake
    [223] = true, -- Vengeful Nether Drake
    [225] = true, -- Brewfest Riding Kodo
    [238] = true, -- Swift Spectral Gryphon
    [241] = true, -- Brutal Nether Drake
    [251] = true, -- Black Polar Bear
    [263] = true, -- Black Proto-Drake
    [266] = true, -- Plagued Proto-Drake
    [273] = true, -- Grand Caravan Mammoth
    [274] = true, -- Grand Caravan Mammoth
    [308] = true, -- Blue Skeletal Warhorse
    [313] = true, -- Deadly Gladiator's Frost Wyrm
    [317] = true, -- Furious Gladiator's Frost Wyrm
    [340] = true, -- Relentless Gladiator's Frost Wyrm
    [342] = true, -- Swift Horde Wolf
    [343] = true, -- Swift Alliance Steed
    [344] = true, -- Crusader's White Warhorse
    [345] = true, -- Crusader's Black Warhorse
    [358] = true, -- Wrathful Gladiator's Frost Wyrm
    [367] = true, -- Exarch's Elekk
    [424] = true, -- Vicious Gladiator's Twilight Drake
    [428] = true, -- Ruthless Gladiator's Twilight Drake
    [467] = true, -- Cataclysmic Gladiator's Twilight Drake
    [541] = true, -- Malevolent Gladiator's Cloud Serpent
    [562] = true, -- Tyrannical Gladiator's Cloud Serpent
    [563] = true, -- Grievous Gladiator's Cloud Serpent
    [564] = true, -- Prideful Gladiator's Cloud Serpent
    [776] = true, -- Swift Spectral Rylak
    [934] = true, -- Swift Spectral Hippogryph
    [937] = true, -- Black Qiraji War Tank
    [1269] = true, -- Swift Spectral Fathom Ray
    [1270] = true, -- Swift Spectral Magnetocraft
    [1271] = true, -- Swift Spectral Armored Gryphon
    [1272] = true, -- Swift Spectral Pterrordax
    [1607] = true, -- Swift Spectral Drake
    [2595] = true, -- Swift Spectral Dragonhawk
    [2969] = true, -- Swift Spectral Dragonhawk
    [2999] = true, -- Swift Spectral Eagle
}
