-- RocketMount | Data/MountItems.lua
-- GENERATED by tools/coletar_itens.py on 2026-09-23 -- do not edit by hand.
--
-- mount id -> the item that teaches it, for the vendor mounts MCL records without an item.
-- Source: warcraftmounts.com's page per mount, which links the item on Wowhead. The addon
-- uses a line ONLY when the game agrees (`C_MountJournal.GetMountFromItem(item) == mount`).
local ADDON, ns = ...

ns.MountItems = {
    [545] = 206585,
}
