-- RocketMount | Data/MountBosses.lua
-- GENERATED by tools/coletar_chefes.py on 2026-09-28 -- do not edit by hand.
--
-- The boss that drops each mount, from the game's own Adventure Guide tables. `instance` and
-- `bosses` are the game's ids (JournalInstance, JournalEncounter): the names the player reads
-- are asked of the game by id, in the player's language, and the English ones here are what
-- is left when the game does not answer. `difficulties` are the game's difficulty ids; none
-- listed means every difficulty. `also` are other instances the game lists the mount in.
-- `world` is a world boss: the "instance" is the list of an expansion's, with no door.
local ADDON, ns = ...

ns.MountBosses = {
    [69] = { instance = 1292, zone = "Stratholme - Service Entrance", bosses = { { 456, "Lord Aurius Rivendare" } } }, -- Rivendare's Deathcharger
    [168] = { instance = 745, zone = "Karazhan", raid = true, bosses = { { 1553, "Attumen the Huntsman" } } }, -- Fiery Warhorse
    [183] = { instance = 749, zone = "The Eye", raid = true, bosses = { { 1576, "Kael'thas Sunstrider" } } }, -- Ashes of Al'ar
    [185] = { instance = 252, zone = "Sethekk Halls", bosses = { { 542, "Anzu" } }, difficulties = { 2 } }, -- Raven Lord
    [213] = { instance = 249, zone = "Magisters' Terrace", bosses = { { 533, "Kael'thas Sunstrider" } }, difficulties = { 2, 24 } }, -- Swift White Hawkstrider
    [246] = { instance = 756, zone = "The Eye of Eternity", raid = true, bosses = { { 1617, "Malygos" } } }, -- Azure Drake
    [247] = { instance = 756, zone = "The Eye of Eternity", raid = true, bosses = { { 1617, "Malygos" } } }, -- Blue Drake
    [250] = { instance = 755, zone = "The Obsidian Sanctum", raid = true, bosses = { { 1616, "Sartharion" } }, difficulties = { 4 } }, -- Twilight Drake
    [253] = { instance = 755, zone = "The Obsidian Sanctum", raid = true, bosses = { { 1616, "Sartharion" } }, difficulties = { 3 } }, -- Black Drake
    [264] = { instance = 286, zone = "Utgarde Pinnacle", bosses = { { 643, "Skadi the Ruthless" } }, difficulties = { 2, 24 } }, -- Blue Proto-Drake
    [286] = { instance = 753, zone = "Vault of Archavon", raid = true, bosses = { { 1597, "Archavon the Stone Watcher" }, { 1598, "Emalon the Storm Watcher" }, { 1599, "Koralon the Flame Watcher" }, { 1600, "Toravon the Ice Watcher" } } }, -- Grand Black War Mammoth
    [287] = { instance = 753, zone = "Vault of Archavon", raid = true, bosses = { { 1597, "Archavon the Stone Watcher" }, { 1598, "Emalon the Storm Watcher" }, { 1599, "Koralon the Flame Watcher" }, { 1600, "Toravon the Ice Watcher" } } }, -- Grand Black War Mammoth
    [304] = { instance = 759, zone = "Ulduar", raid = true, bosses = { { 1649, "Yogg-Saron" } }, difficulties = { 14, 33 } }, -- Mimiron's Head
    [349] = { instance = 760, zone = "Onyxia's Lair", raid = true, bosses = { { 1651, "Onyxia" } } }, -- Onyxian Drake
    [363] = { instance = 758, zone = "Icecrown Citadel", raid = true, bosses = { { 1636, "The Lich King" } }, difficulties = { 6 } }, -- Invincible
    [395] = { instance = 68, zone = "The Vortex Pinnacle", bosses = { { 115, "Altairus" } }, difficulties = { 1, 2, 3, 4, 8, 24 } }, -- Drake of the North Wind
    [396] = { instance = 74, zone = "Throne of the Four Winds", raid = true, bosses = { { 155, "Al'Akir" } } }, -- Drake of the South Wind
    [397] = { instance = 67, zone = "The Stonecore", bosses = { { 111, "Slabhide" } }, difficulties = { 1, 2, 24 } }, -- Vitreous Stone Drake
    [410] = { instance = 76, zone = "Zul'Gurub", bosses = { { 176, "Bloodlord Mandokir" } } }, -- Armored Razzashi Raptor
    [411] = { instance = 76, zone = "Zul'Gurub", bosses = { { 181, "High Priestess Kilnara" } } }, -- Swift Zulian Panther
    [415] = { instance = 78, zone = "Firelands", raid = true, bosses = { { 198, "Ragnaros" } }, difficulties = { 1, 2, 3, 4, 5, 6, 14, 15, 33 } }, -- Pureblood Fire Hawk
    [425] = { instance = 78, zone = "Firelands", raid = true, bosses = { { 194, "Alysrazor" } }, difficulties = { 3, 4, 5, 6, 14, 15, 33 } }, -- Flametalon of Alysrazor
    [442] = { instance = 187, zone = "Dragon Soul", raid = true, bosses = { { 333, "Madness of Deathwing" } }, difficulties = { 1, 2, 3, 4, 5, 6 } }, -- Blazing Drake
    [444] = { instance = 187, zone = "Dragon Soul", raid = true, bosses = { { 333, "Madness of Deathwing" } }, difficulties = { 5, 6 } }, -- Life-Binder's Handmaiden
    [445] = { instance = 187, zone = "Dragon Soul", raid = true, bosses = { { 331, "Ultraxion" } }, difficulties = { 3, 4, 5, 6 } }, -- Experiment 12-B
    [473] = { instance = 322, zone = "Pandaria", world = true, bosses = { { 691, "Sha of Anger" } } }, -- Heavenly Onyx Cloud Serpent
    [478] = { instance = 317, zone = "Mogu'shan Vaults", raid = true, bosses = { { 726, "Elegon" } }, difficulties = { 3, 4, 5, 6 } }, -- Astral Cloud Serpent
    [515] = { instance = 322, zone = "Pandaria", world = true, bosses = { { 725, "Salyis's Warband" } } }, -- Son of Galleon
    [531] = { instance = 362, zone = "Throne of Thunder", raid = true, bosses = { { 819, "Horridon" } }, difficulties = { 3, 4, 5, 6 } }, -- Spawn of Horridon
    [533] = { instance = 322, zone = "Pandaria", world = true, bosses = { { 826, "Oondasta" } } }, -- Cobalt Primordial Direhorn
    [542] = { instance = 322, zone = "Pandaria", world = true, bosses = { { 814, "Nalak, The Storm Lord" } } }, -- Thundering Cobalt Cloud Serpent
    [543] = { instance = 362, zone = "Throne of Thunder", raid = true, bosses = { { 828, "Ji-Kun" } }, difficulties = { 3, 4, 5, 6 } }, -- Clutch of Ji-Kun
    [559] = { instance = 369, zone = "Siege of Orgrimmar", raid = true, bosses = { { 869, "Garrosh Hellscream" } }, difficulties = { 16 } }, -- Kor'kron Juggernaut
    [613] = { instance = 457, zone = "Blackrock Foundry", raid = true, bosses = { { 959, "Blackhand" } }, difficulties = { 16 } }, -- Ironhoof Destroyer
    [633] = { instance = 786, zone = "The Nighthold", raid = true, bosses = { { 1737, "Gul'dan" } }, difficulties = { 16 } }, -- Hellfire Infernal
    [634] = { instance = 557, zone = "Draenor", world = true, bosses = { { 1262, "Rukhmar" } } }, -- Solar Spirehawk
    [751] = { instance = 669, zone = "Hellfire Citadel", raid = true, bosses = { { 1438, "Archimonde" } }, difficulties = { 16 } }, -- Felsteel Annihilator
    [791] = { instance = 786, zone = "The Nighthold", raid = true, bosses = { { 1737, "Gul'dan" } }, difficulties = { 14, 15, 16 } }, -- Felblaze Infernal
    [875] = { instance = 860, zone = "Return to Karazhan", bosses = { { 1835, "Attumen the Huntsman" } }, difficulties = { 23 } }, -- Midnight
    [899] = { instance = 875, zone = "Tomb of Sargeras", raid = true, bosses = { { 1861, "Mistress Sassz'ine" } } }, -- Abyss Worm
    [954] = { instance = 946, zone = "Antorus, the Burning Throne", raid = true, bosses = { { 2031, "Argus the Unmaker" } }, difficulties = { 16 } }, -- Shackled Ur'zul
    [971] = { instance = 946, zone = "Antorus, the Burning Throne", raid = true, bosses = { { 1987, "Felhounds of Sargeras" } } }, -- Antoran Charhound
    [995] = { instance = 1001, zone = "Freehold", bosses = { { 2095, "Harlan Sweete" } }, difficulties = { 8, 23 } }, -- Sharkbait
    [1040] = { instance = 1041, zone = "Kings' Rest", bosses = { { 2172, "Dazar, The First King" } }, difficulties = { 23 } }, -- Tomb Stalker
    [1053] = { instance = 1022, zone = "The Underrot", bosses = { { 2158, "Unbound Abomination" } }, difficulties = { 8, 23 } }, -- Underrot Crawg
    [1217] = { instance = 1176, zone = "Battle of Dazar'alor", raid = true, bosses = { { 2334, "High Tinker Mekkatorque" }, { 2343, "Lady Jaina Proudmoore" } }, difficulties = { 14, 15, 16, 17 } }, -- G.M.O.D.
    [1219] = { instance = 1176, zone = "Battle of Dazar'alor", raid = true, bosses = { { 2343, "Lady Jaina Proudmoore" } }, difficulties = { 16 } }, -- Glacial Tidestorm
    [1250] = { instance = 1028, zone = "Azeroth", world = true, bosses = { { 2210, "Dunegorger Kraulok" } } }, -- Mollie
    [1252] = { instance = 1178, zone = "Operation: Mechagon", bosses = { { 2355, "HK-8 Aerial Oppression Unit" } }, difficulties = { 23 } }, -- Mechagon Peacekeeper
    [1293] = { instance = 1180, zone = "Ny'alotha, the Waking City", raid = true, bosses = { { 2375, "N'Zoth the Corruptor" } }, difficulties = { 16 } }, -- Ny'alotha Allseer
    [1406] = { instance = 1182, zone = "The Necrotic Wake", bosses = { { 2396, "Nalthor the Rimebinder" } }, difficulties = { 8, 23 } }, -- Marrowfang
    [1471] = { instance = 1193, zone = "Sanctum of Domination", raid = true, bosses = { { 2441, "Sylvanas Windrunner" } }, difficulties = { 16 } }, -- Vengeance
    [1481] = { instance = 1194, zone = "Tazavesh, the Veiled Market", bosses = { { 2455, "So'leah" } } }, -- Cartel Master's Gearglider
    [1500] = { instance = 1193, zone = "Sanctum of Domination", raid = true, bosses = { { 2439, "The Nine" } } }, -- Sanctum Gloomcharger
    [1587] = { instance = 1195, zone = "Sepulcher of the First Ones", raid = true, bosses = { { 2464, "The Jailer" } }, difficulties = { 16 } }, -- Zereth Overseer
    [1818] = { instance = 1207, zone = "Amirdrassil, the Dream's Hope", raid = true, bosses = { { 2519, "Fyrakk the Blazing" } }, difficulties = { 16 } }, -- Anu'relos, Flame's Guidance
    [2204] = { instance = 1210, zone = "Darkflame Cleft", bosses = { { 2561, "The Darkness" } }, difficulties = { 8, 23 } }, -- Wick
    [2219] = { instance = 1273, zone = "Nerub-ar Palace", raid = true, bosses = { { 2602, "Queen Ansurek" } } }, -- Sureki Skyrazor
    [2223] = { instance = 1273, zone = "Nerub-ar Palace", raid = true, bosses = { { 2602, "Queen Ansurek" } }, difficulties = { 16 } }, -- Ascendant Skyrazor
    [2487] = { instance = 1296, zone = "Liberation of Undermine", raid = true, bosses = { { 2646, "Chrome King Gallywix" } }, difficulties = { 16 } }, -- The Big G
    [2507] = { instance = 1296, zone = "Liberation of Undermine", raid = true, bosses = { { 2646, "Chrome King Gallywix" } } }, -- Prototype A.S.M.R.
    [2569] = { instance = 1302, zone = "Manaforge Omega", raid = true, bosses = { { 2691, "Dimensius, the All-Devouring" } }, difficulties = { 16 } }, -- Unbound Star-Eater
    [2607] = { instance = 1308, zone = "March on Quel'Danas", raid = true, bosses = { { 2740, "Midnight Falls" } }, difficulties = { 16 } }, -- Ashes of Belo'ren
    [2805] = { instance = 1299, zone = "Windrunner Spire", bosses = { { 2658, "The Restless Heart" } }, difficulties = { 23 } }, -- Spectral Hawkstrider
    [2817] = { instance = 1300, zone = "Magisters' Terrace", bosses = { { 2662, "Degentrius" } }, difficulties = { 23 } }, -- Lucent Hawkstrider
    [3030] = { instance = 1320, zone = "The Venomous Abyss", raid = true, bosses = { { 2895, "Ula'tek" } }, difficulties = { 16 } }, -- Primeval Skyfriend
}
