-- RocketMount | Data/MountTips.lua
-- GENERATED by tools/gerar_dicas.py on 2026-09-27 from tools/dicas/*.json -- do not edit by hand.
--
-- What players found out about getting a mount, in OUR words: written after reading what
-- they reported (Wowhead's comments, picked by tools/coletar_dicas.py) side by side with
-- the game's own text and other catalogues (tools/dossie_dicas.py). No comment is copied:
-- the facts are nobody's, the sentences are their authors'.
--
-- A tip is not the game speaking. It was true when somebody wrote it down, and the card
-- says so, with `year`. It never decides a mount's place in the list.
--
-- `{item:207026|Dreamsurge Coalescence}` is shown as the item's name in the player's
-- language, asked by id (Tips.lua); what follows the bar shows when the game does not
-- answer. Kinds: item, npc, achievement, quest, faction, currency, map.
--
-- Keyed by mount id. The Portuguese is in Locales/ptBR_Tips.lua, generated with this file.
local ADDON, ns = ...

ns.MountTips = {
    [401] = { year = 2021, -- Dark Phoenix
        text = "Sold by the guild vendors to a character Exalted with a guild that has {achievement:4988|Guild Glory of the Cataclysm Raider}. Joining a guild that already has it works, but the reputation with a new guild starts over. Once learnt, the mount is yours whatever guild you are in." },
    [802] = { year = 2018, -- Long-Forgotten Hippogryph
        text = "Five Ephemeral Crystals appear at the same time at random spots of {map:630|Azsuna}, many of them inside caves. Touching the first one starts 8 hours to touch the other four; dying loses the count. Other players are after the same crystals, and when somebody finishes they all vanish until the next round." },
    [1617] = { year = 2022, -- Verdant Skitterfly
        text = "Reach Renown 25 with {faction:2507|Dragonscale Expedition}. From then on it has a small chance to be inside every Expedition Scout's Pack." },
    [1656] = { year = 2023, -- Otto
        text = "A chain, most of it fishing.\n1. Get one {item:199340|Gold Coin of the Isles}: fished in the Dragon Isles, or 75 {item:199338|Copper Coin of the Isles} traded up with {npc:191608|The Great Swog}.\n2. Buy {item:202102|Immaculate Sac of Swog Treasures} from him with it. Most of the time it has {item:202042|Aquatic Shades}; when it does not, it takes another coin.\n3. Wearing the shades, dance for 5 minutes on the dance floor of the underwater bar in {map:2022|The Waking Shores}, at 19.6, 36.5.\n4. Pick up the {item:202061|Empty Fish Barrel} and fill it: 100 {item:202072|Frigid Floe Fish} (open water around Iskaara), 25 {item:202073|Calamitous Carp} (lava around the Obsidian Citadel) and 1 {item:202074|Kingfin, the Wise Whiskerfish} (water around Algeth'ar Academy).\n5. Take the barrel back to where you danced: Otto offers {quest:72738|The Way to an Otto's Heart}." },
    [1671] = { year = 2023, -- Duskwing Ohuna
        text = "{item:207026|Dreamsurge Coalescence} comes from the green orbs scattered over the zone where the Dreamsurge is active, and from the creatures killed there. {npc:210608|Celestine of the Harvest} is at the Dreamsurge symbol on the map." },
    [2615] = { year = 2026, -- Rootstalker Grimlynx, Vibrant Petalwing (Harandar rares)
        text = "Any rare of {map:2413|Harandar} can drop it, each with about 1 chance in 1,000. A rare gives loot once a day per character, so players repeat the round on other characters, level 80 ones included. Reports go from the first kill to more than 2,000." },
    [2708] = { year = 2026, -- Rootstalker Grimlynx, Vibrant Petalwing (Harandar rares)
        text = "Any rare of {map:2413|Harandar} can drop it, each with about 1 chance in 1,000. A rare gives loot once a day per character, so players repeat the round on other characters, level 80 ones included. Reports go from the first kill to more than 2,000." },
    [2747] = { year = 2026, -- Untainted Grove Crawler
        text = "In {map:2413|Harandar}: touch the Fungal Mallet at 41.3, 67.9, which gives a buff of 5 minutes, and with the buff ring the Mycelium Gong at 46.6, 67.8. The Sporespawned Cache appears beside the gong. One player only saw the gong after killing the creatures around it; another clicked the cache, got nothing, and received the mount by mail hours later." },
    [2749] = { year = 2026, -- Echo of Aln'sharan
        text = "1. Do the short chain of {npc:245637|Su'meera} that starts with {quest:91063|The Blooming Lattice} (65.4, 22.6 in {map:2413|Harandar}), then the chain of {npc:242358|Kuri} (67.8, 24.8), from {quest:90467|Tales of the Sky} to {quest:90474|The Legend of Aln'sharan}. One character of the account is enough.\n2. From then on the creatures of Harandar drop {item:255826|Mysterious Skyshards}, in delves and dungeons too; rares drop them far more often. Gather 500.\n3. Give them to Kuri at 66.2, 25.5 with the extra action button. Nothing seems to happen, but you get a buff.\n4. Aln'sharan flies high over the zone and hurts whoever gets near. Dismount in the air next to his head and click him, with a slow fall at hand.\nPlayers lost the buff, and the 500 shards with it, by joining a group or a battleground before step 4." },
    [2751] = { year = 2026, -- Augmented Stormray, Sanguine Harrower (Voidstorm rares)
        text = "Any rare of {map:2405|Voidstorm} can drop it, each with about 1 chance in 1,000. A rare gives loot once a day per character, so players repeat the round on other characters, level 80 ones included. Reports go from the first kill to more than 2,000." },
    [2758] = { year = 2026, -- Cobalt Dragonhawk, Cerulean Hawkstrider (Eversong Woods rares)
        text = "Any rare of {map:2395|Eversong Woods} can drop it, each with about 1 chance in 1,000. A rare gives loot once a day per character, so players repeat the round on other characters. Reports go from the first kill to more than 2,000." },
    [2760] = { year = 2026, -- Amani Sharptalon, Witherbark Pango (Zul'Aman rares)
        text = "Any rare of {map:2437|Zul'Aman} can drop it, each with about 1 chance in 1,000. A rare gives loot once a day per character, so players repeat the round on other characters. Reports go from a few kills to more than 2,000." },
    [2762] = { year = 2026, -- Cobalt Dragonhawk, Cerulean Hawkstrider (Eversong Woods rares)
        text = "Any rare of {map:2395|Eversong Woods} can drop it, each with about 1 chance in 1,000. A rare gives loot once a day per character, so players repeat the round on other characters. Reports go from the first kill to more than 2,000." },
    [2764] = { year = 2026, -- Duskbrute Harrower
        text = "{item:267299|Slayer's Duellum Trove} is what {faction:2770|Slayer's Duellum} gives each time the reputation bar fills again after the reputation is at its maximum. About 1 trove in 4 has the mount; the others may bring the same pet again and again." },
    [2767] = { year = 2026, -- Contained Stormarion Defender
        text = "Two caches can have it, a few in every hundred: {item:268485|Victorious Stormarion Pinnacle Cache}, the weekly one for finishing {quest:90962|Stormarion Assault}, and {item:260979|Victorious Stormarion Cache}, the one of its world quest. The world quest only shows up for a character that has finished the event once." },
    [2772] = { year = 2026, -- Blessed Amani Burrower
        text = "The journal says 1,600 {currency:3377|Unalloyed Abundance}, but {npc:241928|Chel the Chip} charges 6,400." },
    [2775] = { year = 2026, -- Amani Sharptalon, Witherbark Pango (Zul'Aman rares)
        text = "Any rare of {map:2437|Zul'Aman} can drop it, each with about 1 chance in 1,000. A rare gives loot once a day per character, so players repeat the round on other characters. Reports go from a few kills to more than 2,000." },
    [2778] = { year = 2026, -- Ancestral War Bear
        text = "The Honored Warrior's Cache is inside the base of the tree at 47.0, 82.4 of {map:2437|Zul'Aman}. Click it first: only then do the four Honored Warrior's Urns answer. Each urn calls a guardian that drops one token: {npc:255171|Nalorakk's Chosen} at 32.6, 83.5, {npc:255232|Halazzi's Chosen} at 34.5, 33.4, {npc:255233|Jan'alai's Chosen} at 54.7, 22.3 and {npc:255231|Akil'zon's Chosen} at 51.5, 84.9. With the four tokens, go back to the cache." },
    [2779] = { year = 2026, -- Witherbark Warbear Mother
        text = "Take 6 {item:242639|Practically Pork} with you (auction house, or the beasts outside) into the ritual site {map:2585|Broken Throne}, on tier 2 or higher. The Lost Bear Cub is hidden beside a tree at 55.8, 49.5, on a ledge you reach by jumping down: feed him 1 and he becomes the pet {item:269836|Chubs}. Summon Chubs at the Chewed Meat at 56.0, 38.5 and an angry warbear comes. Beat her; she turns friendly, and you feed her the other 5." },
    [2786] = { year = 2026, -- Hexed Vilefeather Eagle
        text = "The Abandoned Ritual Skull is in a small cave of {map:2437|Zul'Aman}, at 44.7, 44.1 (entrance at 44.2, 43.5), and asks for 1,000 {item:259361|Vile Essence}, dropped by the creatures of the elite area around 45.8, 40.2. Players count 6 to 7 hours.\nWhat makes it bearable: take {quest:91838|De Vile Diminished}, {quest:91836|Respect de Totem} and {quest:91835|Send Dem Home} there and do NOT hand them in. While they are in the log you keep an extra action button whose buff stacks 10 times, and each {npc:248775|Wild Guardian} killed stacks a second one; with both, players did it alone. Turn off any addon that hands quests in by itself. Who has done those quests does it on another character." },
    [2790] = { year = 2026, -- Insatiable Shredclaw
        text = "The cave is in the south of {map:2405|Voidstorm}, entrance at 48.9, 78.4. Inside, broken eggs make a maze of lightning circles; being hit sends you back to the entrance. The Final Clutch of Predaxas is at the end. Players say a circle stops hurting a little before it vanishes, and that a trail of wind on the ground shows the way." },
    [2827] = { year = 2026, -- Augmented Stormray, Sanguine Harrower (Voidstorm rares)
        text = "Any rare of {map:2405|Voidstorm} can drop it, each with about 1 chance in 1,000. A rare gives loot once a day per character, so players repeat the round on other characters, level 80 ones included. Reports go from the first kill to more than 2,000." },
    [2829] = { year = 2026, -- Lab-Grown Stormray
        text = "{achievement:62385|Staring Into The Void} asks for 7 {currency:3400|Uncontaminated Void Sample}: 1 at the start, then each week 1 from the weekly quest of {npc:248328|Void Researcher Anomander}, beside the console, and 1 from the weekly cache of {quest:90962|Stormarion Assault}. About 3 weeks. If the mount does not come with the achievement, look in the mail, or use Wings of the Void in the spellbook: it puts the item in your bag, wherever you are." },
    [2839] = { year = 2026, -- Delver's Arcane Golem
        text = "Inside the delve Gnarldor Isle, on any tier: the Sturdy Chest at 60.4, 68.1. The delve has three Sturdy Chests; the mount came from this one." },
    [2913] = { year = 2026, -- Vivid Chloroceros
        text = "{currency:3385|Luminous Dust} comes from the Glowing Moths scattered over {map:2413|Harandar}, 120 in all. Part of them only appears as your Renown with {faction:2704|Hara'ti} goes up: the player who mapped them advises reaching Renown 9 before hunting." },
    [2950] = { year = 2026, -- Luminous Sporeglider
        text = "It is made by combining 4 {item:269245|Delicious Sporesnack}. {npc:254176|Rotmire} gives one per week, on any difficulty: four weeks at least." },
    [2961] = { year = 2026, -- Void-Corrupted Hex Eagle
        text = "In the ritual site {map:2585|Broken Throne}, on tier 2 or higher. One of the four skulls around the ritual circle at 50.6, 47.3 has no candle: pick up the Misplaced Ritual Candle under the tree at 51.5, 47.8 and put it on the skull at the north-east of the circle. Then click the candles in the middle and kill the eagle that comes: it drops the mount. If three eaglets come instead, the candle was not in place." },
    [2964] = { year = 2026, -- Void-Touched Snapdragon
        text = "In the ritual site {map:2594|Daggerspine Point}, on any tier, up to 2 Washed Up Kelp appear per run, out of 8 spots along the shores. Clicking one calls creatures and, with a small chance, the Void-Touched Snapdragon, which drops the mount. Players check the kelp, leave the instance and enter again, without doing the ritual. Reports speak of 25 to 30 attempts." },
    [2965] = { year = 2026, -- Void-Corrupted Lynx
        text = "Players got it on tiers 1, 2 and 5 of the ritual sites: the tier does not seem to decide. One of them counted about 20 runs." },
    [2980] = { year = 2026, -- Spirit of Tok'jara
        text = "At Renown 10 with {faction:2772|Zul'jarra's Forces}, {npc:264611|Du'gal} (50.5, 63.9 in {map:2509|Vaults of Atal'Utek}) starts a chain of 6 quests, one per day, from {quest:96267|Ancestral Gems} to {quest:96305|The Innocent Essence}, which gives the mount. Six days at least, and the chain is of the character that started it." },
    [3005] = { year = 2026, -- Lindormi's six mounts (Timelost Saddle)
        text = "In Season 1 of Midnight, {item:275436|Timelost Saddle} came with {achievement:63097|Midnight Keystone Myth: Season 1}, 3,400 of Mythic+ rating, and expired when the season ended. Each saddle bought one of the mounts {npc:197711|Lindormi} sells, the player choosing which." },
    [3006] = { year = 2026, -- Lindormi's six mounts (Timelost Saddle)
        text = "In Season 1 of Midnight, {item:275436|Timelost Saddle} came with {achievement:63097|Midnight Keystone Myth: Season 1}, 3,400 of Mythic+ rating, and expired when the season ended. Each saddle bought one of the mounts {npc:197711|Lindormi} sells, the player choosing which." },
    [3007] = { year = 2026, -- Lindormi's six mounts (Timelost Saddle)
        text = "In Season 1 of Midnight, {item:275436|Timelost Saddle} came with {achievement:63097|Midnight Keystone Myth: Season 1}, 3,400 of Mythic+ rating, and expired when the season ended. Each saddle bought one of the mounts {npc:197711|Lindormi} sells, the player choosing which." },
    [3008] = { year = 2026, -- Lindormi's six mounts (Timelost Saddle)
        text = "In Season 1 of Midnight, {item:275436|Timelost Saddle} came with {achievement:63097|Midnight Keystone Myth: Season 1}, 3,400 of Mythic+ rating, and expired when the season ended. Each saddle bought one of the mounts {npc:197711|Lindormi} sells, the player choosing which." },
    [3009] = { year = 2026, -- Lindormi's six mounts (Timelost Saddle)
        text = "In Season 1 of Midnight, {item:275436|Timelost Saddle} came with {achievement:63097|Midnight Keystone Myth: Season 1}, 3,400 of Mythic+ rating, and expired when the season ended. Each saddle bought one of the mounts {npc:197711|Lindormi} sells, the player choosing which." },
    [3010] = { year = 2026, -- Lindormi's six mounts (Timelost Saddle)
        text = "In Season 1 of Midnight, {item:275436|Timelost Saddle} came with {achievement:63097|Midnight Keystone Myth: Season 1}, 3,400 of Mythic+ rating, and expired when the season ended. Each saddle bought one of the mounts {npc:197711|Lindormi} sells, the player choosing which." },
    [3031] = { year = 2026, -- Hexflame Reaver
        text = "{npc:258928|Ral'kala} is called by burning {item:274422|Ossified Relic} at a {npc:265151|Haunted Brazier} of {map:2512|The Coiled Isle}, 100 for each call, with the Nightmare mode of the hunts on. To get loot you must have put at least 1 relic in yourself and have hit him: the buff Whispers from De Other Side shows that your relic counted. He has no daily limit, so groups call him again and again. The daily hunt in the north of the isle gives 100 relics. While waiting, do not kill the creatures around the brazier: it brings snakes on the whole group." },
    [3036] = { year = 2026, -- Sun Festival's Painted Roc
        text = "It comes in {item:117394|Satchel of Chilled Goods}, given by the first {npc:25740|Ahune} of the day. Only the first satchel of the day of the whole account can have the mount. Since a fix of June 2026 that chance doubled, and it grows each day until the mount comes." },
    [3043] = { year = 2026, -- Corroded Soul Crusher
        text = "The item only says that the Delver's Journey unlocks it. Players report rank 5 of the Journey of Season 2." },
    [3051] = { year = 2026, -- Topaz Skyfang, Ruby Writhe (Coiled Isle rares)
        text = "Any rare of {map:2512|The Coiled Isle} can drop it, each with about 1 chance in 1,000. A rare gives loot once a day per character, so players repeat the round on other characters. Reports go from the first kill to more than 1,200." },
    [3061] = { year = 2026, -- Topaz Skyfang, Ruby Writhe (Coiled Isle rares)
        text = "Any rare of {map:2512|The Coiled Isle} can drop it, each with about 1 chance in 1,000. A rare gives loot once a day per character, so players repeat the round on other characters. Reports go from the first kill to more than 1,200." },
}
