-- RocketMount | Data/MountChances.lua
-- GENERATED by tools/coletar_dificuldades.py on 2026-09-28 -- do not edit by hand.
--
-- How often a mount came on each difficulty, the best first. `d` is the game's difficulty
-- id; a row with no `d` is a chest whose difficulty could not be told from what is in it.
-- Only mounts with two rows or more.
local ADDON, ns = ...

ns.MountChances = {
    [246] = { { count = 2247, outof = 65048 }, { d = 4, count = 1994, outof = 82128 } }, -- Azure Drake
    [247] = { { count = 2622, outof = 65048 }, { d = 4, count = 1747, outof = 82128 } }, -- Blue Drake
    [395] = { { d = 1, count = 1514, outof = 175024 }, { d = 2, count = 1073, outof = 139155 } }, -- Drake of the North Wind
    [396] = { { count = 1399, outof = 71625 }, { count = 559, outof = 51141 }, { d = 5, count = 70, outof = 7299 } }, -- Drake of the South Wind
    [415] = { { count = 549, outof = 32471 }, { d = 14, count = 158, outof = 17560 } }, -- Pureblood Fire Hawk
    [442] = { { count = 1334, outof = 40092 }, { count = 844, outof = 90093 }, { d = 4, count = 229, outof = 29801 }, { d = 5, count = 83, outof = 12607 } }, -- Blazing Drake
    [444] = { { count = 735, outof = 40092 }, { count = 1095, outof = 90093 }, { d = 5, count = 130, outof = 12607 } }, -- Life-Binder's Handmaiden
    [445] = { { count = 1272, outof = 110569 }, { count = 136, outof = 18919 }, { count = 278, outof = 44278 }, { d = 4, count = 174, outof = 32909 } }, -- Experiment 12-B
    [478] = { { count = 2178, outof = 54812 }, { d = 4, count = 527, outof = 18227 }, { d = 3, count = 170, outof = 40966 }, { d = 5, count = 96, outof = 24014 } }, -- Astral Cloud Serpent
    [531] = { { d = 6, count = 439, outof = 11100 }, { d = 3, count = 197, outof = 6605 }, { d = 5, count = 40, outof = 5093 }, { d = 4, count = 32, outof = 5009 } }, -- Spawn of Horridon
    [543] = { { d = 4, count = 646, outof = 14563 }, { d = 6, count = 1211, outof = 36146 }, { d = 3, count = 215, outof = 19857 }, { d = 5, count = 94, outof = 14987 } }, -- Clutch of Ji-Kun
    [899] = { { d = 16, count = 89, outof = 32281 }, { d = 15, count = 41, outof = 15870 }, { d = 14, count = 46, outof = 18996 }, { d = 17, count = 46, outof = 32124 } }, -- Abyss Worm
    [1481] = { { d = 23, count = 102, outof = 4704 }, { d = 2, count = 35, outof = 1917 } }, -- Cartel Master's Gearglider
}
