-- RocketMount | Data/MountExpansion.lua
-- GENERATED by tools/coletar_expansao.py on 2026-09-29 -- do not edit by hand.
--
-- The first mount id of each expansion. The game has no "expansion of a mount", but it
-- says the expansion of what a mount is tied to (the boss's instance, the faction, the
-- map of who sells it or drops it, the item), and it hands mount ids out in order: the
-- cut between two expansions is the id where those change side. `id` is the game's own
-- index of the expansion (the one of EXPANSION_NAME<id>).
local ADDON, ns = ...

ns.MountExpansion = {
    { id = 0, name = "Classic", min = 0 },
    { id = 1, name = "Burning Crusade", min = 123 },
    { id = 2, name = "Wrath of the Lich King", min = 237 },
    { id = 3, name = "Cataclysm", min = 393 },
    { id = 4, name = "Mists of Pandaria", min = 448 },
    { id = 5, name = "Warlords of Draenor", min = 603 },
    { id = 6, name = "Legion", min = 779 },
    { id = 7, name = "Battle for Azeroth", min = 993 },
    { id = 8, name = "Shadowlands", min = 1298 },
    { id = 9, name = "Dragonflight", min = 1588 },
    { id = 10, name = "The War Within", min = 2119 },
    { id = 11, name = "Midnight", min = 2693 },
    -- The ones that came late: the id is of one block, the instance or the item of another.
    late = {
        [633] = 6, -- Hellfire Infernal: Legion
        [803] = 8, -- Mastercraft Gravewing: Shadowlands
        [926] = 7, -- Alabaster Hyena: Battle for Azeroth
        [928] = 7, -- Dune Scavenger: Battle for Azeroth
        [933] = 7, -- Obsidian Krolusk: Battle for Azeroth
        [956] = 7, -- Leaping Veinseeker: Battle for Azeroth
        [958] = 7, -- Spectral Pterrorwing: Battle for Azeroth
        [963] = 7, -- Bloodgorged Crawg: Battle for Azeroth
        [1242] = 5, -- Beastlord's Irontusk: Warlords of Draenor
        [1243] = 5, -- Beastlord's Warwolf: Warlords of Draenor
        [1314] = 7, -- Drake of the Four Winds: Battle for Azeroth
        [1317] = 7, -- Waste Marauder: Battle for Azeroth
        [1318] = 7, -- Wastewander Skyterror: Battle for Azeroth
        [1319] = 7, -- Malevolent Drone: Battle for Azeroth
        [1320] = 7, -- Shadowbarb Drone: Battle for Azeroth
        [1322] = 7, -- Wriggling Parasite: Battle for Azeroth
        [1324] = 7, -- Elusive Quickhoof: Battle for Azeroth
        [1329] = 7, -- Springfur Alpaca: Battle for Azeroth
        [1467] = 9, -- Noble Bruffalon: Dragonflight
        [1469] = 9, -- Magmashell: Dragonflight
        [1470] = 9, -- Liquid Hot Magma Slug: Dragonflight
        [1474] = 9, -- Bestowed Thunderspine Packleader: Dragonflight
        [1478] = 9, -- Skyskin Hornstrider: Dragonflight
        [1546] = 9, -- Iskaara Trader's Ottuk: Dragonflight
        [1553] = 9, -- Liberated Slyvern: Dragonflight
        [1563] = 9, -- Highland Drake: Dragonflight
        [1597] = 8, -- Grimhowl: Shadowlands
        [1599] = 8, -- Eternal Gladiator's Soul Eater: Shadowlands
        [1773] = 7, -- Harbor Gryphon: Battle for Azeroth
        [1813] = 7, -- Mimiron's Jumpjets: Battle for Azeroth
        [2060] = 4, -- Golden Discus: Mists of Pandaria
        [2063] = 4, -- Mogu Hazeblazer: Mists of Pandaria
        [2064] = 4, -- Sky Surfer: Mists of Pandaria
        [2065] = 4, -- Daystorm Windsteed: Mists of Pandaria
        [2067] = 4, -- Forest Windsteed: Mists of Pandaria
        [2068] = 4, -- Dashing Windsteed: Mists of Pandaria
        [2069] = 4, -- Feathered Windsurfer: Mists of Pandaria
        [2070] = 4, -- Guardian Quilen: Mists of Pandaria
        [2071] = 4, -- Marble Quilen: Mists of Pandaria
        [2072] = 4, -- Gilded Riding Crane: Mists of Pandaria
        [2073] = 4, -- Pale Riding Crane: Mists of Pandaria
        [2074] = 4, -- Rose Riding Crane: Mists of Pandaria
        [2075] = 4, -- Silver Riding Crane: Mists of Pandaria
        [2076] = 4, -- Luxurious Riding Crane: Mists of Pandaria
        [2077] = 4, -- Tropical Riding Crane: Mists of Pandaria
        [2078] = 4, -- Snowy Riding Goat: Mists of Pandaria
        [2080] = 4, -- Little Red Riding Goat: Mists of Pandaria
        [2081] = 4, -- Bloody Skyscreamer: Mists of Pandaria
        [2083] = 4, -- Night Pterrorwing: Mists of Pandaria
        [2084] = 4, -- Jade Pterrordax: Mists of Pandaria
        [2085] = 4, -- Cobalt Juggernaut: Mists of Pandaria
        [2086] = 4, -- Fel Iron Juggernaut: Mists of Pandaria
        [2087] = 4, -- Purple Shado-Pan Riding Tiger: Mists of Pandaria
        [2088] = 4, -- Riverwalker Mushan: Mists of Pandaria
        [2089] = 4, -- Palehide Mushan Beast: Mists of Pandaria
        [2118] = 4, -- Amber Pterrordax: Mists of Pandaria
        [2142] = 4, -- August Phoenix: Mists of Pandaria
        [2143] = 4, -- Astral Emperor's Serpent: Mists of Pandaria
        [2161] = 11, -- Elder Glowmite: Midnight
        [2317] = 2, -- Enchanted Spellweave Carpet: Wrath of the Lich King
        [2470] = 5, -- Nightfall Skyreaver: Warlords of Draenor
        [2471] = 6, -- Ur'zul Fleshripper: Legion
        [2473] = 6, -- Broodling of Sinestra: Legion
        [2474] = 4, -- Copper-Maned Quilen: Mists of Pandaria
        [2567] = 11, -- Voidwing Dragonhawk: Midnight
        [2568] = 11, -- Lightwing Dragonhawk: Midnight
        [2586] = 7, -- Moonlit Nightsaber: Battle for Azeroth
        [2587] = 7, -- Ivory Savagemane: Battle for Azeroth
        [2598] = 11, -- Voidlight Surger: Midnight
        [2607] = 11, -- Ashes of Belo'ren: Midnight
        [2611] = 11, -- Dusk Grimlynx: Midnight
        [2614] = 11, -- Fierce Grimlynx: Midnight
        [2615] = 11, -- Rootstalker Grimlynx: Midnight
        [2616] = 11, -- Ivory Grimlynx: Midnight
        [2802] = 10, -- Geargrinder Mk. 11: The War Within
        [2803] = 8, -- Skypaw Glimmerfur: Shadowlands
        [2804] = 8, -- Crimson Lupine: Shadowlands
        [2806] = 9, -- Spawn of Vyranoth: Dragonflight
        [2815] = 8, -- Snowpaw Glimmerfur Prowler: Shadowlands
        [2915] = 10, -- Unbound Manawyrm: The War Within
        [2964] = 10, -- Void-Touched Snapdragon: The War Within
    },
}
