-- RocketMount | Data/RareDrops.lua
-- GENERATED by tools/coletar_raros.py on 2026-09-23 -- do not edit by hand.
--
-- Source: wowhead.com item pages, `Dropped by` list. For each rare (classification rare or
-- rare elite): the mount's item id, how many times it dropped (`count`) and in how many
-- kills (`outof`). These are Wowhead's samples, not Blizzard's rates -- a small `count` is
-- a rough estimate, and the alert says so.
local ADDON, ns = ...

ns.RareDrops = {
    [248741] = { name = "Rhazul",
        { item = 246735, count = 7, outof = 6391 }, -- Rootstalker Grimlynx
    },
    [249844] = { name = "Chironex",
        { item = 246735, count = 7, outof = 5714 }, -- Rootstalker Grimlynx
    },
    [249849] = { name = "Ha'kalawe",
        { item = 246735, count = 8, outof = 6653 }, -- Rootstalker Grimlynx
    },
    [249902] = { name = "Tallcap the Truthspreader",
        { item = 246735, count = 9, outof = 4488 }, -- Rootstalker Grimlynx
    },
    [249962] = { name = "Queen Lashtongue",
        { item = 246735, count = 12, outof = 6790 }, -- Rootstalker Grimlynx
    },
    [249997] = { name = "Chlorokyll",
        { item = 246735, count = 5, outof = 4997 }, -- Rootstalker Grimlynx
    },
    [250086] = { name = "Stumpy",
        { item = 246735, count = 9, outof = 5560 }, -- Rootstalker Grimlynx
    },
    [250180] = { name = "Serrasa",
        { item = 246735, count = 11, outof = 5494 }, -- Rootstalker Grimlynx
    },
    [250226] = { name = "Mindrot",
        { item = 246735, count = 7, outof = 5634 }, -- Rootstalker Grimlynx
    },
    [250231] = { name = "Dracaena",
        { item = 246735, count = 7, outof = 5862 }, -- Rootstalker Grimlynx
    },
    [250246] = { name = "Treetop",
        { item = 246735, count = 8, outof = 5193 }, -- Rootstalker Grimlynx
    },
    [250317] = { name = "Oro'ohna",
        { item = 246735, count = 15, outof = 5390 }, -- Rootstalker Grimlynx
    },
    [250321] = { name = "Pterrock",
        { item = 246735, count = 5, outof = 4191 }, -- Rootstalker Grimlynx
    },
    [250347] = { name = "Ahl'ua'huhi",
        { item = 246735, count = 7, outof = 5881 }, -- Rootstalker Grimlynx
    },
    [250358] = { name = "Annulus the Worldshaker",
        { item = 246735, count = 5, outof = 2508 }, -- Rootstalker Grimlynx
    },
}
